/* File generated by the BNF Converter (bnfc 2.9.7). */

#ifndef ABSYN_HEADER
#define ABSYN_HEADER

/* strdup was not in the ISO C standard before 6/2019 (C2x), but in POSIX 1003.1.
 * See: https://en.cppreference.com/w/c/experimental/dynamic/strdup
 * Setting _POSIX_C_SOURCE to 200809L activates strdup in string.h.
 */
#define _POSIX_C_SOURCE 200809L

#include <stddef.h>  /* NULL */
#include <string.h>  /* strdup */

/* C++ Abstract Syntax Interface.*/

/********************   TypeDef Section    ********************/

typedef int Integer;
typedef char Char;
typedef double Double;
typedef char* String;
typedef char* Ident;
typedef char* StellaIdent;
typedef char* ExtensionName;
typedef char* MemoryAddress;

/********************   Forward Declarations    ***********************/
struct Program_;
typedef struct Program_ *Program;

struct ListStellaIdent_;
typedef struct ListStellaIdent_ *ListStellaIdent;

struct LanguageDecl_;
typedef struct LanguageDecl_ *LanguageDecl;

struct Extension_;
typedef struct Extension_ *Extension;

struct ListExtensionName_;
typedef struct ListExtensionName_ *ListExtensionName;

struct ListExtension_;
typedef struct ListExtension_ *ListExtension;

struct Decl_;
typedef struct Decl_ *Decl;

struct ListDecl_;
typedef struct ListDecl_ *ListDecl;

struct LocalDecl_;
typedef struct LocalDecl_ *LocalDecl;

struct ListLocalDecl_;
typedef struct ListLocalDecl_ *ListLocalDecl;

struct Annotation_;
typedef struct Annotation_ *Annotation;

struct ListAnnotation_;
typedef struct ListAnnotation_ *ListAnnotation;

struct ParamDecl_;
typedef struct ParamDecl_ *ParamDecl;

struct ListParamDecl_;
typedef struct ListParamDecl_ *ListParamDecl;

struct ReturnType_;
typedef struct ReturnType_ *ReturnType;

struct ThrowType_;
typedef struct ThrowType_ *ThrowType;

struct Type_;
typedef struct Type_ *Type;

struct ListType_;
typedef struct ListType_ *ListType;

struct MatchCase_;
typedef struct MatchCase_ *MatchCase;

struct ListMatchCase_;
typedef struct ListMatchCase_ *ListMatchCase;

struct OptionalTyping_;
typedef struct OptionalTyping_ *OptionalTyping;

struct PatternData_;
typedef struct PatternData_ *PatternData;

struct ExprData_;
typedef struct ExprData_ *ExprData;

struct Pattern_;
typedef struct Pattern_ *Pattern;

struct ListPattern_;
typedef struct ListPattern_ *ListPattern;

struct LabelledPattern_;
typedef struct LabelledPattern_ *LabelledPattern;

struct ListLabelledPattern_;
typedef struct ListLabelledPattern_ *ListLabelledPattern;

struct Binding_;
typedef struct Binding_ *Binding;

struct ListBinding_;
typedef struct ListBinding_ *ListBinding;

struct Expr_;
typedef struct Expr_ *Expr;

struct ListExpr_;
typedef struct ListExpr_ *ListExpr;

struct PatternBinding_;
typedef struct PatternBinding_ *PatternBinding;

struct ListPatternBinding_;
typedef struct ListPatternBinding_ *ListPatternBinding;

struct LabelledEffect_;
typedef struct LabelledEffect_ *LabelledEffect;

struct ListLabelledEffect_;
typedef struct ListLabelledEffect_ *ListLabelledEffect;

struct Modality_;
typedef struct Modality_ *Modality;

struct ListModality_;
typedef struct ListModality_ *ListModality;

struct Handler_;
typedef struct Handler_ *Handler;

struct ListHandler_;
typedef struct ListHandler_ *ListHandler;

struct VariantFieldType_;
typedef struct VariantFieldType_ *VariantFieldType;

struct ListVariantFieldType_;
typedef struct ListVariantFieldType_ *ListVariantFieldType;

struct RecordFieldType_;
typedef struct RecordFieldType_ *RecordFieldType;

struct ListRecordFieldType_;
typedef struct ListRecordFieldType_ *ListRecordFieldType;

struct Typing_;
typedef struct Typing_ *Typing;

/********************   Abstract Syntax Classes    ********************/

struct Program_
{
  enum { is_AProgram } kind;
  union
  {
    struct { LanguageDecl languagedecl_; ListDecl listdecl_; ListExtension listextension_; } aProgram_;
  } u;
};

Program make_AProgram(LanguageDecl p0, ListExtension p1, ListDecl p2);

struct ListStellaIdent_
{
  StellaIdent stellaident_;
  ListStellaIdent liststellaident_;
};

ListStellaIdent make_ListStellaIdent(StellaIdent p1, ListStellaIdent p2);

struct LanguageDecl_
{
  enum { is_LanguageCore } kind;
  union
  {
  } u;
};

LanguageDecl make_LanguageCore(void);

struct Extension_
{
  enum { is_AnExtension } kind;
  union
  {
    struct { ListExtensionName listextensionname_; } anExtension_;
  } u;
};

Extension make_AnExtension(ListExtensionName p0);

struct ListExtensionName_
{
  ExtensionName extensionname_;
  ListExtensionName listextensionname_;
};

ListExtensionName make_ListExtensionName(ExtensionName p1, ListExtensionName p2);

struct ListExtension_
{
  Extension extension_;
  ListExtension listextension_;
};

ListExtension make_ListExtension(Extension p1, ListExtension p2);

struct Decl_
{
  enum { is_DeclFun, is_DeclFunGeneric, is_DeclFunMod, is_DeclTypeAlias, is_DeclExceptionType, is_DeclExceptionVariant } kind;
  union
  {
    struct { Expr expr_; ListAnnotation listannotation_; ListDecl listdecl_; ListParamDecl listparamdecl_; ReturnType returntype_; StellaIdent stellaident_; ThrowType throwtype_; } declFun_;
    struct { Expr expr_; ListAnnotation listannotation_; ListDecl listdecl_; ListParamDecl listparamdecl_; ListStellaIdent liststellaident_; ReturnType returntype_; StellaIdent stellaident_; ThrowType throwtype_; } declFunGeneric_;
    struct { Expr expr_; ListAnnotation listannotation_; ListDecl listdecl_; ListModality listmodality_; ListParamDecl listparamdecl_; ReturnType returntype_; StellaIdent stellaident_; ThrowType throwtype_; } declFunMod_;
    struct { StellaIdent stellaident_; Type type_; } declTypeAlias_;
    struct { Type type_; } declExceptionType_;
    struct { StellaIdent stellaident_; Type type_; } declExceptionVariant_;
  } u;
};

Decl make_DeclFun(ListAnnotation p0, StellaIdent p1, ListParamDecl p2, ReturnType p3, ThrowType p4, ListDecl p5, Expr p6);
Decl make_DeclFunGeneric(ListAnnotation p0, StellaIdent p1, ListStellaIdent p2, ListParamDecl p3, ReturnType p4, ThrowType p5, ListDecl p6, Expr p7);
Decl make_DeclFunMod(ListAnnotation p0, ListModality p1, StellaIdent p2, ListParamDecl p3, ReturnType p4, ThrowType p5, ListDecl p6, Expr p7);
Decl make_DeclTypeAlias(StellaIdent p0, Type p1);
Decl make_DeclExceptionType(Type p0);
Decl make_DeclExceptionVariant(StellaIdent p0, Type p1);

struct ListDecl_
{
  Decl decl_;
  ListDecl listdecl_;
};

ListDecl make_ListDecl(Decl p1, ListDecl p2);

struct LocalDecl_
{
  enum { is_ALocalDecl } kind;
  union
  {
    struct { Decl decl_; } aLocalDecl_;
  } u;
};

LocalDecl make_ALocalDecl(Decl p0);

struct ListLocalDecl_
{
  LocalDecl localdecl_;
  ListLocalDecl listlocaldecl_;
};

ListLocalDecl make_ListLocalDecl(LocalDecl p1, ListLocalDecl p2);

struct Annotation_
{
  enum { is_InlineAnnotation } kind;
  union
  {
  } u;
};

Annotation make_InlineAnnotation(void);

struct ListAnnotation_
{
  Annotation annotation_;
  ListAnnotation listannotation_;
};

ListAnnotation make_ListAnnotation(Annotation p1, ListAnnotation p2);

struct ParamDecl_
{
  enum { is_AParamDecl } kind;
  union
  {
    struct { StellaIdent stellaident_; Type type_; } aParamDecl_;
  } u;
};

ParamDecl make_AParamDecl(StellaIdent p0, Type p1);

struct ListParamDecl_
{
  ParamDecl paramdecl_;
  ListParamDecl listparamdecl_;
};

ListParamDecl make_ListParamDecl(ParamDecl p1, ListParamDecl p2);

struct ReturnType_
{
  enum { is_NoReturnType, is_SomeReturnType } kind;
  union
  {
    struct { Type type_; } someReturnType_;
  } u;
};

ReturnType make_NoReturnType(void);
ReturnType make_SomeReturnType(Type p0);

struct ThrowType_
{
  enum { is_NoThrowType, is_SomeThrowType } kind;
  union
  {
    struct { ListType listtype_; } someThrowType_;
  } u;
};

ThrowType make_NoThrowType(void);
ThrowType make_SomeThrowType(ListType p0);

struct Type_
{
  enum { is_TypeMod, is_TypeAuto, is_TypeFun, is_TypeForAll, is_TypeRec, is_TypeSum, is_TypeTuple, is_TypeRecord, is_TypeVariant, is_TypeList, is_TypeBool, is_TypeNat, is_TypeUnit, is_TypeTop, is_TypeBottom, is_TypeRef, is_TypeVar } kind;
  union
  {
    struct { Modality modality_; Type type_; } typeMod_;
    struct { ListType listtype_; Type type_; } typeFun_;
    struct { ListStellaIdent liststellaident_; Type type_; } typeForAll_;
    struct { StellaIdent stellaident_; Type type_; } typeRec_;
    struct { Type type_1, type_2; } typeSum_;
    struct { ListType listtype_; } typeTuple_;
    struct { ListRecordFieldType listrecordfieldtype_; } typeRecord_;
    struct { ListVariantFieldType listvariantfieldtype_; } typeVariant_;
    struct { Type type_; } typeList_;
    struct { Type type_; } typeRef_;
    struct { StellaIdent stellaident_; } typeVar_;
  } u;
};

Type make_TypeMod(Modality p0, Type p1);
Type make_TypeAuto(void);
Type make_TypeFun(ListType p0, Type p1);
Type make_TypeForAll(ListStellaIdent p0, Type p1);
Type make_TypeRec(StellaIdent p0, Type p1);
Type make_TypeSum(Type p0, Type p1);
Type make_TypeTuple(ListType p0);
Type make_TypeRecord(ListRecordFieldType p0);
Type make_TypeVariant(ListVariantFieldType p0);
Type make_TypeList(Type p0);
Type make_TypeBool(void);
Type make_TypeNat(void);
Type make_TypeUnit(void);
Type make_TypeTop(void);
Type make_TypeBottom(void);
Type make_TypeRef(Type p0);
Type make_TypeVar(StellaIdent p0);

struct ListType_
{
  Type type_;
  ListType listtype_;
};

ListType make_ListType(Type p1, ListType p2);

struct MatchCase_
{
  enum { is_AMatchCase } kind;
  union
  {
    struct { Expr expr_; Pattern pattern_; } aMatchCase_;
  } u;
};

MatchCase make_AMatchCase(Pattern p0, Expr p1);

struct ListMatchCase_
{
  MatchCase matchcase_;
  ListMatchCase listmatchcase_;
};

ListMatchCase make_ListMatchCase(MatchCase p1, ListMatchCase p2);

struct OptionalTyping_
{
  enum { is_NoTyping, is_SomeTyping } kind;
  union
  {
    struct { Type type_; } someTyping_;
  } u;
};

OptionalTyping make_NoTyping(void);
OptionalTyping make_SomeTyping(Type p0);

struct PatternData_
{
  enum { is_NoPatternData, is_SomePatternData } kind;
  union
  {
    struct { Pattern pattern_; } somePatternData_;
  } u;
};

PatternData make_NoPatternData(void);
PatternData make_SomePatternData(Pattern p0);

struct ExprData_
{
  enum { is_NoExprData, is_SomeExprData } kind;
  union
  {
    struct { Expr expr_; } someExprData_;
  } u;
};

ExprData make_NoExprData(void);
ExprData make_SomeExprData(Expr p0);

struct Pattern_
{
  enum { is_PatternCastAs, is_PatternAsc, is_PatternVariant, is_PatternInl, is_PatternInr, is_PatternTuple, is_PatternRecord, is_PatternList, is_PatternCons, is_PatternFalse, is_PatternTrue, is_PatternUnit, is_PatternInt, is_PatternSucc, is_PatternVar } kind;
  union
  {
    struct { Pattern pattern_; Type type_; } patternCastAs_;
    struct { Pattern pattern_; Type type_; } patternAsc_;
    struct { PatternData patterndata_; StellaIdent stellaident_; } patternVariant_;
    struct { Pattern pattern_; } patternInl_;
    struct { Pattern pattern_; } patternInr_;
    struct { ListPattern listpattern_; } patternTuple_;
    struct { ListLabelledPattern listlabelledpattern_; } patternRecord_;
    struct { ListPattern listpattern_; } patternList_;
    struct { Pattern pattern_1, pattern_2; } patternCons_;
    struct { Integer integer_; } patternInt_;
    struct { Pattern pattern_; } patternSucc_;
    struct { StellaIdent stellaident_; } patternVar_;
  } u;
};

Pattern make_PatternCastAs(Pattern p0, Type p1);
Pattern make_PatternAsc(Pattern p0, Type p1);
Pattern make_PatternVariant(StellaIdent p0, PatternData p1);
Pattern make_PatternInl(Pattern p0);
Pattern make_PatternInr(Pattern p0);
Pattern make_PatternTuple(ListPattern p0);
Pattern make_PatternRecord(ListLabelledPattern p0);
Pattern make_PatternList(ListPattern p0);
Pattern make_PatternCons(Pattern p0, Pattern p1);
Pattern make_PatternFalse(void);
Pattern make_PatternTrue(void);
Pattern make_PatternUnit(void);
Pattern make_PatternInt(Integer p0);
Pattern make_PatternSucc(Pattern p0);
Pattern make_PatternVar(StellaIdent p0);

struct ListPattern_
{
  Pattern pattern_;
  ListPattern listpattern_;
};

ListPattern make_ListPattern(Pattern p1, ListPattern p2);

struct LabelledPattern_
{
  enum { is_ALabelledPattern } kind;
  union
  {
    struct { Pattern pattern_; StellaIdent stellaident_; } aLabelledPattern_;
  } u;
};

LabelledPattern make_ALabelledPattern(StellaIdent p0, Pattern p1);

struct ListLabelledPattern_
{
  LabelledPattern labelledpattern_;
  ListLabelledPattern listlabelledpattern_;
};

ListLabelledPattern make_ListLabelledPattern(LabelledPattern p1, ListLabelledPattern p2);

struct Binding_
{
  enum { is_ABinding } kind;
  union
  {
    struct { Expr expr_; StellaIdent stellaident_; } aBinding_;
  } u;
};

Binding make_ABinding(StellaIdent p0, Expr p1);

struct ListBinding_
{
  Binding binding_;
  ListBinding listbinding_;
};

ListBinding make_ListBinding(Binding p1, ListBinding p2);

struct Expr_
{
  enum { is_Sequence, is_Assign, is_If, is_Let, is_LetRec, is_ModLet, is_TypeAbstraction, is_LessThan, is_LessThanOrEqual, is_GreaterThan, is_GreaterThanOrEqual, is_Equal, is_NotEqual, is_TypeAsc, is_TypeCast, is_Abstraction, is_ModBox, is_Variant, is_Match, is_List, is_Add, is_Subtract, is_LogicOr, is_Multiply, is_Divide, is_LogicAnd, is_Ref, is_Deref, is_Application, is_TypeApplication, is_DotRecord, is_DotTuple, is_Tuple, is_Record, is_ConsList, is_Head, is_IsEmpty, is_Tail, is_Panic, is_Throw, is_TryCatch, is_TryWith, is_TryCastAs, is_Inl, is_Inr, is_Succ, is_LogicNot, is_Pred, is_IsZero, is_ModDo, is_ModHandle, is_Fix, is_NatRec, is_Fold, is_Unfold, is_ConstTrue, is_ConstFalse, is_ConstUnit, is_ConstInt, is_ConstMemory, is_Var } kind;
  union
  {
    struct { Expr expr_1, expr_2; } sequence_;
    struct { Expr expr_1, expr_2; } assign_;
    struct { Expr expr_1, expr_2, expr_3; } if_;
    struct { Expr expr_; ListPatternBinding listpatternbinding_; } let_;
    struct { Expr expr_; ListPatternBinding listpatternbinding_; } letRec_;
    struct { Expr expr_; ListPatternBinding listpatternbinding_; Modality modality_1, modality_2; } modLet_;
    struct { Expr expr_; ListStellaIdent liststellaident_; } typeAbstraction_;
    struct { Expr expr_1, expr_2; } lessThan_;
    struct { Expr expr_1, expr_2; } lessThanOrEqual_;
    struct { Expr expr_1, expr_2; } greaterThan_;
    struct { Expr expr_1, expr_2; } greaterThanOrEqual_;
    struct { Expr expr_1, expr_2; } equal_;
    struct { Expr expr_1, expr_2; } notEqual_;
    struct { Expr expr_; Type type_; } typeAsc_;
    struct { Expr expr_; Type type_; } typeCast_;
    struct { Expr expr_; ListParamDecl listparamdecl_; } abstraction_;
    struct { Expr expr_; Modality modality_; } modBox_;
    struct { ExprData exprdata_; StellaIdent stellaident_; } variant_;
    struct { Expr expr_; ListMatchCase listmatchcase_; } match_;
    struct { ListExpr listexpr_; } list_;
    struct { Expr expr_1, expr_2; } add_;
    struct { Expr expr_1, expr_2; } subtract_;
    struct { Expr expr_1, expr_2; } logicOr_;
    struct { Expr expr_1, expr_2; } multiply_;
    struct { Expr expr_1, expr_2; } divide_;
    struct { Expr expr_1, expr_2; } logicAnd_;
    struct { Expr expr_; } ref_;
    struct { Expr expr_; } deref_;
    struct { Expr expr_; ListExpr listexpr_; } application_;
    struct { Expr expr_; ListType listtype_; } typeApplication_;
    struct { Expr expr_; StellaIdent stellaident_; } dotRecord_;
    struct { Expr expr_; Integer integer_; } dotTuple_;
    struct { ListExpr listexpr_; } tuple_;
    struct { ListBinding listbinding_; } record_;
    struct { Expr expr_1, expr_2; } consList_;
    struct { Expr expr_; } head_;
    struct { Expr expr_; } isEmpty_;
    struct { Expr expr_; } tail_;
    struct { Expr expr_; } throw_;
    struct { Expr expr_1, expr_2; Pattern pattern_; } tryCatch_;
    struct { Expr expr_1, expr_2; } tryWith_;
    struct { Expr expr_1, expr_2, expr_3; Pattern pattern_; Type type_; } tryCastAs_;
    struct { Expr expr_; } inl_;
    struct { Expr expr_; } inr_;
    struct { Expr expr_; } succ_;
    struct { Expr expr_; } logicNot_;
    struct { Expr expr_; } pred_;
    struct { Expr expr_; } isZero_;
    struct { Expr expr_; StellaIdent stellaident_; } modDo_;
    struct { Expr expr_; ListHandler listhandler_; } modHandle_;
    struct { Expr expr_; } fix_;
    struct { Expr expr_1, expr_2, expr_3; } natRec_;
    struct { Expr expr_; Type type_; } fold_;
    struct { Expr expr_; Type type_; } unfold_;
    struct { Integer integer_; } constInt_;
    struct { MemoryAddress memoryaddress_; } constMemory_;
    struct { StellaIdent stellaident_; } var_;
  } u;
};

Expr make_Sequence(Expr p0, Expr p1);
Expr make_Assign(Expr p0, Expr p1);
Expr make_If(Expr p0, Expr p1, Expr p2);
Expr make_Let(ListPatternBinding p0, Expr p1);
Expr make_LetRec(ListPatternBinding p0, Expr p1);
Expr make_ModLet(Modality p0, Modality p1, ListPatternBinding p2, Expr p3);
Expr make_TypeAbstraction(ListStellaIdent p0, Expr p1);
Expr make_LessThan(Expr p0, Expr p1);
Expr make_LessThanOrEqual(Expr p0, Expr p1);
Expr make_GreaterThan(Expr p0, Expr p1);
Expr make_GreaterThanOrEqual(Expr p0, Expr p1);
Expr make_Equal(Expr p0, Expr p1);
Expr make_NotEqual(Expr p0, Expr p1);
Expr make_TypeAsc(Expr p0, Type p1);
Expr make_TypeCast(Expr p0, Type p1);
Expr make_Abstraction(ListParamDecl p0, Expr p1);
Expr make_ModBox(Modality p0, Expr p1);
Expr make_Variant(StellaIdent p0, ExprData p1);
Expr make_Match(Expr p0, ListMatchCase p1);
Expr make_List(ListExpr p0);
Expr make_Add(Expr p0, Expr p1);
Expr make_Subtract(Expr p0, Expr p1);
Expr make_LogicOr(Expr p0, Expr p1);
Expr make_Multiply(Expr p0, Expr p1);
Expr make_Divide(Expr p0, Expr p1);
Expr make_LogicAnd(Expr p0, Expr p1);
Expr make_Ref(Expr p0);
Expr make_Deref(Expr p0);
Expr make_Application(Expr p0, ListExpr p1);
Expr make_TypeApplication(Expr p0, ListType p1);
Expr make_DotRecord(Expr p0, StellaIdent p1);
Expr make_DotTuple(Expr p0, Integer p1);
Expr make_Tuple(ListExpr p0);
Expr make_Record(ListBinding p0);
Expr make_ConsList(Expr p0, Expr p1);
Expr make_Head(Expr p0);
Expr make_IsEmpty(Expr p0);
Expr make_Tail(Expr p0);
Expr make_Panic(void);
Expr make_Throw(Expr p0);
Expr make_TryCatch(Expr p0, Pattern p1, Expr p2);
Expr make_TryWith(Expr p0, Expr p1);
Expr make_TryCastAs(Expr p0, Type p1, Pattern p2, Expr p3, Expr p4);
Expr make_Inl(Expr p0);
Expr make_Inr(Expr p0);
Expr make_Succ(Expr p0);
Expr make_LogicNot(Expr p0);
Expr make_Pred(Expr p0);
Expr make_IsZero(Expr p0);
Expr make_ModDo(StellaIdent p0, Expr p1);
Expr make_ModHandle(Expr p0, ListHandler p1);
Expr make_Fix(Expr p0);
Expr make_NatRec(Expr p0, Expr p1, Expr p2);
Expr make_Fold(Type p0, Expr p1);
Expr make_Unfold(Type p0, Expr p1);
Expr make_ConstTrue(void);
Expr make_ConstFalse(void);
Expr make_ConstUnit(void);
Expr make_ConstInt(Integer p0);
Expr make_ConstMemory(MemoryAddress p0);
Expr make_Var(StellaIdent p0);

struct ListExpr_
{
  Expr expr_;
  ListExpr listexpr_;
};

ListExpr make_ListExpr(Expr p1, ListExpr p2);

struct PatternBinding_
{
  enum { is_APatternBinding } kind;
  union
  {
    struct { Expr expr_; Pattern pattern_; } aPatternBinding_;
  } u;
};

PatternBinding make_APatternBinding(Pattern p0, Expr p1);

struct ListPatternBinding_
{
  PatternBinding patternbinding_;
  ListPatternBinding listpatternbinding_;
};

ListPatternBinding make_ListPatternBinding(PatternBinding p1, ListPatternBinding p2);

struct LabelledEffect_
{
  enum { is_ALabelledEffect } kind;
  union
  {
    struct { StellaIdent stellaident_; Type type_; } aLabelledEffect_;
  } u;
};

LabelledEffect make_ALabelledEffect(StellaIdent p0, Type p1);

struct ListLabelledEffect_
{
  LabelledEffect labelledeffect_;
  ListLabelledEffect listlabelledeffect_;
};

ListLabelledEffect make_ListLabelledEffect(LabelledEffect p1, ListLabelledEffect p2);

struct Modality_
{
  enum { is_ModalityLock, is_ModalityAbs, is_ModalityRel } kind;
  union
  {
    struct { ListLabelledEffect listlabelledeffect_; } modalityAbs_;
    struct { ListLabelledEffect listlabelledeffect_; ListStellaIdent liststellaident_; } modalityRel_;
  } u;
};

Modality make_ModalityLock(void);
Modality make_ModalityAbs(ListLabelledEffect p0);
Modality make_ModalityRel(ListStellaIdent p0, ListLabelledEffect p1);

struct ListModality_
{
  Modality modality_;
  ListModality listmodality_;
};

ListModality make_ListModality(Modality p1, ListModality p2);

struct Handler_
{
  enum { is_HandlerReturn, is_HandlerLabel } kind;
  union
  {
    struct { Expr expr_; Pattern pattern_; } handlerReturn_;
    struct { Expr expr_; LabelledEffect labelledeffect_; Pattern pattern_; StellaIdent stellaident_; } handlerLabel_;
  } u;
};

Handler make_HandlerReturn(Pattern p0, Expr p1);
Handler make_HandlerLabel(LabelledEffect p0, Pattern p1, StellaIdent p2, Expr p3);

struct ListHandler_
{
  Handler handler_;
  ListHandler listhandler_;
};

ListHandler make_ListHandler(Handler p1, ListHandler p2);

struct VariantFieldType_
{
  enum { is_AVariantFieldType } kind;
  union
  {
    struct { OptionalTyping optionaltyping_; StellaIdent stellaident_; } aVariantFieldType_;
  } u;
};

VariantFieldType make_AVariantFieldType(StellaIdent p0, OptionalTyping p1);

struct ListVariantFieldType_
{
  VariantFieldType variantfieldtype_;
  ListVariantFieldType listvariantfieldtype_;
};

ListVariantFieldType make_ListVariantFieldType(VariantFieldType p1, ListVariantFieldType p2);

struct RecordFieldType_
{
  enum { is_ARecordFieldType } kind;
  union
  {
    struct { StellaIdent stellaident_; Type type_; } aRecordFieldType_;
  } u;
};

RecordFieldType make_ARecordFieldType(StellaIdent p0, Type p1);

struct ListRecordFieldType_
{
  RecordFieldType recordfieldtype_;
  ListRecordFieldType listrecordfieldtype_;
};

ListRecordFieldType make_ListRecordFieldType(RecordFieldType p1, ListRecordFieldType p2);

struct Typing_
{
  enum { is_ATyping } kind;
  union
  {
    struct { Expr expr_; Type type_; } aTyping_;
  } u;
};

Typing make_ATyping(Expr p0, Type p1);

/***************************   Cloning   ******************************/

Program clone_Program(Program p);
ListStellaIdent clone_ListStellaIdent(ListStellaIdent p);
LanguageDecl clone_LanguageDecl(LanguageDecl p);
Extension clone_Extension(Extension p);
ListExtensionName clone_ListExtensionName(ListExtensionName p);
ListExtension clone_ListExtension(ListExtension p);
Decl clone_Decl(Decl p);
ListDecl clone_ListDecl(ListDecl p);
LocalDecl clone_LocalDecl(LocalDecl p);
ListLocalDecl clone_ListLocalDecl(ListLocalDecl p);
Annotation clone_Annotation(Annotation p);
ListAnnotation clone_ListAnnotation(ListAnnotation p);
ParamDecl clone_ParamDecl(ParamDecl p);
ListParamDecl clone_ListParamDecl(ListParamDecl p);
ReturnType clone_ReturnType(ReturnType p);
ThrowType clone_ThrowType(ThrowType p);
Type clone_Type(Type p);
ListType clone_ListType(ListType p);
MatchCase clone_MatchCase(MatchCase p);
ListMatchCase clone_ListMatchCase(ListMatchCase p);
OptionalTyping clone_OptionalTyping(OptionalTyping p);
PatternData clone_PatternData(PatternData p);
ExprData clone_ExprData(ExprData p);
Pattern clone_Pattern(Pattern p);
ListPattern clone_ListPattern(ListPattern p);
LabelledPattern clone_LabelledPattern(LabelledPattern p);
ListLabelledPattern clone_ListLabelledPattern(ListLabelledPattern p);
Binding clone_Binding(Binding p);
ListBinding clone_ListBinding(ListBinding p);
Expr clone_Expr(Expr p);
ListExpr clone_ListExpr(ListExpr p);
PatternBinding clone_PatternBinding(PatternBinding p);
ListPatternBinding clone_ListPatternBinding(ListPatternBinding p);
LabelledEffect clone_LabelledEffect(LabelledEffect p);
ListLabelledEffect clone_ListLabelledEffect(ListLabelledEffect p);
Modality clone_Modality(Modality p);
ListModality clone_ListModality(ListModality p);
Handler clone_Handler(Handler p);
ListHandler clone_ListHandler(ListHandler p);
VariantFieldType clone_VariantFieldType(VariantFieldType p);
ListVariantFieldType clone_ListVariantFieldType(ListVariantFieldType p);
RecordFieldType clone_RecordFieldType(RecordFieldType p);
ListRecordFieldType clone_ListRecordFieldType(ListRecordFieldType p);
Typing clone_Typing(Typing p);

/********************   Recursive Destructors    **********************/

/* These free an entire abstract syntax tree
 * including all subtrees and strings.
 *
 * Will not work properly if there is sharing in the tree,
 * i.e., when some pointers are aliased.  In this case
 * it will attempt to free the same memory twice.
 */

void free_Program(Program p);
void free_ListStellaIdent(ListStellaIdent p);
void free_LanguageDecl(LanguageDecl p);
void free_Extension(Extension p);
void free_ListExtensionName(ListExtensionName p);
void free_ListExtension(ListExtension p);
void free_Decl(Decl p);
void free_ListDecl(ListDecl p);
void free_LocalDecl(LocalDecl p);
void free_ListLocalDecl(ListLocalDecl p);
void free_Annotation(Annotation p);
void free_ListAnnotation(ListAnnotation p);
void free_ParamDecl(ParamDecl p);
void free_ListParamDecl(ListParamDecl p);
void free_ReturnType(ReturnType p);
void free_ThrowType(ThrowType p);
void free_Type(Type p);
void free_ListType(ListType p);
void free_MatchCase(MatchCase p);
void free_ListMatchCase(ListMatchCase p);
void free_OptionalTyping(OptionalTyping p);
void free_PatternData(PatternData p);
void free_ExprData(ExprData p);
void free_Pattern(Pattern p);
void free_ListPattern(ListPattern p);
void free_LabelledPattern(LabelledPattern p);
void free_ListLabelledPattern(ListLabelledPattern p);
void free_Binding(Binding p);
void free_ListBinding(ListBinding p);
void free_Expr(Expr p);
void free_ListExpr(ListExpr p);
void free_PatternBinding(PatternBinding p);
void free_ListPatternBinding(ListPatternBinding p);
void free_LabelledEffect(LabelledEffect p);
void free_ListLabelledEffect(ListLabelledEffect p);
void free_Modality(Modality p);
void free_ListModality(ListModality p);
void free_Handler(Handler p);
void free_ListHandler(ListHandler p);
void free_VariantFieldType(VariantFieldType p);
void free_ListVariantFieldType(ListVariantFieldType p);
void free_RecordFieldType(RecordFieldType p);
void free_ListRecordFieldType(ListRecordFieldType p);
void free_Typing(Typing p);

/********************   Defined Constructors    ***********************/

#define make_patternCons(h,t) \
  make_PatternCons (h, t)

#endif
