/* File generated by the BNF Converter (bnfc 2.9.7). */

#include "Parser.h"
#include "Printer.h"
#include "Absyn.h"

/* *********** Conversion between Koka and C string **********  */
uint8_t* string_to_chars(kk_string_t str, kk_context_t* _ctx) {
  kk_ssize_t len;
  const uint8_t* cstr = kk_string_buf_borrow(str, &len, _ctx);
  return cstr;
}
kk_string_t chars_to_string(char* str, kk_context_t* _ctx) {
  kk_string_t kstr = kk_string_alloc_from_utf8(str, _ctx);
  return kstr;
}

/* ************** Handle reserved BNFC types ************ */
kk_stella_syntax_ast__ident convert_Ident(Ident ident, kk_context_t* _ctx) {
  kk_string_t str = chars_to_string(ident, _ctx);
  return kk_stella_syntax_ast__new_Ident(str, _ctx);
}
kk_integer_t convert_Integer(Integer i, kk_context_t* _ctx) {
  return kk_integer_from_int(i, _ctx);
}

/* ************** Declarations ************ */
kk_stella_syntax_ast__stellaIdent convert_StellaIdent(StellaIdent stellaIdent, kk_context_t* _ctx);
kk_stella_syntax_ast__extensionName convert_ExtensionName(ExtensionName extensionName, kk_context_t* _ctx);
kk_stella_syntax_ast__memoryAddress convert_MemoryAddress(MemoryAddress memoryAddress, kk_context_t* _ctx);
kk_stella_syntax_ast__program convert_Program(Program program, kk_context_t* _ctx);
kk_std_core_types__list convert_ListStellaIdent(ListStellaIdent listStellaIdent, kk_context_t* _ctx);
kk_stella_syntax_ast__languageDecl convert_LanguageDecl(LanguageDecl languageDecl, kk_context_t* _ctx);
kk_stella_syntax_ast__extension convert_Extension(Extension extension, kk_context_t* _ctx);
kk_std_core_types__list convert_ListExtensionName(ListExtensionName listExtensionName, kk_context_t* _ctx);
kk_std_core_types__list convert_ListExtension(ListExtension listExtension, kk_context_t* _ctx);
kk_stella_syntax_ast__decl convert_Decl(Decl decl, kk_context_t* _ctx);
kk_std_core_types__list convert_ListDecl(ListDecl listDecl, kk_context_t* _ctx);
kk_stella_syntax_ast__localDecl convert_LocalDecl(LocalDecl localDecl, kk_context_t* _ctx);
kk_std_core_types__list convert_ListLocalDecl(ListLocalDecl listLocalDecl, kk_context_t* _ctx);
kk_stella_syntax_ast__annotation convert_Annotation(Annotation annotation, kk_context_t* _ctx);
kk_std_core_types__list convert_ListAnnotation(ListAnnotation listAnnotation, kk_context_t* _ctx);
kk_stella_syntax_ast__paramDecl convert_ParamDecl(ParamDecl paramDecl, kk_context_t* _ctx);
kk_std_core_types__list convert_ListParamDecl(ListParamDecl listParamDecl, kk_context_t* _ctx);
kk_stella_syntax_ast__returnType convert_ReturnType(ReturnType returnType, kk_context_t* _ctx);
kk_stella_syntax_ast__throwType convert_ThrowType(ThrowType throwType, kk_context_t* _ctx);
kk_stella_syntax_ast__type__ convert_Type(Type type, kk_context_t* _ctx);
kk_std_core_types__list convert_ListType(ListType listType, kk_context_t* _ctx);
kk_stella_syntax_ast__matchCase convert_MatchCase(MatchCase matchCase, kk_context_t* _ctx);
kk_std_core_types__list convert_ListMatchCase(ListMatchCase listMatchCase, kk_context_t* _ctx);
kk_stella_syntax_ast__optionalTyping convert_OptionalTyping(OptionalTyping optionalTyping, kk_context_t* _ctx);
kk_stella_syntax_ast__patternData convert_PatternData(PatternData patternData, kk_context_t* _ctx);
kk_stella_syntax_ast__exprData convert_ExprData(ExprData exprData, kk_context_t* _ctx);
kk_stella_syntax_ast__pattern convert_Pattern(Pattern pattern, kk_context_t* _ctx);
kk_std_core_types__list convert_ListPattern(ListPattern listPattern, kk_context_t* _ctx);
kk_stella_syntax_ast__labelledPattern convert_LabelledPattern(LabelledPattern labelledPattern, kk_context_t* _ctx);
kk_std_core_types__list convert_ListLabelledPattern(ListLabelledPattern listLabelledPattern, kk_context_t* _ctx);
kk_stella_syntax_ast__binding convert_Binding(Binding binding, kk_context_t* _ctx);
kk_std_core_types__list convert_ListBinding(ListBinding listBinding, kk_context_t* _ctx);
kk_stella_syntax_ast__expr convert_Expr(Expr expr, kk_context_t* _ctx);
kk_std_core_types__list convert_ListExpr(ListExpr listExpr, kk_context_t* _ctx);
kk_stella_syntax_ast__patternBinding convert_PatternBinding(PatternBinding patternBinding, kk_context_t* _ctx);
kk_std_core_types__list convert_ListPatternBinding(ListPatternBinding listPatternBinding, kk_context_t* _ctx);
kk_stella_syntax_ast__labelledEffect convert_LabelledEffect(LabelledEffect labelledEffect, kk_context_t* _ctx);
kk_std_core_types__list convert_ListLabelledEffect(ListLabelledEffect listLabelledEffect, kk_context_t* _ctx);
kk_stella_syntax_ast__modality convert_Modality(Modality modality, kk_context_t* _ctx);
kk_std_core_types__list convert_ListModality(ListModality listModality, kk_context_t* _ctx);
kk_stella_syntax_ast__handler__ convert_Handler(Handler handler, kk_context_t* _ctx);
kk_std_core_types__list convert_ListHandler(ListHandler listHandler, kk_context_t* _ctx);
kk_stella_syntax_ast__variantFieldType convert_VariantFieldType(VariantFieldType variantFieldType, kk_context_t* _ctx);
kk_std_core_types__list convert_ListVariantFieldType(ListVariantFieldType listVariantFieldType, kk_context_t* _ctx);
kk_stella_syntax_ast__recordFieldType convert_RecordFieldType(RecordFieldType recordFieldType, kk_context_t* _ctx);
kk_std_core_types__list convert_ListRecordFieldType(ListRecordFieldType listRecordFieldType, kk_context_t* _ctx);
kk_stella_syntax_ast__typing convert_Typing(Typing typing, kk_context_t* _ctx);


/* ************** Convert C AST into Koka AST ************ */
kk_stella_syntax_ast__stellaIdent convert_StellaIdent(StellaIdent stellaIdent, kk_context_t* _ctx) {
  kk_string_t str = chars_to_string(stellaIdent, _ctx);
  return kk_stella_syntax_ast__new_StellaIdent(str, _ctx);
}
kk_stella_syntax_ast__extensionName convert_ExtensionName(ExtensionName extensionName, kk_context_t* _ctx) {
  kk_string_t str = chars_to_string(extensionName, _ctx);
  return kk_stella_syntax_ast__new_ExtensionName(str, _ctx);
}
kk_stella_syntax_ast__memoryAddress convert_MemoryAddress(MemoryAddress memoryAddress, kk_context_t* _ctx) {
  kk_string_t str = chars_to_string(memoryAddress, _ctx);
  return kk_stella_syntax_ast__new_MemoryAddress(str, _ctx);
}
kk_stella_syntax_ast__program convert_Program(Program program, kk_context_t* _ctx) {
  switch(program->kind) {
    case is_AProgram:
      LanguageDecl c0_1 = program->u.aProgram_.languagedecl_;
      kk_stella_syntax_ast__languageDecl k0_1 = convert_LanguageDecl(c0_1, _ctx);
      ListExtension c0_2 = program->u.aProgram_.listextension_;
      kk_std_core_types__list k0_2 = convert_ListExtension(c0_2, _ctx);
      ListDecl c0_3 = program->u.aProgram_.listdecl_;
      kk_std_core_types__list k0_3 = convert_ListDecl(c0_3, _ctx);

      return kk_stella_syntax_ast__new_AProgram(kk_reuse_null, 0, k0_1, k0_2, k0_3, _ctx);

  }

}

kk_std_core_types__list convert_ListStellaIdent(ListStellaIdent listStellaIdent, kk_context_t* _ctx) {
  if (listStellaIdent) {
    StellaIdent stellaIdent = listStellaIdent->stellaident_;
    kk_stella_syntax_ast__stellaIdent k1 = convert_StellaIdent(stellaIdent, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__stellaIdent_box(k1, _ctx);
    listStellaIdent = listStellaIdent->liststellaident_;
    kk_std_core_types__list k3 = convert_ListStellaIdent(listStellaIdent, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__languageDecl convert_LanguageDecl(LanguageDecl languageDecl, kk_context_t* _ctx) {
  switch(languageDecl->kind) {
    case is_LanguageCore:
      return kk_stella_syntax_ast__new_LanguageCore(_ctx);

  }

}

kk_stella_syntax_ast__extension convert_Extension(Extension extension, kk_context_t* _ctx) {
  switch(extension->kind) {
    case is_AnExtension:
      ListExtensionName c0_1 = extension->u.anExtension_.listextensionname_;
      kk_std_core_types__list k0_1 = convert_ListExtensionName(c0_1, _ctx);

      return kk_stella_syntax_ast__new_AnExtension(k0_1, _ctx);

  }

}

kk_std_core_types__list convert_ListExtensionName(ListExtensionName listExtensionName, kk_context_t* _ctx) {
  if (listExtensionName) {
    ExtensionName extensionName = listExtensionName->extensionname_;
    kk_stella_syntax_ast__extensionName k1 = convert_ExtensionName(extensionName, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__extensionName_box(k1, _ctx);
    listExtensionName = listExtensionName->listextensionname_;
    kk_std_core_types__list k3 = convert_ListExtensionName(listExtensionName, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_std_core_types__list convert_ListExtension(ListExtension listExtension, kk_context_t* _ctx) {
  if (listExtension) {
    Extension extension = listExtension->extension_;
    kk_stella_syntax_ast__extension k1 = convert_Extension(extension, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__extension_box(k1, _ctx);
    listExtension = listExtension->listextension_;
    kk_std_core_types__list k3 = convert_ListExtension(listExtension, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__decl convert_Decl(Decl decl, kk_context_t* _ctx) {
  switch(decl->kind) {
    case is_DeclFun:
      ListAnnotation c0_1 = decl->u.declFun_.listannotation_;
      kk_std_core_types__list k0_1 = convert_ListAnnotation(c0_1, _ctx);
      StellaIdent c0_2 = decl->u.declFun_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k0_2 = convert_StellaIdent(c0_2, _ctx);
      ListParamDecl c0_3 = decl->u.declFun_.listparamdecl_;
      kk_std_core_types__list k0_3 = convert_ListParamDecl(c0_3, _ctx);
      ReturnType c0_4 = decl->u.declFun_.returntype_;
      kk_stella_syntax_ast__returnType k0_4 = convert_ReturnType(c0_4, _ctx);
      ThrowType c0_5 = decl->u.declFun_.throwtype_;
      kk_stella_syntax_ast__throwType k0_5 = convert_ThrowType(c0_5, _ctx);
      ListDecl c0_6 = decl->u.declFun_.listdecl_;
      kk_std_core_types__list k0_6 = convert_ListDecl(c0_6, _ctx);
      Expr c0_7 = decl->u.declFun_.expr_;
      kk_stella_syntax_ast__expr k0_7 = convert_Expr(c0_7, _ctx);

      return kk_stella_syntax_ast__new_DeclFun(kk_reuse_null, 0, k0_1, k0_2, k0_3, k0_4, k0_5, k0_6, k0_7, _ctx);
    case is_DeclFunGeneric:
      ListAnnotation c1_1 = decl->u.declFunGeneric_.listannotation_;
      kk_std_core_types__list k1_1 = convert_ListAnnotation(c1_1, _ctx);
      StellaIdent c1_2 = decl->u.declFunGeneric_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k1_2 = convert_StellaIdent(c1_2, _ctx);
      ListStellaIdent c1_3 = decl->u.declFunGeneric_.liststellaident_;
      kk_std_core_types__list k1_3 = convert_ListStellaIdent(c1_3, _ctx);
      ListParamDecl c1_4 = decl->u.declFunGeneric_.listparamdecl_;
      kk_std_core_types__list k1_4 = convert_ListParamDecl(c1_4, _ctx);
      ReturnType c1_5 = decl->u.declFunGeneric_.returntype_;
      kk_stella_syntax_ast__returnType k1_5 = convert_ReturnType(c1_5, _ctx);
      ThrowType c1_6 = decl->u.declFunGeneric_.throwtype_;
      kk_stella_syntax_ast__throwType k1_6 = convert_ThrowType(c1_6, _ctx);
      ListDecl c1_7 = decl->u.declFunGeneric_.listdecl_;
      kk_std_core_types__list k1_7 = convert_ListDecl(c1_7, _ctx);
      Expr c1_8 = decl->u.declFunGeneric_.expr_;
      kk_stella_syntax_ast__expr k1_8 = convert_Expr(c1_8, _ctx);

      return kk_stella_syntax_ast__new_DeclFunGeneric(kk_reuse_null, 0, k1_1, k1_2, k1_3, k1_4, k1_5, k1_6, k1_7, k1_8, _ctx);
    case is_DeclFunMod:
      ListAnnotation c2_1 = decl->u.declFunMod_.listannotation_;
      kk_std_core_types__list k2_1 = convert_ListAnnotation(c2_1, _ctx);
      ListModality c2_2 = decl->u.declFunMod_.listmodality_;
      kk_std_core_types__list k2_2 = convert_ListModality(c2_2, _ctx);
      StellaIdent c2_3 = decl->u.declFunMod_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k2_3 = convert_StellaIdent(c2_3, _ctx);
      ListParamDecl c2_4 = decl->u.declFunMod_.listparamdecl_;
      kk_std_core_types__list k2_4 = convert_ListParamDecl(c2_4, _ctx);
      ReturnType c2_5 = decl->u.declFunMod_.returntype_;
      kk_stella_syntax_ast__returnType k2_5 = convert_ReturnType(c2_5, _ctx);
      ThrowType c2_6 = decl->u.declFunMod_.throwtype_;
      kk_stella_syntax_ast__throwType k2_6 = convert_ThrowType(c2_6, _ctx);
      ListDecl c2_7 = decl->u.declFunMod_.listdecl_;
      kk_std_core_types__list k2_7 = convert_ListDecl(c2_7, _ctx);
      Expr c2_8 = decl->u.declFunMod_.expr_;
      kk_stella_syntax_ast__expr k2_8 = convert_Expr(c2_8, _ctx);

      return kk_stella_syntax_ast__new_DeclFunMod(kk_reuse_null, 0, k2_1, k2_2, k2_3, k2_4, k2_5, k2_6, k2_7, k2_8, _ctx);
    case is_DeclTypeAlias:
      StellaIdent c3_1 = decl->u.declTypeAlias_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k3_1 = convert_StellaIdent(c3_1, _ctx);
      Type c3_2 = decl->u.declTypeAlias_.type_;
      kk_stella_syntax_ast__type__ k3_2 = convert_Type(c3_2, _ctx);

      return kk_stella_syntax_ast__new_DeclTypeAlias(kk_reuse_null, 0, k3_1, k3_2, _ctx);
    case is_DeclExceptionType:
      Type c4_1 = decl->u.declExceptionType_.type_;
      kk_stella_syntax_ast__type__ k4_1 = convert_Type(c4_1, _ctx);

      return kk_stella_syntax_ast__new_DeclExceptionType(kk_reuse_null, 0, k4_1, _ctx);
    case is_DeclExceptionVariant:
      StellaIdent c5_1 = decl->u.declExceptionVariant_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k5_1 = convert_StellaIdent(c5_1, _ctx);
      Type c5_2 = decl->u.declExceptionVariant_.type_;
      kk_stella_syntax_ast__type__ k5_2 = convert_Type(c5_2, _ctx);

      return kk_stella_syntax_ast__new_DeclExceptionVariant(kk_reuse_null, 0, k5_1, k5_2, _ctx);

  }

}

kk_std_core_types__list convert_ListDecl(ListDecl listDecl, kk_context_t* _ctx) {
  if (listDecl) {
    Decl decl = listDecl->decl_;
    kk_stella_syntax_ast__decl k1 = convert_Decl(decl, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__decl_box(k1, _ctx);
    listDecl = listDecl->listdecl_;
    kk_std_core_types__list k3 = convert_ListDecl(listDecl, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__localDecl convert_LocalDecl(LocalDecl localDecl, kk_context_t* _ctx) {
  switch(localDecl->kind) {
    case is_ALocalDecl:
      Decl c0_1 = localDecl->u.aLocalDecl_.decl_;
      kk_stella_syntax_ast__decl k0_1 = convert_Decl(c0_1, _ctx);

      return kk_stella_syntax_ast__new_ALocalDecl(k0_1, _ctx);

  }

}

kk_std_core_types__list convert_ListLocalDecl(ListLocalDecl listLocalDecl, kk_context_t* _ctx) {
  if (listLocalDecl) {
    LocalDecl localDecl = listLocalDecl->localdecl_;
    kk_stella_syntax_ast__localDecl k1 = convert_LocalDecl(localDecl, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__localDecl_box(k1, _ctx);
    listLocalDecl = listLocalDecl->listlocaldecl_;
    kk_std_core_types__list k3 = convert_ListLocalDecl(listLocalDecl, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__annotation convert_Annotation(Annotation annotation, kk_context_t* _ctx) {
  switch(annotation->kind) {
    case is_InlineAnnotation:
      return kk_stella_syntax_ast__new_InlineAnnotation(_ctx);

  }

}

kk_std_core_types__list convert_ListAnnotation(ListAnnotation listAnnotation, kk_context_t* _ctx) {
  if (listAnnotation) {
    Annotation annotation = listAnnotation->annotation_;
    kk_stella_syntax_ast__annotation k1 = convert_Annotation(annotation, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__annotation_box(k1, _ctx);
    listAnnotation = listAnnotation->listannotation_;
    kk_std_core_types__list k3 = convert_ListAnnotation(listAnnotation, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__paramDecl convert_ParamDecl(ParamDecl paramDecl, kk_context_t* _ctx) {
  switch(paramDecl->kind) {
    case is_AParamDecl:
      StellaIdent c0_1 = paramDecl->u.aParamDecl_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k0_1 = convert_StellaIdent(c0_1, _ctx);
      Type c0_2 = paramDecl->u.aParamDecl_.type_;
      kk_stella_syntax_ast__type__ k0_2 = convert_Type(c0_2, _ctx);

      return kk_stella_syntax_ast__new_AParamDecl(kk_reuse_null, 0, k0_1, k0_2, _ctx);

  }

}

kk_std_core_types__list convert_ListParamDecl(ListParamDecl listParamDecl, kk_context_t* _ctx) {
  if (listParamDecl) {
    ParamDecl paramDecl = listParamDecl->paramdecl_;
    kk_stella_syntax_ast__paramDecl k1 = convert_ParamDecl(paramDecl, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__paramDecl_box(k1, _ctx);
    listParamDecl = listParamDecl->listparamdecl_;
    kk_std_core_types__list k3 = convert_ListParamDecl(listParamDecl, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__returnType convert_ReturnType(ReturnType returnType, kk_context_t* _ctx) {
  switch(returnType->kind) {
    case is_NoReturnType:
      return kk_stella_syntax_ast__new_NoReturnType(_ctx);
    case is_SomeReturnType:
      Type c1_1 = returnType->u.someReturnType_.type_;
      kk_stella_syntax_ast__type__ k1_1 = convert_Type(c1_1, _ctx);

      return kk_stella_syntax_ast__new_SomeReturnType(kk_reuse_null, 0, k1_1, _ctx);

  }

}

kk_stella_syntax_ast__throwType convert_ThrowType(ThrowType throwType, kk_context_t* _ctx) {
  switch(throwType->kind) {
    case is_NoThrowType:
      return kk_stella_syntax_ast__new_NoThrowType(_ctx);
    case is_SomeThrowType:
      ListType c1_1 = throwType->u.someThrowType_.listtype_;
      kk_std_core_types__list k1_1 = convert_ListType(c1_1, _ctx);

      return kk_stella_syntax_ast__new_SomeThrowType(kk_reuse_null, 0, k1_1, _ctx);

  }

}

kk_stella_syntax_ast__type__ convert_Type(Type type, kk_context_t* _ctx) {
  switch(type->kind) {
    case is_TypeMod:
      Modality c0_1 = type->u.typeMod_.modality_;
      kk_stella_syntax_ast__modality k0_1 = convert_Modality(c0_1, _ctx);
      Type c0_2 = type->u.typeMod_.type_;
      kk_stella_syntax_ast__type__ k0_2 = convert_Type(c0_2, _ctx);

      return kk_stella_syntax_ast__new_TypeMod(kk_reuse_null, 0, k0_1, k0_2, _ctx);
    case is_TypeAuto:
      return kk_stella_syntax_ast__new_TypeAuto(_ctx);
    case is_TypeFun:
      ListType c2_1 = type->u.typeFun_.listtype_;
      kk_std_core_types__list k2_1 = convert_ListType(c2_1, _ctx);
      Type c2_2 = type->u.typeFun_.type_;
      kk_stella_syntax_ast__type__ k2_2 = convert_Type(c2_2, _ctx);

      return kk_stella_syntax_ast__new_TypeFun(kk_reuse_null, 0, k2_1, k2_2, _ctx);
    case is_TypeForAll:
      ListStellaIdent c3_1 = type->u.typeForAll_.liststellaident_;
      kk_std_core_types__list k3_1 = convert_ListStellaIdent(c3_1, _ctx);
      Type c3_2 = type->u.typeForAll_.type_;
      kk_stella_syntax_ast__type__ k3_2 = convert_Type(c3_2, _ctx);

      return kk_stella_syntax_ast__new_TypeForAll(kk_reuse_null, 0, k3_1, k3_2, _ctx);
    case is_TypeRec:
      StellaIdent c4_1 = type->u.typeRec_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k4_1 = convert_StellaIdent(c4_1, _ctx);
      Type c4_2 = type->u.typeRec_.type_;
      kk_stella_syntax_ast__type__ k4_2 = convert_Type(c4_2, _ctx);

      return kk_stella_syntax_ast__new_TypeRec(kk_reuse_null, 0, k4_1, k4_2, _ctx);
    case is_TypeSum:
      Type c5_1 = type->u.typeSum_.type_1;
      kk_stella_syntax_ast__type__ k5_1 = convert_Type(c5_1, _ctx);
      Type c5_2 = type->u.typeSum_.type_2;
      kk_stella_syntax_ast__type__ k5_2 = convert_Type(c5_2, _ctx);

      return kk_stella_syntax_ast__new_TypeSum(kk_reuse_null, 0, k5_1, k5_2, _ctx);
    case is_TypeTuple:
      ListType c6_1 = type->u.typeTuple_.listtype_;
      kk_std_core_types__list k6_1 = convert_ListType(c6_1, _ctx);

      return kk_stella_syntax_ast__new_TypeTuple(kk_reuse_null, 0, k6_1, _ctx);
    case is_TypeRecord:
      ListRecordFieldType c7_1 = type->u.typeRecord_.listrecordfieldtype_;
      kk_std_core_types__list k7_1 = convert_ListRecordFieldType(c7_1, _ctx);

      return kk_stella_syntax_ast__new_TypeRecord(kk_reuse_null, 0, k7_1, _ctx);
    case is_TypeVariant:
      ListVariantFieldType c8_1 = type->u.typeVariant_.listvariantfieldtype_;
      kk_std_core_types__list k8_1 = convert_ListVariantFieldType(c8_1, _ctx);

      return kk_stella_syntax_ast__new_TypeVariant(kk_reuse_null, 0, k8_1, _ctx);
    case is_TypeList:
      Type c9_1 = type->u.typeList_.type_;
      kk_stella_syntax_ast__type__ k9_1 = convert_Type(c9_1, _ctx);

      return kk_stella_syntax_ast__new_TypeList(kk_reuse_null, 0, k9_1, _ctx);
    case is_TypeBool:
      return kk_stella_syntax_ast__new_TypeBool(_ctx);
    case is_TypeNat:
      return kk_stella_syntax_ast__new_TypeNat(_ctx);
    case is_TypeUnit:
      return kk_stella_syntax_ast__new_TypeUnit(_ctx);
    case is_TypeTop:
      return kk_stella_syntax_ast__new_TypeTop(_ctx);
    case is_TypeBottom:
      return kk_stella_syntax_ast__new_TypeBottom(_ctx);
    case is_TypeRef:
      Type c15_1 = type->u.typeRef_.type_;
      kk_stella_syntax_ast__type__ k15_1 = convert_Type(c15_1, _ctx);

      return kk_stella_syntax_ast__new_TypeRef(kk_reuse_null, 0, k15_1, _ctx);
    case is_TypeVar:
      StellaIdent c16_1 = type->u.typeVar_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k16_1 = convert_StellaIdent(c16_1, _ctx);

      return kk_stella_syntax_ast__new_TypeVar(kk_reuse_null, 0, k16_1, _ctx);

  }

}

kk_std_core_types__list convert_ListType(ListType listType, kk_context_t* _ctx) {
  if (listType) {
    Type type = listType->type_;
    kk_stella_syntax_ast__type__ k1 = convert_Type(type, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__type___box(k1, _ctx);
    listType = listType->listtype_;
    kk_std_core_types__list k3 = convert_ListType(listType, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__matchCase convert_MatchCase(MatchCase matchCase, kk_context_t* _ctx) {
  switch(matchCase->kind) {
    case is_AMatchCase:
      Pattern c0_1 = matchCase->u.aMatchCase_.pattern_;
      kk_stella_syntax_ast__pattern k0_1 = convert_Pattern(c0_1, _ctx);
      Expr c0_2 = matchCase->u.aMatchCase_.expr_;
      kk_stella_syntax_ast__expr k0_2 = convert_Expr(c0_2, _ctx);

      return kk_stella_syntax_ast__new_AMatchCase(kk_reuse_null, 0, k0_1, k0_2, _ctx);

  }

}

kk_std_core_types__list convert_ListMatchCase(ListMatchCase listMatchCase, kk_context_t* _ctx) {
  if (listMatchCase) {
    MatchCase matchCase = listMatchCase->matchcase_;
    kk_stella_syntax_ast__matchCase k1 = convert_MatchCase(matchCase, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__matchCase_box(k1, _ctx);
    listMatchCase = listMatchCase->listmatchcase_;
    kk_std_core_types__list k3 = convert_ListMatchCase(listMatchCase, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__optionalTyping convert_OptionalTyping(OptionalTyping optionalTyping, kk_context_t* _ctx) {
  switch(optionalTyping->kind) {
    case is_NoTyping:
      return kk_stella_syntax_ast__new_NoTyping(_ctx);
    case is_SomeTyping:
      Type c1_1 = optionalTyping->u.someTyping_.type_;
      kk_stella_syntax_ast__type__ k1_1 = convert_Type(c1_1, _ctx);

      return kk_stella_syntax_ast__new_SomeTyping(kk_reuse_null, 0, k1_1, _ctx);

  }

}

kk_stella_syntax_ast__patternData convert_PatternData(PatternData patternData, kk_context_t* _ctx) {
  switch(patternData->kind) {
    case is_NoPatternData:
      return kk_stella_syntax_ast__new_NoPatternData(_ctx);
    case is_SomePatternData:
      Pattern c1_1 = patternData->u.somePatternData_.pattern_;
      kk_stella_syntax_ast__pattern k1_1 = convert_Pattern(c1_1, _ctx);

      return kk_stella_syntax_ast__new_SomePatternData(kk_reuse_null, 0, k1_1, _ctx);

  }

}

kk_stella_syntax_ast__exprData convert_ExprData(ExprData exprData, kk_context_t* _ctx) {
  switch(exprData->kind) {
    case is_NoExprData:
      return kk_stella_syntax_ast__new_NoExprData(_ctx);
    case is_SomeExprData:
      Expr c1_1 = exprData->u.someExprData_.expr_;
      kk_stella_syntax_ast__expr k1_1 = convert_Expr(c1_1, _ctx);

      return kk_stella_syntax_ast__new_SomeExprData(kk_reuse_null, 0, k1_1, _ctx);

  }

}

kk_stella_syntax_ast__pattern convert_Pattern(Pattern pattern, kk_context_t* _ctx) {
  switch(pattern->kind) {
    case is_PatternCastAs:
      Pattern c0_1 = pattern->u.patternCastAs_.pattern_;
      kk_stella_syntax_ast__pattern k0_1 = convert_Pattern(c0_1, _ctx);
      Type c0_2 = pattern->u.patternCastAs_.type_;
      kk_stella_syntax_ast__type__ k0_2 = convert_Type(c0_2, _ctx);

      return kk_stella_syntax_ast__new_PatternCastAs(kk_reuse_null, 0, k0_1, k0_2, _ctx);
    case is_PatternAsc:
      Pattern c1_1 = pattern->u.patternAsc_.pattern_;
      kk_stella_syntax_ast__pattern k1_1 = convert_Pattern(c1_1, _ctx);
      Type c1_2 = pattern->u.patternAsc_.type_;
      kk_stella_syntax_ast__type__ k1_2 = convert_Type(c1_2, _ctx);

      return kk_stella_syntax_ast__new_PatternAsc(kk_reuse_null, 0, k1_1, k1_2, _ctx);
    case is_PatternVariant:
      StellaIdent c2_1 = pattern->u.patternVariant_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k2_1 = convert_StellaIdent(c2_1, _ctx);
      PatternData c2_2 = pattern->u.patternVariant_.patterndata_;
      kk_stella_syntax_ast__patternData k2_2 = convert_PatternData(c2_2, _ctx);

      return kk_stella_syntax_ast__new_PatternVariant(kk_reuse_null, 0, k2_1, k2_2, _ctx);
    case is_PatternInl:
      Pattern c3_1 = pattern->u.patternInl_.pattern_;
      kk_stella_syntax_ast__pattern k3_1 = convert_Pattern(c3_1, _ctx);

      return kk_stella_syntax_ast__new_PatternInl(kk_reuse_null, 0, k3_1, _ctx);
    case is_PatternInr:
      Pattern c4_1 = pattern->u.patternInr_.pattern_;
      kk_stella_syntax_ast__pattern k4_1 = convert_Pattern(c4_1, _ctx);

      return kk_stella_syntax_ast__new_PatternInr(kk_reuse_null, 0, k4_1, _ctx);
    case is_PatternTuple:
      ListPattern c5_1 = pattern->u.patternTuple_.listpattern_;
      kk_std_core_types__list k5_1 = convert_ListPattern(c5_1, _ctx);

      return kk_stella_syntax_ast__new_PatternTuple(kk_reuse_null, 0, k5_1, _ctx);
    case is_PatternRecord:
      ListLabelledPattern c6_1 = pattern->u.patternRecord_.listlabelledpattern_;
      kk_std_core_types__list k6_1 = convert_ListLabelledPattern(c6_1, _ctx);

      return kk_stella_syntax_ast__new_PatternRecord(kk_reuse_null, 0, k6_1, _ctx);
    case is_PatternList:
      ListPattern c7_1 = pattern->u.patternList_.listpattern_;
      kk_std_core_types__list k7_1 = convert_ListPattern(c7_1, _ctx);

      return kk_stella_syntax_ast__new_PatternList(kk_reuse_null, 0, k7_1, _ctx);
    case is_PatternCons:
      Pattern c8_1 = pattern->u.patternCons_.pattern_1;
      kk_stella_syntax_ast__pattern k8_1 = convert_Pattern(c8_1, _ctx);
      Pattern c8_2 = pattern->u.patternCons_.pattern_2;
      kk_stella_syntax_ast__pattern k8_2 = convert_Pattern(c8_2, _ctx);

      return kk_stella_syntax_ast__new_PatternCons(kk_reuse_null, 0, k8_1, k8_2, _ctx);
    case is_PatternFalse:
      return kk_stella_syntax_ast__new_PatternFalse(_ctx);
    case is_PatternTrue:
      return kk_stella_syntax_ast__new_PatternTrue(_ctx);
    case is_PatternUnit:
      return kk_stella_syntax_ast__new_PatternUnit(_ctx);
    case is_PatternInt:
      Integer c12_1 = pattern->u.patternInt_.integer_;
      kk_integer_t k12_1 = convert_Integer(c12_1, _ctx);

      return kk_stella_syntax_ast__new_PatternInt(kk_reuse_null, 0, k12_1, _ctx);
    case is_PatternSucc:
      Pattern c13_1 = pattern->u.patternSucc_.pattern_;
      kk_stella_syntax_ast__pattern k13_1 = convert_Pattern(c13_1, _ctx);

      return kk_stella_syntax_ast__new_PatternSucc(kk_reuse_null, 0, k13_1, _ctx);
    case is_PatternVar:
      StellaIdent c14_1 = pattern->u.patternVar_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k14_1 = convert_StellaIdent(c14_1, _ctx);

      return kk_stella_syntax_ast__new_PatternVar(kk_reuse_null, 0, k14_1, _ctx);

  }

}

kk_std_core_types__list convert_ListPattern(ListPattern listPattern, kk_context_t* _ctx) {
  if (listPattern) {
    Pattern pattern = listPattern->pattern_;
    kk_stella_syntax_ast__pattern k1 = convert_Pattern(pattern, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__pattern_box(k1, _ctx);
    listPattern = listPattern->listpattern_;
    kk_std_core_types__list k3 = convert_ListPattern(listPattern, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__labelledPattern convert_LabelledPattern(LabelledPattern labelledPattern, kk_context_t* _ctx) {
  switch(labelledPattern->kind) {
    case is_ALabelledPattern:
      StellaIdent c0_1 = labelledPattern->u.aLabelledPattern_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k0_1 = convert_StellaIdent(c0_1, _ctx);
      Pattern c0_2 = labelledPattern->u.aLabelledPattern_.pattern_;
      kk_stella_syntax_ast__pattern k0_2 = convert_Pattern(c0_2, _ctx);

      return kk_stella_syntax_ast__new_ALabelledPattern(kk_reuse_null, 0, k0_1, k0_2, _ctx);

  }

}

kk_std_core_types__list convert_ListLabelledPattern(ListLabelledPattern listLabelledPattern, kk_context_t* _ctx) {
  if (listLabelledPattern) {
    LabelledPattern labelledPattern = listLabelledPattern->labelledpattern_;
    kk_stella_syntax_ast__labelledPattern k1 = convert_LabelledPattern(labelledPattern, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__labelledPattern_box(k1, _ctx);
    listLabelledPattern = listLabelledPattern->listlabelledpattern_;
    kk_std_core_types__list k3 = convert_ListLabelledPattern(listLabelledPattern, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__binding convert_Binding(Binding binding, kk_context_t* _ctx) {
  switch(binding->kind) {
    case is_ABinding:
      StellaIdent c0_1 = binding->u.aBinding_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k0_1 = convert_StellaIdent(c0_1, _ctx);
      Expr c0_2 = binding->u.aBinding_.expr_;
      kk_stella_syntax_ast__expr k0_2 = convert_Expr(c0_2, _ctx);

      return kk_stella_syntax_ast__new_ABinding(kk_reuse_null, 0, k0_1, k0_2, _ctx);

  }

}

kk_std_core_types__list convert_ListBinding(ListBinding listBinding, kk_context_t* _ctx) {
  if (listBinding) {
    Binding binding = listBinding->binding_;
    kk_stella_syntax_ast__binding k1 = convert_Binding(binding, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__binding_box(k1, _ctx);
    listBinding = listBinding->listbinding_;
    kk_std_core_types__list k3 = convert_ListBinding(listBinding, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__expr convert_Expr(Expr expr, kk_context_t* _ctx) {
  switch(expr->kind) {
    case is_Sequence:
      Expr c0_1 = expr->u.sequence_.expr_1;
      kk_stella_syntax_ast__expr k0_1 = convert_Expr(c0_1, _ctx);
      Expr c0_2 = expr->u.sequence_.expr_2;
      kk_stella_syntax_ast__expr k0_2 = convert_Expr(c0_2, _ctx);

      return kk_stella_syntax_ast__new_Sequence(kk_reuse_null, 0, k0_1, k0_2, _ctx);
    case is_Assign:
      Expr c1_1 = expr->u.assign_.expr_1;
      kk_stella_syntax_ast__expr k1_1 = convert_Expr(c1_1, _ctx);
      Expr c1_2 = expr->u.assign_.expr_2;
      kk_stella_syntax_ast__expr k1_2 = convert_Expr(c1_2, _ctx);

      return kk_stella_syntax_ast__new_Assign(kk_reuse_null, 0, k1_1, k1_2, _ctx);
    case is_If:
      Expr c2_1 = expr->u.if_.expr_1;
      kk_stella_syntax_ast__expr k2_1 = convert_Expr(c2_1, _ctx);
      Expr c2_2 = expr->u.if_.expr_2;
      kk_stella_syntax_ast__expr k2_2 = convert_Expr(c2_2, _ctx);
      Expr c2_3 = expr->u.if_.expr_3;
      kk_stella_syntax_ast__expr k2_3 = convert_Expr(c2_3, _ctx);

      return kk_stella_syntax_ast__new_If(kk_reuse_null, 0, k2_1, k2_2, k2_3, _ctx);
    case is_Let:
      ListPatternBinding c3_1 = expr->u.let_.listpatternbinding_;
      kk_std_core_types__list k3_1 = convert_ListPatternBinding(c3_1, _ctx);
      Expr c3_2 = expr->u.let_.expr_;
      kk_stella_syntax_ast__expr k3_2 = convert_Expr(c3_2, _ctx);

      return kk_stella_syntax_ast__new_Let(kk_reuse_null, 0, k3_1, k3_2, _ctx);
    case is_LetRec:
      ListPatternBinding c4_1 = expr->u.letRec_.listpatternbinding_;
      kk_std_core_types__list k4_1 = convert_ListPatternBinding(c4_1, _ctx);
      Expr c4_2 = expr->u.letRec_.expr_;
      kk_stella_syntax_ast__expr k4_2 = convert_Expr(c4_2, _ctx);

      return kk_stella_syntax_ast__new_LetRec(kk_reuse_null, 0, k4_1, k4_2, _ctx);
    case is_ModLet:
      Modality c5_1 = expr->u.modLet_.modality_1;
      kk_stella_syntax_ast__modality k5_1 = convert_Modality(c5_1, _ctx);
      Modality c5_2 = expr->u.modLet_.modality_2;
      kk_stella_syntax_ast__modality k5_2 = convert_Modality(c5_2, _ctx);
      ListPatternBinding c5_3 = expr->u.modLet_.listpatternbinding_;
      kk_std_core_types__list k5_3 = convert_ListPatternBinding(c5_3, _ctx);
      Expr c5_4 = expr->u.modLet_.expr_;
      kk_stella_syntax_ast__expr k5_4 = convert_Expr(c5_4, _ctx);

      return kk_stella_syntax_ast__new_ModLet(kk_reuse_null, 0, k5_1, k5_2, k5_3, k5_4, _ctx);
    case is_TypeAbstraction:
      ListStellaIdent c6_1 = expr->u.typeAbstraction_.liststellaident_;
      kk_std_core_types__list k6_1 = convert_ListStellaIdent(c6_1, _ctx);
      Expr c6_2 = expr->u.typeAbstraction_.expr_;
      kk_stella_syntax_ast__expr k6_2 = convert_Expr(c6_2, _ctx);

      return kk_stella_syntax_ast__new_TypeAbstraction(kk_reuse_null, 0, k6_1, k6_2, _ctx);
    case is_LessThan:
      Expr c7_1 = expr->u.lessThan_.expr_1;
      kk_stella_syntax_ast__expr k7_1 = convert_Expr(c7_1, _ctx);
      Expr c7_2 = expr->u.lessThan_.expr_2;
      kk_stella_syntax_ast__expr k7_2 = convert_Expr(c7_2, _ctx);

      return kk_stella_syntax_ast__new_LessThan(kk_reuse_null, 0, k7_1, k7_2, _ctx);
    case is_LessThanOrEqual:
      Expr c8_1 = expr->u.lessThanOrEqual_.expr_1;
      kk_stella_syntax_ast__expr k8_1 = convert_Expr(c8_1, _ctx);
      Expr c8_2 = expr->u.lessThanOrEqual_.expr_2;
      kk_stella_syntax_ast__expr k8_2 = convert_Expr(c8_2, _ctx);

      return kk_stella_syntax_ast__new_LessThanOrEqual(kk_reuse_null, 0, k8_1, k8_2, _ctx);
    case is_GreaterThan:
      Expr c9_1 = expr->u.greaterThan_.expr_1;
      kk_stella_syntax_ast__expr k9_1 = convert_Expr(c9_1, _ctx);
      Expr c9_2 = expr->u.greaterThan_.expr_2;
      kk_stella_syntax_ast__expr k9_2 = convert_Expr(c9_2, _ctx);

      return kk_stella_syntax_ast__new_GreaterThan(kk_reuse_null, 0, k9_1, k9_2, _ctx);
    case is_GreaterThanOrEqual:
      Expr c10_1 = expr->u.greaterThanOrEqual_.expr_1;
      kk_stella_syntax_ast__expr k10_1 = convert_Expr(c10_1, _ctx);
      Expr c10_2 = expr->u.greaterThanOrEqual_.expr_2;
      kk_stella_syntax_ast__expr k10_2 = convert_Expr(c10_2, _ctx);

      return kk_stella_syntax_ast__new_GreaterThanOrEqual(kk_reuse_null, 0, k10_1, k10_2, _ctx);
    case is_Equal:
      Expr c11_1 = expr->u.equal_.expr_1;
      kk_stella_syntax_ast__expr k11_1 = convert_Expr(c11_1, _ctx);
      Expr c11_2 = expr->u.equal_.expr_2;
      kk_stella_syntax_ast__expr k11_2 = convert_Expr(c11_2, _ctx);

      return kk_stella_syntax_ast__new_Equal(kk_reuse_null, 0, k11_1, k11_2, _ctx);
    case is_NotEqual:
      Expr c12_1 = expr->u.notEqual_.expr_1;
      kk_stella_syntax_ast__expr k12_1 = convert_Expr(c12_1, _ctx);
      Expr c12_2 = expr->u.notEqual_.expr_2;
      kk_stella_syntax_ast__expr k12_2 = convert_Expr(c12_2, _ctx);

      return kk_stella_syntax_ast__new_NotEqual(kk_reuse_null, 0, k12_1, k12_2, _ctx);
    case is_TypeAsc:
      Expr c13_1 = expr->u.typeAsc_.expr_;
      kk_stella_syntax_ast__expr k13_1 = convert_Expr(c13_1, _ctx);
      Type c13_2 = expr->u.typeAsc_.type_;
      kk_stella_syntax_ast__type__ k13_2 = convert_Type(c13_2, _ctx);

      return kk_stella_syntax_ast__new_TypeAsc(kk_reuse_null, 0, k13_1, k13_2, _ctx);
    case is_TypeCast:
      Expr c14_1 = expr->u.typeCast_.expr_;
      kk_stella_syntax_ast__expr k14_1 = convert_Expr(c14_1, _ctx);
      Type c14_2 = expr->u.typeCast_.type_;
      kk_stella_syntax_ast__type__ k14_2 = convert_Type(c14_2, _ctx);

      return kk_stella_syntax_ast__new_TypeCast(kk_reuse_null, 0, k14_1, k14_2, _ctx);
    case is_Abstraction:
      ListParamDecl c15_1 = expr->u.abstraction_.listparamdecl_;
      kk_std_core_types__list k15_1 = convert_ListParamDecl(c15_1, _ctx);
      Expr c15_2 = expr->u.abstraction_.expr_;
      kk_stella_syntax_ast__expr k15_2 = convert_Expr(c15_2, _ctx);

      return kk_stella_syntax_ast__new_Abstraction(kk_reuse_null, 0, k15_1, k15_2, _ctx);
    case is_ModBox:
      Modality c16_1 = expr->u.modBox_.modality_;
      kk_stella_syntax_ast__modality k16_1 = convert_Modality(c16_1, _ctx);
      Expr c16_2 = expr->u.modBox_.expr_;
      kk_stella_syntax_ast__expr k16_2 = convert_Expr(c16_2, _ctx);

      return kk_stella_syntax_ast__new_ModBox(kk_reuse_null, 0, k16_1, k16_2, _ctx);
    case is_Variant:
      StellaIdent c17_1 = expr->u.variant_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k17_1 = convert_StellaIdent(c17_1, _ctx);
      ExprData c17_2 = expr->u.variant_.exprdata_;
      kk_stella_syntax_ast__exprData k17_2 = convert_ExprData(c17_2, _ctx);

      return kk_stella_syntax_ast__new_Variant(kk_reuse_null, 0, k17_1, k17_2, _ctx);
    case is_Match:
      Expr c18_1 = expr->u.match_.expr_;
      kk_stella_syntax_ast__expr k18_1 = convert_Expr(c18_1, _ctx);
      ListMatchCase c18_2 = expr->u.match_.listmatchcase_;
      kk_std_core_types__list k18_2 = convert_ListMatchCase(c18_2, _ctx);

      return kk_stella_syntax_ast__new_Match(kk_reuse_null, 0, k18_1, k18_2, _ctx);
    case is_List:
      ListExpr c19_1 = expr->u.list_.listexpr_;
      kk_std_core_types__list k19_1 = convert_ListExpr(c19_1, _ctx);

      return kk_stella_syntax_ast__new_List(kk_reuse_null, 0, k19_1, _ctx);
    case is_Add:
      Expr c20_1 = expr->u.add_.expr_1;
      kk_stella_syntax_ast__expr k20_1 = convert_Expr(c20_1, _ctx);
      Expr c20_2 = expr->u.add_.expr_2;
      kk_stella_syntax_ast__expr k20_2 = convert_Expr(c20_2, _ctx);

      return kk_stella_syntax_ast__new_Add(kk_reuse_null, 0, k20_1, k20_2, _ctx);
    case is_Subtract:
      Expr c21_1 = expr->u.subtract_.expr_1;
      kk_stella_syntax_ast__expr k21_1 = convert_Expr(c21_1, _ctx);
      Expr c21_2 = expr->u.subtract_.expr_2;
      kk_stella_syntax_ast__expr k21_2 = convert_Expr(c21_2, _ctx);

      return kk_stella_syntax_ast__new_Subtract(kk_reuse_null, 0, k21_1, k21_2, _ctx);
    case is_LogicOr:
      Expr c22_1 = expr->u.logicOr_.expr_1;
      kk_stella_syntax_ast__expr k22_1 = convert_Expr(c22_1, _ctx);
      Expr c22_2 = expr->u.logicOr_.expr_2;
      kk_stella_syntax_ast__expr k22_2 = convert_Expr(c22_2, _ctx);

      return kk_stella_syntax_ast__new_LogicOr(kk_reuse_null, 0, k22_1, k22_2, _ctx);
    case is_Multiply:
      Expr c23_1 = expr->u.multiply_.expr_1;
      kk_stella_syntax_ast__expr k23_1 = convert_Expr(c23_1, _ctx);
      Expr c23_2 = expr->u.multiply_.expr_2;
      kk_stella_syntax_ast__expr k23_2 = convert_Expr(c23_2, _ctx);

      return kk_stella_syntax_ast__new_Multiply(kk_reuse_null, 0, k23_1, k23_2, _ctx);
    case is_Divide:
      Expr c24_1 = expr->u.divide_.expr_1;
      kk_stella_syntax_ast__expr k24_1 = convert_Expr(c24_1, _ctx);
      Expr c24_2 = expr->u.divide_.expr_2;
      kk_stella_syntax_ast__expr k24_2 = convert_Expr(c24_2, _ctx);

      return kk_stella_syntax_ast__new_Divide(kk_reuse_null, 0, k24_1, k24_2, _ctx);
    case is_LogicAnd:
      Expr c25_1 = expr->u.logicAnd_.expr_1;
      kk_stella_syntax_ast__expr k25_1 = convert_Expr(c25_1, _ctx);
      Expr c25_2 = expr->u.logicAnd_.expr_2;
      kk_stella_syntax_ast__expr k25_2 = convert_Expr(c25_2, _ctx);

      return kk_stella_syntax_ast__new_LogicAnd(kk_reuse_null, 0, k25_1, k25_2, _ctx);
    case is_Ref:
      Expr c26_1 = expr->u.ref_.expr_;
      kk_stella_syntax_ast__expr k26_1 = convert_Expr(c26_1, _ctx);

      return kk_stella_syntax_ast__new_Ref(kk_reuse_null, 0, k26_1, _ctx);
    case is_Deref:
      Expr c27_1 = expr->u.deref_.expr_;
      kk_stella_syntax_ast__expr k27_1 = convert_Expr(c27_1, _ctx);

      return kk_stella_syntax_ast__new_Deref(kk_reuse_null, 0, k27_1, _ctx);
    case is_Application:
      Expr c28_1 = expr->u.application_.expr_;
      kk_stella_syntax_ast__expr k28_1 = convert_Expr(c28_1, _ctx);
      ListExpr c28_2 = expr->u.application_.listexpr_;
      kk_std_core_types__list k28_2 = convert_ListExpr(c28_2, _ctx);

      return kk_stella_syntax_ast__new_Application(kk_reuse_null, 0, k28_1, k28_2, _ctx);
    case is_TypeApplication:
      Expr c29_1 = expr->u.typeApplication_.expr_;
      kk_stella_syntax_ast__expr k29_1 = convert_Expr(c29_1, _ctx);
      ListType c29_2 = expr->u.typeApplication_.listtype_;
      kk_std_core_types__list k29_2 = convert_ListType(c29_2, _ctx);

      return kk_stella_syntax_ast__new_TypeApplication(kk_reuse_null, 0, k29_1, k29_2, _ctx);
    case is_DotRecord:
      Expr c30_1 = expr->u.dotRecord_.expr_;
      kk_stella_syntax_ast__expr k30_1 = convert_Expr(c30_1, _ctx);
      StellaIdent c30_2 = expr->u.dotRecord_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k30_2 = convert_StellaIdent(c30_2, _ctx);

      return kk_stella_syntax_ast__new_DotRecord(kk_reuse_null, 0, k30_1, k30_2, _ctx);
    case is_DotTuple:
      Expr c31_1 = expr->u.dotTuple_.expr_;
      kk_stella_syntax_ast__expr k31_1 = convert_Expr(c31_1, _ctx);
      Integer c31_2 = expr->u.dotTuple_.integer_;
      kk_integer_t k31_2 = convert_Integer(c31_2, _ctx);

      return kk_stella_syntax_ast__new_DotTuple(kk_reuse_null, 0, k31_1, k31_2, _ctx);
    case is_Tuple:
      ListExpr c32_1 = expr->u.tuple_.listexpr_;
      kk_std_core_types__list k32_1 = convert_ListExpr(c32_1, _ctx);

      return kk_stella_syntax_ast__new_Tuple(kk_reuse_null, 0, k32_1, _ctx);
    case is_Record:
      ListBinding c33_1 = expr->u.record_.listbinding_;
      kk_std_core_types__list k33_1 = convert_ListBinding(c33_1, _ctx);

      return kk_stella_syntax_ast__new_Record(kk_reuse_null, 0, k33_1, _ctx);
    case is_ConsList:
      Expr c34_1 = expr->u.consList_.expr_1;
      kk_stella_syntax_ast__expr k34_1 = convert_Expr(c34_1, _ctx);
      Expr c34_2 = expr->u.consList_.expr_2;
      kk_stella_syntax_ast__expr k34_2 = convert_Expr(c34_2, _ctx);

      return kk_stella_syntax_ast__new_ConsList(kk_reuse_null, 0, k34_1, k34_2, _ctx);
    case is_Head:
      Expr c35_1 = expr->u.head_.expr_;
      kk_stella_syntax_ast__expr k35_1 = convert_Expr(c35_1, _ctx);

      return kk_stella_syntax_ast__new_Head(kk_reuse_null, 0, k35_1, _ctx);
    case is_IsEmpty:
      Expr c36_1 = expr->u.isEmpty_.expr_;
      kk_stella_syntax_ast__expr k36_1 = convert_Expr(c36_1, _ctx);

      return kk_stella_syntax_ast__new_IsEmpty(kk_reuse_null, 0, k36_1, _ctx);
    case is_Tail:
      Expr c37_1 = expr->u.tail_.expr_;
      kk_stella_syntax_ast__expr k37_1 = convert_Expr(c37_1, _ctx);

      return kk_stella_syntax_ast__new_Tail(kk_reuse_null, 0, k37_1, _ctx);
    case is_Panic:
      return kk_stella_syntax_ast__new_Panic(_ctx);
    case is_Throw:
      Expr c39_1 = expr->u.throw_.expr_;
      kk_stella_syntax_ast__expr k39_1 = convert_Expr(c39_1, _ctx);

      return kk_stella_syntax_ast__new_Throw(kk_reuse_null, 0, k39_1, _ctx);
    case is_TryCatch:
      Expr c40_1 = expr->u.tryCatch_.expr_1;
      kk_stella_syntax_ast__expr k40_1 = convert_Expr(c40_1, _ctx);
      Pattern c40_2 = expr->u.tryCatch_.pattern_;
      kk_stella_syntax_ast__pattern k40_2 = convert_Pattern(c40_2, _ctx);
      Expr c40_3 = expr->u.tryCatch_.expr_2;
      kk_stella_syntax_ast__expr k40_3 = convert_Expr(c40_3, _ctx);

      return kk_stella_syntax_ast__new_TryCatch(kk_reuse_null, 0, k40_1, k40_2, k40_3, _ctx);
    case is_TryWith:
      Expr c41_1 = expr->u.tryWith_.expr_1;
      kk_stella_syntax_ast__expr k41_1 = convert_Expr(c41_1, _ctx);
      Expr c41_2 = expr->u.tryWith_.expr_2;
      kk_stella_syntax_ast__expr k41_2 = convert_Expr(c41_2, _ctx);

      return kk_stella_syntax_ast__new_TryWith(kk_reuse_null, 0, k41_1, k41_2, _ctx);
    case is_TryCastAs:
      Expr c42_1 = expr->u.tryCastAs_.expr_1;
      kk_stella_syntax_ast__expr k42_1 = convert_Expr(c42_1, _ctx);
      Type c42_2 = expr->u.tryCastAs_.type_;
      kk_stella_syntax_ast__type__ k42_2 = convert_Type(c42_2, _ctx);
      Pattern c42_3 = expr->u.tryCastAs_.pattern_;
      kk_stella_syntax_ast__pattern k42_3 = convert_Pattern(c42_3, _ctx);
      Expr c42_4 = expr->u.tryCastAs_.expr_2;
      kk_stella_syntax_ast__expr k42_4 = convert_Expr(c42_4, _ctx);
      Expr c42_5 = expr->u.tryCastAs_.expr_3;
      kk_stella_syntax_ast__expr k42_5 = convert_Expr(c42_5, _ctx);

      return kk_stella_syntax_ast__new_TryCastAs(kk_reuse_null, 0, k42_1, k42_2, k42_3, k42_4, k42_5, _ctx);
    case is_Inl:
      Expr c43_1 = expr->u.inl_.expr_;
      kk_stella_syntax_ast__expr k43_1 = convert_Expr(c43_1, _ctx);

      return kk_stella_syntax_ast__new_Inl(kk_reuse_null, 0, k43_1, _ctx);
    case is_Inr:
      Expr c44_1 = expr->u.inr_.expr_;
      kk_stella_syntax_ast__expr k44_1 = convert_Expr(c44_1, _ctx);

      return kk_stella_syntax_ast__new_Inr(kk_reuse_null, 0, k44_1, _ctx);
    case is_Succ:
      Expr c45_1 = expr->u.succ_.expr_;
      kk_stella_syntax_ast__expr k45_1 = convert_Expr(c45_1, _ctx);

      return kk_stella_syntax_ast__new_Succ(kk_reuse_null, 0, k45_1, _ctx);
    case is_LogicNot:
      Expr c46_1 = expr->u.logicNot_.expr_;
      kk_stella_syntax_ast__expr k46_1 = convert_Expr(c46_1, _ctx);

      return kk_stella_syntax_ast__new_LogicNot(kk_reuse_null, 0, k46_1, _ctx);
    case is_Pred:
      Expr c47_1 = expr->u.pred_.expr_;
      kk_stella_syntax_ast__expr k47_1 = convert_Expr(c47_1, _ctx);

      return kk_stella_syntax_ast__new_Pred(kk_reuse_null, 0, k47_1, _ctx);
    case is_IsZero:
      Expr c48_1 = expr->u.isZero_.expr_;
      kk_stella_syntax_ast__expr k48_1 = convert_Expr(c48_1, _ctx);

      return kk_stella_syntax_ast__new_IsZero(kk_reuse_null, 0, k48_1, _ctx);
    case is_ModDo:
      StellaIdent c49_1 = expr->u.modDo_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k49_1 = convert_StellaIdent(c49_1, _ctx);
      Expr c49_2 = expr->u.modDo_.expr_;
      kk_stella_syntax_ast__expr k49_2 = convert_Expr(c49_2, _ctx);

      return kk_stella_syntax_ast__new_ModDo(kk_reuse_null, 0, k49_1, k49_2, _ctx);
    case is_ModHandle:
      Expr c50_1 = expr->u.modHandle_.expr_;
      kk_stella_syntax_ast__expr k50_1 = convert_Expr(c50_1, _ctx);
      ListHandler c50_2 = expr->u.modHandle_.listhandler_;
      kk_std_core_types__list k50_2 = convert_ListHandler(c50_2, _ctx);

      return kk_stella_syntax_ast__new_ModHandle(kk_reuse_null, 0, k50_1, k50_2, _ctx);
    case is_Fix:
      Expr c51_1 = expr->u.fix_.expr_;
      kk_stella_syntax_ast__expr k51_1 = convert_Expr(c51_1, _ctx);

      return kk_stella_syntax_ast__new_Fix(kk_reuse_null, 0, k51_1, _ctx);
    case is_NatRec:
      Expr c52_1 = expr->u.natRec_.expr_1;
      kk_stella_syntax_ast__expr k52_1 = convert_Expr(c52_1, _ctx);
      Expr c52_2 = expr->u.natRec_.expr_2;
      kk_stella_syntax_ast__expr k52_2 = convert_Expr(c52_2, _ctx);
      Expr c52_3 = expr->u.natRec_.expr_3;
      kk_stella_syntax_ast__expr k52_3 = convert_Expr(c52_3, _ctx);

      return kk_stella_syntax_ast__new_NatRec(kk_reuse_null, 0, k52_1, k52_2, k52_3, _ctx);
    case is_Fold:
      Type c53_1 = expr->u.fold_.type_;
      kk_stella_syntax_ast__type__ k53_1 = convert_Type(c53_1, _ctx);
      Expr c53_2 = expr->u.fold_.expr_;
      kk_stella_syntax_ast__expr k53_2 = convert_Expr(c53_2, _ctx);

      return kk_stella_syntax_ast__new_Fold(kk_reuse_null, 0, k53_1, k53_2, _ctx);
    case is_Unfold:
      Type c54_1 = expr->u.unfold_.type_;
      kk_stella_syntax_ast__type__ k54_1 = convert_Type(c54_1, _ctx);
      Expr c54_2 = expr->u.unfold_.expr_;
      kk_stella_syntax_ast__expr k54_2 = convert_Expr(c54_2, _ctx);

      return kk_stella_syntax_ast__new_Unfold(kk_reuse_null, 0, k54_1, k54_2, _ctx);
    case is_ConstTrue:
      return kk_stella_syntax_ast__new_ConstTrue(_ctx);
    case is_ConstFalse:
      return kk_stella_syntax_ast__new_ConstFalse(_ctx);
    case is_ConstUnit:
      return kk_stella_syntax_ast__new_ConstUnit(_ctx);
    case is_ConstInt:
      Integer c58_1 = expr->u.constInt_.integer_;
      kk_integer_t k58_1 = convert_Integer(c58_1, _ctx);

      return kk_stella_syntax_ast__new_ConstInt(kk_reuse_null, 0, k58_1, _ctx);
    case is_ConstMemory:
      MemoryAddress c59_1 = expr->u.constMemory_.memoryaddress_;
      kk_stella_syntax_ast__memoryAddress k59_1 = convert_MemoryAddress(c59_1, _ctx);

      return kk_stella_syntax_ast__new_ConstMemory(kk_reuse_null, 0, k59_1, _ctx);
    case is_Var:
      StellaIdent c60_1 = expr->u.var_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k60_1 = convert_StellaIdent(c60_1, _ctx);

      return kk_stella_syntax_ast__new_Var(kk_reuse_null, 0, k60_1, _ctx);

  }

}

kk_std_core_types__list convert_ListExpr(ListExpr listExpr, kk_context_t* _ctx) {
  if (listExpr) {
    Expr expr = listExpr->expr_;
    kk_stella_syntax_ast__expr k1 = convert_Expr(expr, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__expr_box(k1, _ctx);
    listExpr = listExpr->listexpr_;
    kk_std_core_types__list k3 = convert_ListExpr(listExpr, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__patternBinding convert_PatternBinding(PatternBinding patternBinding, kk_context_t* _ctx) {
  switch(patternBinding->kind) {
    case is_APatternBinding:
      Pattern c0_1 = patternBinding->u.aPatternBinding_.pattern_;
      kk_stella_syntax_ast__pattern k0_1 = convert_Pattern(c0_1, _ctx);
      Expr c0_2 = patternBinding->u.aPatternBinding_.expr_;
      kk_stella_syntax_ast__expr k0_2 = convert_Expr(c0_2, _ctx);

      return kk_stella_syntax_ast__new_APatternBinding(kk_reuse_null, 0, k0_1, k0_2, _ctx);

  }

}

kk_std_core_types__list convert_ListPatternBinding(ListPatternBinding listPatternBinding, kk_context_t* _ctx) {
  if (listPatternBinding) {
    PatternBinding patternBinding = listPatternBinding->patternbinding_;
    kk_stella_syntax_ast__patternBinding k1 = convert_PatternBinding(patternBinding, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__patternBinding_box(k1, _ctx);
    listPatternBinding = listPatternBinding->listpatternbinding_;
    kk_std_core_types__list k3 = convert_ListPatternBinding(listPatternBinding, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__labelledEffect convert_LabelledEffect(LabelledEffect labelledEffect, kk_context_t* _ctx) {
  switch(labelledEffect->kind) {
    case is_ALabelledEffect:
      StellaIdent c0_1 = labelledEffect->u.aLabelledEffect_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k0_1 = convert_StellaIdent(c0_1, _ctx);
      Type c0_2 = labelledEffect->u.aLabelledEffect_.type_;
      kk_stella_syntax_ast__type__ k0_2 = convert_Type(c0_2, _ctx);

      return kk_stella_syntax_ast__new_ALabelledEffect(kk_reuse_null, 0, k0_1, k0_2, _ctx);

  }

}

kk_std_core_types__list convert_ListLabelledEffect(ListLabelledEffect listLabelledEffect, kk_context_t* _ctx) {
  if (listLabelledEffect) {
    LabelledEffect labelledEffect = listLabelledEffect->labelledeffect_;
    kk_stella_syntax_ast__labelledEffect k1 = convert_LabelledEffect(labelledEffect, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__labelledEffect_box(k1, _ctx);
    listLabelledEffect = listLabelledEffect->listlabelledeffect_;
    kk_std_core_types__list k3 = convert_ListLabelledEffect(listLabelledEffect, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__modality convert_Modality(Modality modality, kk_context_t* _ctx) {
  switch(modality->kind) {
    case is_ModalityLock:
      return kk_stella_syntax_ast__new_ModalityLock(_ctx);
    case is_ModalityAbs:
      ListLabelledEffect c1_1 = modality->u.modalityAbs_.listlabelledeffect_;
      kk_std_core_types__list k1_1 = convert_ListLabelledEffect(c1_1, _ctx);

      return kk_stella_syntax_ast__new_ModalityAbs(kk_reuse_null, 0, k1_1, _ctx);
    case is_ModalityRel:
      ListStellaIdent c2_1 = modality->u.modalityRel_.liststellaident_;
      kk_std_core_types__list k2_1 = convert_ListStellaIdent(c2_1, _ctx);
      ListLabelledEffect c2_2 = modality->u.modalityRel_.listlabelledeffect_;
      kk_std_core_types__list k2_2 = convert_ListLabelledEffect(c2_2, _ctx);

      return kk_stella_syntax_ast__new_ModalityRel(kk_reuse_null, 0, k2_1, k2_2, _ctx);

  }

}

kk_std_core_types__list convert_ListModality(ListModality listModality, kk_context_t* _ctx) {
  if (listModality) {
    Modality modality = listModality->modality_;
    kk_stella_syntax_ast__modality k1 = convert_Modality(modality, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__modality_box(k1, _ctx);
    listModality = listModality->listmodality_;
    kk_std_core_types__list k3 = convert_ListModality(listModality, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__handler__ convert_Handler(Handler handler, kk_context_t* _ctx) {
  switch(handler->kind) {
    case is_HandlerReturn:
      Pattern c0_1 = handler->u.handlerReturn_.pattern_;
      kk_stella_syntax_ast__pattern k0_1 = convert_Pattern(c0_1, _ctx);
      Expr c0_2 = handler->u.handlerReturn_.expr_;
      kk_stella_syntax_ast__expr k0_2 = convert_Expr(c0_2, _ctx);

      return kk_stella_syntax_ast__new_HandlerReturn(kk_reuse_null, 0, k0_1, k0_2, _ctx);
    case is_HandlerLabel:
      LabelledEffect c1_1 = handler->u.handlerLabel_.labelledeffect_;
      kk_stella_syntax_ast__labelledEffect k1_1 = convert_LabelledEffect(c1_1, _ctx);
      Pattern c1_2 = handler->u.handlerLabel_.pattern_;
      kk_stella_syntax_ast__pattern k1_2 = convert_Pattern(c1_2, _ctx);
      StellaIdent c1_3 = handler->u.handlerLabel_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k1_3 = convert_StellaIdent(c1_3, _ctx);
      Expr c1_4 = handler->u.handlerLabel_.expr_;
      kk_stella_syntax_ast__expr k1_4 = convert_Expr(c1_4, _ctx);

      return kk_stella_syntax_ast__new_HandlerLabel(kk_reuse_null, 0, k1_1, k1_2, k1_3, k1_4, _ctx);

  }

}

kk_std_core_types__list convert_ListHandler(ListHandler listHandler, kk_context_t* _ctx) {
  if (listHandler) {
    Handler handler = listHandler->handler_;
    kk_stella_syntax_ast__handler__ k1 = convert_Handler(handler, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__handler___box(k1, _ctx);
    listHandler = listHandler->listhandler_;
    kk_std_core_types__list k3 = convert_ListHandler(listHandler, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__variantFieldType convert_VariantFieldType(VariantFieldType variantFieldType, kk_context_t* _ctx) {
  switch(variantFieldType->kind) {
    case is_AVariantFieldType:
      StellaIdent c0_1 = variantFieldType->u.aVariantFieldType_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k0_1 = convert_StellaIdent(c0_1, _ctx);
      OptionalTyping c0_2 = variantFieldType->u.aVariantFieldType_.optionaltyping_;
      kk_stella_syntax_ast__optionalTyping k0_2 = convert_OptionalTyping(c0_2, _ctx);

      return kk_stella_syntax_ast__new_AVariantFieldType(kk_reuse_null, 0, k0_1, k0_2, _ctx);

  }

}

kk_std_core_types__list convert_ListVariantFieldType(ListVariantFieldType listVariantFieldType, kk_context_t* _ctx) {
  if (listVariantFieldType) {
    VariantFieldType variantFieldType = listVariantFieldType->variantfieldtype_;
    kk_stella_syntax_ast__variantFieldType k1 = convert_VariantFieldType(variantFieldType, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__variantFieldType_box(k1, _ctx);
    listVariantFieldType = listVariantFieldType->listvariantfieldtype_;
    kk_std_core_types__list k3 = convert_ListVariantFieldType(listVariantFieldType, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__recordFieldType convert_RecordFieldType(RecordFieldType recordFieldType, kk_context_t* _ctx) {
  switch(recordFieldType->kind) {
    case is_ARecordFieldType:
      StellaIdent c0_1 = recordFieldType->u.aRecordFieldType_.stellaident_;
      kk_stella_syntax_ast__stellaIdent k0_1 = convert_StellaIdent(c0_1, _ctx);
      Type c0_2 = recordFieldType->u.aRecordFieldType_.type_;
      kk_stella_syntax_ast__type__ k0_2 = convert_Type(c0_2, _ctx);

      return kk_stella_syntax_ast__new_ARecordFieldType(kk_reuse_null, 0, k0_1, k0_2, _ctx);

  }

}

kk_std_core_types__list convert_ListRecordFieldType(ListRecordFieldType listRecordFieldType, kk_context_t* _ctx) {
  if (listRecordFieldType) {
    RecordFieldType recordFieldType = listRecordFieldType->recordfieldtype_;
    kk_stella_syntax_ast__recordFieldType k1 = convert_RecordFieldType(recordFieldType, _ctx);
    kk_box_t k2 = kk_stella_syntax_ast__recordFieldType_box(k1, _ctx);
    listRecordFieldType = listRecordFieldType->listrecordfieldtype_;
    kk_std_core_types__list k3 = convert_ListRecordFieldType(listRecordFieldType, _ctx);
    return kk_std_core_types__new_Cons(kk_reuse_null, 0, k2, k3, _ctx);
  }
  else {
    return kk_std_core_types__new_Nil(_ctx);
  }
}

kk_stella_syntax_ast__typing convert_Typing(Typing typing, kk_context_t* _ctx) {
  switch(typing->kind) {
    case is_ATyping:
      Expr c0_1 = typing->u.aTyping_.expr_;
      kk_stella_syntax_ast__expr k0_1 = convert_Expr(c0_1, _ctx);
      Type c0_2 = typing->u.aTyping_.type_;
      kk_stella_syntax_ast__type__ k0_2 = convert_Type(c0_2, _ctx);

      return kk_stella_syntax_ast__new_ATyping(kk_reuse_null, 0, k0_1, k0_2, _ctx);

  }

}

/* ************** Entrypoints (functions to call from Koka) ************ */
kk_std_core_types__maybe kk_parse_Program(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Program parse_tree;
  parse_tree = psProgram(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__program converted = convert_Program(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__program_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListStellaIdent(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListStellaIdent parse_tree;
  parse_tree = psListStellaIdent(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListStellaIdent(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_LanguageDecl(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  LanguageDecl parse_tree;
  parse_tree = psLanguageDecl(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__languageDecl converted = convert_LanguageDecl(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__languageDecl_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Extension(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Extension parse_tree;
  parse_tree = psExtension(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__extension converted = convert_Extension(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__extension_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListExtensionName(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListExtensionName parse_tree;
  parse_tree = psListExtensionName(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListExtensionName(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListExtension(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListExtension parse_tree;
  parse_tree = psListExtension(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListExtension(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Decl(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Decl parse_tree;
  parse_tree = psDecl(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__decl converted = convert_Decl(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__decl_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListDecl(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListDecl parse_tree;
  parse_tree = psListDecl(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListDecl(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_LocalDecl(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  LocalDecl parse_tree;
  parse_tree = psLocalDecl(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__localDecl converted = convert_LocalDecl(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__localDecl_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListLocalDecl(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListLocalDecl parse_tree;
  parse_tree = psListLocalDecl(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListLocalDecl(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Annotation(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Annotation parse_tree;
  parse_tree = psAnnotation(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__annotation converted = convert_Annotation(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__annotation_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListAnnotation(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListAnnotation parse_tree;
  parse_tree = psListAnnotation(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListAnnotation(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ParamDecl(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ParamDecl parse_tree;
  parse_tree = psParamDecl(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__paramDecl converted = convert_ParamDecl(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__paramDecl_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListParamDecl(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListParamDecl parse_tree;
  parse_tree = psListParamDecl(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListParamDecl(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ReturnType(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ReturnType parse_tree;
  parse_tree = psReturnType(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__returnType converted = convert_ReturnType(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__returnType_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ThrowType(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ThrowType parse_tree;
  parse_tree = psThrowType(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__throwType converted = convert_ThrowType(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__throwType_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Type9(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Type parse_tree;
  parse_tree = psType9(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__type__ converted = convert_Type(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__type___box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListType9(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListType parse_tree;
  parse_tree = psListType9(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListType(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_MatchCase(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  MatchCase parse_tree;
  parse_tree = psMatchCase(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__matchCase converted = convert_MatchCase(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__matchCase_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListMatchCase(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListMatchCase parse_tree;
  parse_tree = psListMatchCase(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListMatchCase(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_OptionalTyping(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  OptionalTyping parse_tree;
  parse_tree = psOptionalTyping(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__optionalTyping converted = convert_OptionalTyping(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__optionalTyping_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_PatternData(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  PatternData parse_tree;
  parse_tree = psPatternData(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__patternData converted = convert_PatternData(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__patternData_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ExprData(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ExprData parse_tree;
  parse_tree = psExprData(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__exprData converted = convert_ExprData(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__exprData_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Pattern(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Pattern parse_tree;
  parse_tree = psPattern(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__pattern converted = convert_Pattern(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__pattern_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListPattern(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListPattern parse_tree;
  parse_tree = psListPattern(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListPattern(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_LabelledPattern(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  LabelledPattern parse_tree;
  parse_tree = psLabelledPattern(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__labelledPattern converted = convert_LabelledPattern(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__labelledPattern_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListLabelledPattern(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListLabelledPattern parse_tree;
  parse_tree = psListLabelledPattern(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListLabelledPattern(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Binding(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Binding parse_tree;
  parse_tree = psBinding(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__binding converted = convert_Binding(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__binding_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListBinding(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListBinding parse_tree;
  parse_tree = psListBinding(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListBinding(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Expr(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Expr parse_tree;
  parse_tree = psExpr(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__expr converted = convert_Expr(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__expr_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListExpr(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListExpr parse_tree;
  parse_tree = psListExpr(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListExpr(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Expr1(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Expr parse_tree;
  parse_tree = psExpr1(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__expr converted = convert_Expr(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__expr_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_PatternBinding(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  PatternBinding parse_tree;
  parse_tree = psPatternBinding(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__patternBinding converted = convert_PatternBinding(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__patternBinding_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListPatternBinding(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListPatternBinding parse_tree;
  parse_tree = psListPatternBinding(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListPatternBinding(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Expr2(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Expr parse_tree;
  parse_tree = psExpr2(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__expr converted = convert_Expr(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__expr_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListExpr2(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListExpr parse_tree;
  parse_tree = psListExpr2(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListExpr(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_LabelledEffect(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  LabelledEffect parse_tree;
  parse_tree = psLabelledEffect(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__labelledEffect converted = convert_LabelledEffect(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__labelledEffect_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListLabelledEffect(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListLabelledEffect parse_tree;
  parse_tree = psListLabelledEffect(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListLabelledEffect(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Modality(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Modality parse_tree;
  parse_tree = psModality(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__modality converted = convert_Modality(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__modality_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListModality(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListModality parse_tree;
  parse_tree = psListModality(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListModality(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Expr3(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Expr parse_tree;
  parse_tree = psExpr3(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__expr converted = convert_Expr(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__expr_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Expr4(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Expr parse_tree;
  parse_tree = psExpr4(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__expr converted = convert_Expr(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__expr_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Expr5(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Expr parse_tree;
  parse_tree = psExpr5(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__expr converted = convert_Expr(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__expr_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Expr6(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Expr parse_tree;
  parse_tree = psExpr6(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__expr converted = convert_Expr(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__expr_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Expr7(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Expr parse_tree;
  parse_tree = psExpr7(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__expr converted = convert_Expr(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__expr_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Handler(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Handler parse_tree;
  parse_tree = psHandler(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__handler__ converted = convert_Handler(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__handler___box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListHandler(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListHandler parse_tree;
  parse_tree = psListHandler(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListHandler(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Type(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Type parse_tree;
  parse_tree = psType(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__type__ converted = convert_Type(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__type___box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Type1(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Type parse_tree;
  parse_tree = psType1(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__type__ converted = convert_Type(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__type___box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Type2(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Type parse_tree;
  parse_tree = psType2(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__type__ converted = convert_Type(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__type___box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Type3(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Type parse_tree;
  parse_tree = psType3(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__type__ converted = convert_Type(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__type___box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListType(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListType parse_tree;
  parse_tree = psListType(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListType(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_VariantFieldType(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  VariantFieldType parse_tree;
  parse_tree = psVariantFieldType(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__variantFieldType converted = convert_VariantFieldType(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__variantFieldType_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListVariantFieldType(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListVariantFieldType parse_tree;
  parse_tree = psListVariantFieldType(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListVariantFieldType(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_RecordFieldType(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  RecordFieldType parse_tree;
  parse_tree = psRecordFieldType(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__recordFieldType converted = convert_RecordFieldType(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__recordFieldType_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_ListRecordFieldType(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  ListRecordFieldType parse_tree;
  parse_tree = psListRecordFieldType(cstr);
  if (parse_tree) {
    kk_std_core_types__list converted = convert_ListRecordFieldType(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_std_core_types__list_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
kk_std_core_types__maybe kk_parse_Typing(kk_string_t kstr, kk_context_t* _ctx) {
  const uint8_t* cstr = string_to_chars(kstr, _ctx);
  Typing parse_tree;
  parse_tree = psTyping(cstr);
  if (parse_tree) {
    kk_stella_syntax_ast__typing converted = convert_Typing(parse_tree, _ctx);
    return kk_std_core_types__new_Just(kk_stella_syntax_ast__typing_box(converted, _ctx), _ctx);
  }
  else {
    return kk_std_core_types__new_Nothing(_ctx);
  }
}
