/* File generated by the BNF Converter (bnfc 2.9.7). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printProgram(Program p)
{
  _n_ = 0;
  bufReset();
  ppProgram(p, 0);
  return buf_;
}
char *printListStellaIdent(ListStellaIdent p)
{
  _n_ = 0;
  bufReset();
  ppListStellaIdent(p, 0);
  return buf_;
}
char *printLanguageDecl(LanguageDecl p)
{
  _n_ = 0;
  bufReset();
  ppLanguageDecl(p, 0);
  return buf_;
}
char *printExtension(Extension p)
{
  _n_ = 0;
  bufReset();
  ppExtension(p, 0);
  return buf_;
}
char *printListExtensionName(ListExtensionName p)
{
  _n_ = 0;
  bufReset();
  ppListExtensionName(p, 0);
  return buf_;
}
char *printListExtension(ListExtension p)
{
  _n_ = 0;
  bufReset();
  ppListExtension(p, 0);
  return buf_;
}
char *printDecl(Decl p)
{
  _n_ = 0;
  bufReset();
  ppDecl(p, 0);
  return buf_;
}
char *printListDecl(ListDecl p)
{
  _n_ = 0;
  bufReset();
  ppListDecl(p, 0);
  return buf_;
}
char *printLocalDecl(LocalDecl p)
{
  _n_ = 0;
  bufReset();
  ppLocalDecl(p, 0);
  return buf_;
}
char *printListLocalDecl(ListLocalDecl p)
{
  _n_ = 0;
  bufReset();
  ppListLocalDecl(p, 0);
  return buf_;
}
char *printAnnotation(Annotation p)
{
  _n_ = 0;
  bufReset();
  ppAnnotation(p, 0);
  return buf_;
}
char *printListAnnotation(ListAnnotation p)
{
  _n_ = 0;
  bufReset();
  ppListAnnotation(p, 0);
  return buf_;
}
char *printParamDecl(ParamDecl p)
{
  _n_ = 0;
  bufReset();
  ppParamDecl(p, 0);
  return buf_;
}
char *printListParamDecl(ListParamDecl p)
{
  _n_ = 0;
  bufReset();
  ppListParamDecl(p, 0);
  return buf_;
}
char *printReturnType(ReturnType p)
{
  _n_ = 0;
  bufReset();
  ppReturnType(p, 0);
  return buf_;
}
char *printThrowType(ThrowType p)
{
  _n_ = 0;
  bufReset();
  ppThrowType(p, 0);
  return buf_;
}
char *printType(Type p)
{
  _n_ = 0;
  bufReset();
  ppType(p, 0);
  return buf_;
}
char *printListType(ListType p)
{
  _n_ = 0;
  bufReset();
  ppListType(p, 0);
  return buf_;
}
char *printMatchCase(MatchCase p)
{
  _n_ = 0;
  bufReset();
  ppMatchCase(p, 0);
  return buf_;
}
char *printListMatchCase(ListMatchCase p)
{
  _n_ = 0;
  bufReset();
  ppListMatchCase(p, 0);
  return buf_;
}
char *printOptionalTyping(OptionalTyping p)
{
  _n_ = 0;
  bufReset();
  ppOptionalTyping(p, 0);
  return buf_;
}
char *printPatternData(PatternData p)
{
  _n_ = 0;
  bufReset();
  ppPatternData(p, 0);
  return buf_;
}
char *printExprData(ExprData p)
{
  _n_ = 0;
  bufReset();
  ppExprData(p, 0);
  return buf_;
}
char *printPattern(Pattern p)
{
  _n_ = 0;
  bufReset();
  ppPattern(p, 0);
  return buf_;
}
char *printListPattern(ListPattern p)
{
  _n_ = 0;
  bufReset();
  ppListPattern(p, 0);
  return buf_;
}
char *printLabelledPattern(LabelledPattern p)
{
  _n_ = 0;
  bufReset();
  ppLabelledPattern(p, 0);
  return buf_;
}
char *printListLabelledPattern(ListLabelledPattern p)
{
  _n_ = 0;
  bufReset();
  ppListLabelledPattern(p, 0);
  return buf_;
}
char *printBinding(Binding p)
{
  _n_ = 0;
  bufReset();
  ppBinding(p, 0);
  return buf_;
}
char *printListBinding(ListBinding p)
{
  _n_ = 0;
  bufReset();
  ppListBinding(p, 0);
  return buf_;
}
char *printExpr(Expr p)
{
  _n_ = 0;
  bufReset();
  ppExpr(p, 0);
  return buf_;
}
char *printListExpr(ListExpr p)
{
  _n_ = 0;
  bufReset();
  ppListExpr(p, 0);
  return buf_;
}
char *printPatternBinding(PatternBinding p)
{
  _n_ = 0;
  bufReset();
  ppPatternBinding(p, 0);
  return buf_;
}
char *printListPatternBinding(ListPatternBinding p)
{
  _n_ = 0;
  bufReset();
  ppListPatternBinding(p, 0);
  return buf_;
}
char *printMod(Mod p)
{
  _n_ = 0;
  bufReset();
  ppMod(p, 0);
  return buf_;
}
char *printVariantFieldType(VariantFieldType p)
{
  _n_ = 0;
  bufReset();
  ppVariantFieldType(p, 0);
  return buf_;
}
char *printListVariantFieldType(ListVariantFieldType p)
{
  _n_ = 0;
  bufReset();
  ppListVariantFieldType(p, 0);
  return buf_;
}
char *printRecordFieldType(RecordFieldType p)
{
  _n_ = 0;
  bufReset();
  ppRecordFieldType(p, 0);
  return buf_;
}
char *printListRecordFieldType(ListRecordFieldType p)
{
  _n_ = 0;
  bufReset();
  ppListRecordFieldType(p, 0);
  return buf_;
}
char *printTyping(Typing p)
{
  _n_ = 0;
  bufReset();
  ppTyping(p, 0);
  return buf_;
}
char *showProgram(Program p)
{
  _n_ = 0;
  bufReset();
  shProgram(p);
  return buf_;
}
char *showListStellaIdent(ListStellaIdent p)
{
  _n_ = 0;
  bufReset();
  shListStellaIdent(p);
  return buf_;
}
char *showLanguageDecl(LanguageDecl p)
{
  _n_ = 0;
  bufReset();
  shLanguageDecl(p);
  return buf_;
}
char *showExtension(Extension p)
{
  _n_ = 0;
  bufReset();
  shExtension(p);
  return buf_;
}
char *showListExtensionName(ListExtensionName p)
{
  _n_ = 0;
  bufReset();
  shListExtensionName(p);
  return buf_;
}
char *showListExtension(ListExtension p)
{
  _n_ = 0;
  bufReset();
  shListExtension(p);
  return buf_;
}
char *showDecl(Decl p)
{
  _n_ = 0;
  bufReset();
  shDecl(p);
  return buf_;
}
char *showListDecl(ListDecl p)
{
  _n_ = 0;
  bufReset();
  shListDecl(p);
  return buf_;
}
char *showLocalDecl(LocalDecl p)
{
  _n_ = 0;
  bufReset();
  shLocalDecl(p);
  return buf_;
}
char *showListLocalDecl(ListLocalDecl p)
{
  _n_ = 0;
  bufReset();
  shListLocalDecl(p);
  return buf_;
}
char *showAnnotation(Annotation p)
{
  _n_ = 0;
  bufReset();
  shAnnotation(p);
  return buf_;
}
char *showListAnnotation(ListAnnotation p)
{
  _n_ = 0;
  bufReset();
  shListAnnotation(p);
  return buf_;
}
char *showParamDecl(ParamDecl p)
{
  _n_ = 0;
  bufReset();
  shParamDecl(p);
  return buf_;
}
char *showListParamDecl(ListParamDecl p)
{
  _n_ = 0;
  bufReset();
  shListParamDecl(p);
  return buf_;
}
char *showReturnType(ReturnType p)
{
  _n_ = 0;
  bufReset();
  shReturnType(p);
  return buf_;
}
char *showThrowType(ThrowType p)
{
  _n_ = 0;
  bufReset();
  shThrowType(p);
  return buf_;
}
char *showType(Type p)
{
  _n_ = 0;
  bufReset();
  shType(p);
  return buf_;
}
char *showListType(ListType p)
{
  _n_ = 0;
  bufReset();
  shListType(p);
  return buf_;
}
char *showMatchCase(MatchCase p)
{
  _n_ = 0;
  bufReset();
  shMatchCase(p);
  return buf_;
}
char *showListMatchCase(ListMatchCase p)
{
  _n_ = 0;
  bufReset();
  shListMatchCase(p);
  return buf_;
}
char *showOptionalTyping(OptionalTyping p)
{
  _n_ = 0;
  bufReset();
  shOptionalTyping(p);
  return buf_;
}
char *showPatternData(PatternData p)
{
  _n_ = 0;
  bufReset();
  shPatternData(p);
  return buf_;
}
char *showExprData(ExprData p)
{
  _n_ = 0;
  bufReset();
  shExprData(p);
  return buf_;
}
char *showPattern(Pattern p)
{
  _n_ = 0;
  bufReset();
  shPattern(p);
  return buf_;
}
char *showListPattern(ListPattern p)
{
  _n_ = 0;
  bufReset();
  shListPattern(p);
  return buf_;
}
char *showLabelledPattern(LabelledPattern p)
{
  _n_ = 0;
  bufReset();
  shLabelledPattern(p);
  return buf_;
}
char *showListLabelledPattern(ListLabelledPattern p)
{
  _n_ = 0;
  bufReset();
  shListLabelledPattern(p);
  return buf_;
}
char *showBinding(Binding p)
{
  _n_ = 0;
  bufReset();
  shBinding(p);
  return buf_;
}
char *showListBinding(ListBinding p)
{
  _n_ = 0;
  bufReset();
  shListBinding(p);
  return buf_;
}
char *showExpr(Expr p)
{
  _n_ = 0;
  bufReset();
  shExpr(p);
  return buf_;
}
char *showListExpr(ListExpr p)
{
  _n_ = 0;
  bufReset();
  shListExpr(p);
  return buf_;
}
char *showPatternBinding(PatternBinding p)
{
  _n_ = 0;
  bufReset();
  shPatternBinding(p);
  return buf_;
}
char *showListPatternBinding(ListPatternBinding p)
{
  _n_ = 0;
  bufReset();
  shListPatternBinding(p);
  return buf_;
}
char *showMod(Mod p)
{
  _n_ = 0;
  bufReset();
  shMod(p);
  return buf_;
}
char *showVariantFieldType(VariantFieldType p)
{
  _n_ = 0;
  bufReset();
  shVariantFieldType(p);
  return buf_;
}
char *showListVariantFieldType(ListVariantFieldType p)
{
  _n_ = 0;
  bufReset();
  shListVariantFieldType(p);
  return buf_;
}
char *showRecordFieldType(RecordFieldType p)
{
  _n_ = 0;
  bufReset();
  shRecordFieldType(p);
  return buf_;
}
char *showListRecordFieldType(ListRecordFieldType p)
{
  _n_ = 0;
  bufReset();
  shListRecordFieldType(p);
  return buf_;
}
char *showTyping(Typing p)
{
  _n_ = 0;
  bufReset();
  shTyping(p);
  return buf_;
}
void ppProgram(Program p, int _i_)
{
  switch(p->kind)
  {
  case is_AProgram:
    if (_i_ > 0) renderC(_L_PAREN);
    ppLanguageDecl(p->u.aProgram_.languagedecl_, 0);
    ppListExtension(p->u.aProgram_.listextension_, 0);
    ppListDecl(p->u.aProgram_.listdecl_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Program!\n");
    exit(1);
  }
}

void ppListStellaIdent(ListStellaIdent liststellaident, int i)
{
  if (liststellaident == 0)
  { /* nil */
  }
  else if (liststellaident->liststellaident_ == 0)
  { /* last */
    ppIdent(liststellaident->stellaident_, 0);
  }
  else
  { /* cons */
    ppIdent(liststellaident->stellaident_, 0);
    renderC(',');
    ppListStellaIdent(liststellaident->liststellaident_, 0);
  }
}

void ppLanguageDecl(LanguageDecl p, int _i_)
{
  switch(p->kind)
  {
  case is_LanguageCore:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("language");
    renderS("core");
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing LanguageDecl!\n");
    exit(1);
  }
}

void ppExtension(Extension p, int _i_)
{
  switch(p->kind)
  {
  case is_AnExtension:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("extend");
    renderS("with");
    ppListExtensionName(p->u.anExtension_.listextensionname_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Extension!\n");
    exit(1);
  }
}

void ppListExtensionName(ListExtensionName listextensionname, int i)
{
  if (listextensionname == 0)
  { /* nil */
  }
  else if (listextensionname->listextensionname_ == 0)
  { /* last */
    ppIdent(listextensionname->extensionname_, 0);
  }
  else
  { /* cons */
    ppIdent(listextensionname->extensionname_, 0);
    renderC(',');
    ppListExtensionName(listextensionname->listextensionname_, 0);
  }
}

void ppListExtension(ListExtension listextension, int i)
{
  if (listextension == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppExtension(listextension->extension_, 0);
    renderC(';');
    ppListExtension(listextension->listextension_, 0);
  }
}

void ppDecl(Decl p, int _i_)
{
  switch(p->kind)
  {
  case is_DeclFun:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListAnnotation(p->u.declFun_.listannotation_, 0);
    renderS("fn");
    ppIdent(p->u.declFun_.stellaident_, 0);
    renderC('(');
    ppListParamDecl(p->u.declFun_.listparamdecl_, 0);
    renderC(')');
    ppReturnType(p->u.declFun_.returntype_, 0);
    ppThrowType(p->u.declFun_.throwtype_, 0);
    renderC('{');
    ppListDecl(p->u.declFun_.listdecl_, 0);
    renderS("return");
    ppExpr(p->u.declFun_.expr_, 0);
    renderC('}');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_DeclFunGeneric:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListAnnotation(p->u.declFunGeneric_.listannotation_, 0);
    renderS("generic");
    renderS("fn");
    ppIdent(p->u.declFunGeneric_.stellaident_, 0);
    renderC('[');
    ppListStellaIdent(p->u.declFunGeneric_.liststellaident_, 0);
    renderC(']');
    renderC('(');
    ppListParamDecl(p->u.declFunGeneric_.listparamdecl_, 0);
    renderC(')');
    ppReturnType(p->u.declFunGeneric_.returntype_, 0);
    ppThrowType(p->u.declFunGeneric_.throwtype_, 0);
    renderC('{');
    ppListDecl(p->u.declFunGeneric_.listdecl_, 0);
    renderS("return");
    ppExpr(p->u.declFunGeneric_.expr_, 0);
    renderC('}');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_DeclFunMod:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListAnnotation(p->u.declFunMod_.listannotation_, 0);
    renderS("mod");
    renderC('[');
    ppMod(p->u.declFunMod_.mod_, 0);
    renderC(']');
    renderS("fn");
    ppIdent(p->u.declFunMod_.stellaident_, 0);
    renderC('(');
    ppListParamDecl(p->u.declFunMod_.listparamdecl_, 0);
    renderC(')');
    ppReturnType(p->u.declFunMod_.returntype_, 0);
    ppThrowType(p->u.declFunMod_.throwtype_, 0);
    renderC('{');
    ppListDecl(p->u.declFunMod_.listdecl_, 0);
    renderS("return");
    ppExpr(p->u.declFunMod_.expr_, 0);
    renderC('}');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_DeclTypeAlias:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("type");
    ppIdent(p->u.declTypeAlias_.stellaident_, 0);
    renderC('=');
    ppType(p->u.declTypeAlias_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_DeclExceptionType:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("exception");
    renderS("type");
    renderC('=');
    ppType(p->u.declExceptionType_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_DeclExceptionVariant:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("exception");
    renderS("variant");
    ppIdent(p->u.declExceptionVariant_.stellaident_, 0);
    renderC(':');
    ppType(p->u.declExceptionVariant_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Decl!\n");
    exit(1);
  }
}

void ppListDecl(ListDecl listdecl, int i)
{
  if (listdecl == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppDecl(listdecl->decl_, 0); ppListDecl(listdecl->listdecl_, 0);
  }
}

void ppLocalDecl(LocalDecl p, int _i_)
{
  switch(p->kind)
  {
  case is_ALocalDecl:
    if (_i_ > 0) renderC(_L_PAREN);
    ppDecl(p->u.aLocalDecl_.decl_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing LocalDecl!\n");
    exit(1);
  }
}

void ppListLocalDecl(ListLocalDecl listlocaldecl, int i)
{
  if (listlocaldecl == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppLocalDecl(listlocaldecl->localdecl_, 0);
    renderC(';');
    ppListLocalDecl(listlocaldecl->listlocaldecl_, 0);
  }
}

void ppAnnotation(Annotation p, int _i_)
{
  switch(p->kind)
  {
  case is_InlineAnnotation:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("inline");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Annotation!\n");
    exit(1);
  }
}

void ppListAnnotation(ListAnnotation listannotation, int i)
{
  if (listannotation == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppAnnotation(listannotation->annotation_, 0);
    ppListAnnotation(listannotation->listannotation_, 0);
  }
}

void ppParamDecl(ParamDecl p, int _i_)
{
  switch(p->kind)
  {
  case is_AParamDecl:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.aParamDecl_.stellaident_, 0);
    renderC(':');
    ppType(p->u.aParamDecl_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ParamDecl!\n");
    exit(1);
  }
}

void ppListParamDecl(ListParamDecl listparamdecl, int i)
{
  if (listparamdecl == 0)
  { /* nil */
  }
  else if (listparamdecl->listparamdecl_ == 0)
  { /* last */
    ppParamDecl(listparamdecl->paramdecl_, 0);
  }
  else
  { /* cons */
    ppParamDecl(listparamdecl->paramdecl_, 0);
    renderC(',');
    ppListParamDecl(listparamdecl->listparamdecl_, 0);
  }
}

void ppReturnType(ReturnType p, int _i_)
{
  switch(p->kind)
  {
  case is_NoReturnType:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SomeReturnType:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("->");
    ppType(p->u.someReturnType_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ReturnType!\n");
    exit(1);
  }
}

void ppThrowType(ThrowType p, int _i_)
{
  switch(p->kind)
  {
  case is_NoThrowType:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SomeThrowType:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("throws");
    ppListType(p->u.someThrowType_.listtype_, 9);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ThrowType!\n");
    exit(1);
  }
}

void ppType(Type p, int _i_)
{
  switch(p->kind)
  {
  case is_TypeAuto:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("auto");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TypeFun:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("fn");
    renderC('(');
    ppListType(p->u.typeFun_.listtype_, 0);
    renderC(')');
    renderS("->");
    ppType(p->u.typeFun_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TypeForAll:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("forall");
    ppListStellaIdent(p->u.typeForAll_.liststellaident_, 0);
    renderC('.');
    ppType(p->u.typeForAll_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TypeRec:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('\181');
    ppIdent(p->u.typeRec_.stellaident_, 0);
    renderC('.');
    ppType(p->u.typeRec_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TypeSum:
    if (_i_ > 1) renderC(_L_PAREN);
    ppType(p->u.typeSum_.type_1, 2);
    renderC('+');
    ppType(p->u.typeSum_.type_2, 2);
    if (_i_ > 1) renderC(_R_PAREN);
    break;

  case is_TypeTuple:
    if (_i_ > 2) renderC(_L_PAREN);
    renderC('{');
    ppListType(p->u.typeTuple_.listtype_, 0);
    renderC('}');
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_TypeRecord:
    if (_i_ > 2) renderC(_L_PAREN);
    renderC('{');
    ppListRecordFieldType(p->u.typeRecord_.listrecordfieldtype_, 0);
    renderC('}');
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_TypeVariant:
    if (_i_ > 2) renderC(_L_PAREN);
    renderS("<|");
    ppListVariantFieldType(p->u.typeVariant_.listvariantfieldtype_, 0);
    renderS("|>");
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_TypeList:
    if (_i_ > 2) renderC(_L_PAREN);
    renderC('[');
    ppType(p->u.typeList_.type_, 0);
    renderC(']');
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_TypeBool:
    if (_i_ > 3) renderC(_L_PAREN);
    renderS("Bool");
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_TypeNat:
    if (_i_ > 3) renderC(_L_PAREN);
    renderS("Nat");
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_TypeUnit:
    if (_i_ > 3) renderC(_L_PAREN);
    renderS("Unit");
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_TypeTop:
    if (_i_ > 3) renderC(_L_PAREN);
    renderS("Top");
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_TypeBottom:
    if (_i_ > 3) renderC(_L_PAREN);
    renderS("Bot");
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_TypeRef:
    if (_i_ > 3) renderC(_L_PAREN);
    renderC('&');
    ppType(p->u.typeRef_.type_, 2);
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_TypeVar:
    if (_i_ > 3) renderC(_L_PAREN);
    ppIdent(p->u.typeVar_.stellaident_, 0);
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Type!\n");
    exit(1);
  }
}

void ppListType(ListType listtype, int i)
{
  if (listtype == 0)
  { /* nil */
  }
  else if (listtype->listtype_ == 0)
  { /* last */
    switch(i)
    {
      case 9: ppType(listtype->type_, 9); break;
      case 0: ppType(listtype->type_, 0); break;
    }
  }
  else
  { /* cons */
    switch(i)
    {
      case 9: ppType(listtype->type_, 9);
              renderC(',');
              ppListType(listtype->listtype_, 9); break;
      case 0: ppType(listtype->type_, 0);
              renderC(',');
              ppListType(listtype->listtype_, 0); break;
    }
  }
}

void ppMatchCase(MatchCase p, int _i_)
{
  switch(p->kind)
  {
  case is_AMatchCase:
    if (_i_ > 0) renderC(_L_PAREN);
    ppPattern(p->u.aMatchCase_.pattern_, 0);
    renderS("=>");
    ppExpr(p->u.aMatchCase_.expr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing MatchCase!\n");
    exit(1);
  }
}

void ppListMatchCase(ListMatchCase listmatchcase, int i)
{
  if (listmatchcase == 0)
  { /* nil */
  }
  else if (listmatchcase->listmatchcase_ == 0)
  { /* last */
    ppMatchCase(listmatchcase->matchcase_, 0);
  }
  else
  { /* cons */
    ppMatchCase(listmatchcase->matchcase_, 0);
    renderC('|');
    ppListMatchCase(listmatchcase->listmatchcase_, 0);
  }
}

void ppOptionalTyping(OptionalTyping p, int _i_)
{
  switch(p->kind)
  {
  case is_NoTyping:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SomeTyping:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC(':');
    ppType(p->u.someTyping_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptionalTyping!\n");
    exit(1);
  }
}

void ppPatternData(PatternData p, int _i_)
{
  switch(p->kind)
  {
  case is_NoPatternData:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SomePatternData:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('=');
    ppPattern(p->u.somePatternData_.pattern_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing PatternData!\n");
    exit(1);
  }
}

void ppExprData(ExprData p, int _i_)
{
  switch(p->kind)
  {
  case is_NoExprData:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_SomeExprData:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('=');
    ppExpr(p->u.someExprData_.expr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ExprData!\n");
    exit(1);
  }
}

void ppPattern(Pattern p, int _i_)
{
  switch(p->kind)
  {
  case is_PatternCastAs:
    if (_i_ > 0) renderC(_L_PAREN);
    ppPattern(p->u.patternCastAs_.pattern_, 0);
    renderS("cast");
    renderS("as");
    ppType(p->u.patternCastAs_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternAsc:
    if (_i_ > 0) renderC(_L_PAREN);
    ppPattern(p->u.patternAsc_.pattern_, 0);
    renderS("as");
    ppType(p->u.patternAsc_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternVariant:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("<|");
    ppIdent(p->u.patternVariant_.stellaident_, 0);
    ppPatternData(p->u.patternVariant_.patterndata_, 0);
    renderS("|>");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternInl:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("inl");
    renderC('(');
    ppPattern(p->u.patternInl_.pattern_, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternInr:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("inr");
    renderC('(');
    ppPattern(p->u.patternInr_.pattern_, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternTuple:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('{');
    ppListPattern(p->u.patternTuple_.listpattern_, 0);
    renderC('}');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternRecord:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('{');
    ppListLabelledPattern(p->u.patternRecord_.listlabelledpattern_, 0);
    renderC('}');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternList:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('[');
    ppListPattern(p->u.patternList_.listpattern_, 0);
    renderC(']');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternCons:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("cons");
    renderC('(');
    ppPattern(p->u.patternCons_.pattern_1, 0);
    renderC(',');
    ppPattern(p->u.patternCons_.pattern_2, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternFalse:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("false");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternTrue:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("true");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternUnit:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("unit");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternInt:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.patternInt_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternSucc:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("succ");
    renderC('(');
    ppPattern(p->u.patternSucc_.pattern_, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_PatternVar:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.patternVar_.stellaident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Pattern!\n");
    exit(1);
  }
}

void ppListPattern(ListPattern listpattern, int i)
{
  if (listpattern == 0)
  { /* nil */
  }
  else if (listpattern->listpattern_ == 0)
  { /* last */
    ppPattern(listpattern->pattern_, 0);
  }
  else
  { /* cons */
    ppPattern(listpattern->pattern_, 0);
    renderC(',');
    ppListPattern(listpattern->listpattern_, 0);
  }
}

void ppLabelledPattern(LabelledPattern p, int _i_)
{
  switch(p->kind)
  {
  case is_ALabelledPattern:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.aLabelledPattern_.stellaident_, 0);
    renderC('=');
    ppPattern(p->u.aLabelledPattern_.pattern_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing LabelledPattern!\n");
    exit(1);
  }
}

void ppListLabelledPattern(ListLabelledPattern listlabelledpattern, int i)
{
  if (listlabelledpattern == 0)
  { /* nil */
  }
  else if (listlabelledpattern->listlabelledpattern_ == 0)
  { /* last */
    ppLabelledPattern(listlabelledpattern->labelledpattern_, 0);
  }
  else
  { /* cons */
    ppLabelledPattern(listlabelledpattern->labelledpattern_, 0);
    renderC(',');
    ppListLabelledPattern(listlabelledpattern->listlabelledpattern_, 0);
  }
}

void ppBinding(Binding p, int _i_)
{
  switch(p->kind)
  {
  case is_ABinding:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.aBinding_.stellaident_, 0);
    renderC('=');
    ppExpr(p->u.aBinding_.expr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Binding!\n");
    exit(1);
  }
}

void ppListBinding(ListBinding listbinding, int i)
{
  if (listbinding == 0)
  { /* nil */
  }
  else if (listbinding->listbinding_ == 0)
  { /* last */
    ppBinding(listbinding->binding_, 0);
  }
  else
  { /* cons */
    ppBinding(listbinding->binding_, 0);
    renderC(',');
    ppListBinding(listbinding->listbinding_, 0);
  }
}

void ppExpr(Expr p, int _i_)
{
  switch(p->kind)
  {
  case is_Sequence:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExpr(p->u.sequence_.expr_1, 1);
    renderC(';');
    ppExpr(p->u.sequence_.expr_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Let:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("let");
    ppListPatternBinding(p->u.let_.listpatternbinding_, 0);
    renderS("in");
    ppExpr(p->u.let_.expr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_LetRec:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("letrec");
    ppListPatternBinding(p->u.letRec_.listpatternbinding_, 0);
    renderS("in");
    ppExpr(p->u.letRec_.expr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TypeAbstraction:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("generic");
    renderC('[');
    ppListStellaIdent(p->u.typeAbstraction_.liststellaident_, 0);
    renderC(']');
    ppExpr(p->u.typeAbstraction_.expr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Assign:
    if (_i_ > 1) renderC(_L_PAREN);
    ppExpr(p->u.assign_.expr_1, 2);
    renderS(":=");
    ppExpr(p->u.assign_.expr_2, 1);
    if (_i_ > 1) renderC(_R_PAREN);
    break;

  case is_If:
    if (_i_ > 1) renderC(_L_PAREN);
    renderS("if");
    ppExpr(p->u.if_.expr_1, 1);
    renderS("then");
    ppExpr(p->u.if_.expr_2, 1);
    renderS("else");
    ppExpr(p->u.if_.expr_3, 1);
    if (_i_ > 1) renderC(_R_PAREN);
    break;

  case is_LessThan:
    if (_i_ > 2) renderC(_L_PAREN);
    ppExpr(p->u.lessThan_.expr_1, 3);
    renderC('<');
    ppExpr(p->u.lessThan_.expr_2, 3);
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_LessThanOrEqual:
    if (_i_ > 2) renderC(_L_PAREN);
    ppExpr(p->u.lessThanOrEqual_.expr_1, 3);
    renderS("<=");
    ppExpr(p->u.lessThanOrEqual_.expr_2, 3);
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_GreaterThan:
    if (_i_ > 2) renderC(_L_PAREN);
    ppExpr(p->u.greaterThan_.expr_1, 3);
    renderC('>');
    ppExpr(p->u.greaterThan_.expr_2, 3);
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_GreaterThanOrEqual:
    if (_i_ > 2) renderC(_L_PAREN);
    ppExpr(p->u.greaterThanOrEqual_.expr_1, 3);
    renderS(">=");
    ppExpr(p->u.greaterThanOrEqual_.expr_2, 3);
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_Equal:
    if (_i_ > 2) renderC(_L_PAREN);
    ppExpr(p->u.equal_.expr_1, 3);
    renderS("==");
    ppExpr(p->u.equal_.expr_2, 3);
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_NotEqual:
    if (_i_ > 2) renderC(_L_PAREN);
    ppExpr(p->u.notEqual_.expr_1, 3);
    renderS("!=");
    ppExpr(p->u.notEqual_.expr_2, 3);
    if (_i_ > 2) renderC(_R_PAREN);
    break;

  case is_TypeAsc:
    if (_i_ > 3) renderC(_L_PAREN);
    ppExpr(p->u.typeAsc_.expr_, 3);
    renderS("as");
    ppType(p->u.typeAsc_.type_, 2);
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_TypeCast:
    if (_i_ > 3) renderC(_L_PAREN);
    ppExpr(p->u.typeCast_.expr_, 3);
    renderS("cast");
    renderS("as");
    ppType(p->u.typeCast_.type_, 2);
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_Abstraction:
    if (_i_ > 3) renderC(_L_PAREN);
    renderS("fn");
    renderC('(');
    ppListParamDecl(p->u.abstraction_.listparamdecl_, 0);
    renderC(')');
    renderC('{');
    renderS("return");
    ppExpr(p->u.abstraction_.expr_, 0);
    renderC('}');
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_Mod:
    if (_i_ > 3) renderC(_L_PAREN);
    renderS("mod");
    renderC('[');
    ppMod(p->u.mod_.mod_, 0);
    renderC(']');
    renderC('{');
    ppExpr(p->u.mod_.expr_, 0);
    renderC('}');
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_Variant:
    if (_i_ > 3) renderC(_L_PAREN);
    renderS("<|");
    ppIdent(p->u.variant_.stellaident_, 0);
    ppExprData(p->u.variant_.exprdata_, 0);
    renderS("|>");
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_Match:
    if (_i_ > 3) renderC(_L_PAREN);
    renderS("match");
    ppExpr(p->u.match_.expr_, 2);
    renderC('{');
    ppListMatchCase(p->u.match_.listmatchcase_, 0);
    renderC('}');
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_List:
    if (_i_ > 3) renderC(_L_PAREN);
    renderC('[');
    ppListExpr(p->u.list_.listexpr_, 0);
    renderC(']');
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_Add:
    if (_i_ > 3) renderC(_L_PAREN);
    ppExpr(p->u.add_.expr_1, 3);
    renderC('+');
    ppExpr(p->u.add_.expr_2, 4);
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_Subtract:
    if (_i_ > 3) renderC(_L_PAREN);
    ppExpr(p->u.subtract_.expr_1, 3);
    renderC('-');
    ppExpr(p->u.subtract_.expr_2, 4);
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_LogicOr:
    if (_i_ > 3) renderC(_L_PAREN);
    ppExpr(p->u.logicOr_.expr_1, 3);
    renderS("or");
    ppExpr(p->u.logicOr_.expr_2, 4);
    if (_i_ > 3) renderC(_R_PAREN);
    break;

  case is_Multiply:
    if (_i_ > 4) renderC(_L_PAREN);
    ppExpr(p->u.multiply_.expr_1, 4);
    renderC('*');
    ppExpr(p->u.multiply_.expr_2, 5);
    if (_i_ > 4) renderC(_R_PAREN);
    break;

  case is_Divide:
    if (_i_ > 4) renderC(_L_PAREN);
    ppExpr(p->u.divide_.expr_1, 4);
    renderC('/');
    ppExpr(p->u.divide_.expr_2, 5);
    if (_i_ > 4) renderC(_R_PAREN);
    break;

  case is_LogicAnd:
    if (_i_ > 4) renderC(_L_PAREN);
    ppExpr(p->u.logicAnd_.expr_1, 4);
    renderS("and");
    ppExpr(p->u.logicAnd_.expr_2, 5);
    if (_i_ > 4) renderC(_R_PAREN);
    break;

  case is_Ref:
    if (_i_ > 5) renderC(_L_PAREN);
    renderS("new");
    renderC('(');
    ppExpr(p->u.ref_.expr_, 0);
    renderC(')');
    if (_i_ > 5) renderC(_R_PAREN);
    break;

  case is_Deref:
    if (_i_ > 5) renderC(_L_PAREN);
    renderC('*');
    ppExpr(p->u.deref_.expr_, 5);
    if (_i_ > 5) renderC(_R_PAREN);
    break;

  case is_Application:
    if (_i_ > 6) renderC(_L_PAREN);
    ppExpr(p->u.application_.expr_, 6);
    renderC('(');
    ppListExpr(p->u.application_.listexpr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_TypeApplication:
    if (_i_ > 6) renderC(_L_PAREN);
    ppExpr(p->u.typeApplication_.expr_, 6);
    renderC('[');
    ppListType(p->u.typeApplication_.listtype_, 0);
    renderC(']');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_DotRecord:
    if (_i_ > 6) renderC(_L_PAREN);
    ppExpr(p->u.dotRecord_.expr_, 6);
    renderC('.');
    ppIdent(p->u.dotRecord_.stellaident_, 0);
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_DotTuple:
    if (_i_ > 6) renderC(_L_PAREN);
    ppExpr(p->u.dotTuple_.expr_, 6);
    renderC('.');
    ppInteger(p->u.dotTuple_.integer_, 0);
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Tuple:
    if (_i_ > 6) renderC(_L_PAREN);
    renderC('{');
    ppListExpr(p->u.tuple_.listexpr_, 0);
    renderC('}');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Record:
    if (_i_ > 6) renderC(_L_PAREN);
    renderC('{');
    ppListBinding(p->u.record_.listbinding_, 0);
    renderC('}');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_ConsList:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("cons");
    renderC('(');
    ppExpr(p->u.consList_.expr_1, 0);
    renderC(',');
    ppExpr(p->u.consList_.expr_2, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Head:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("List::head");
    renderC('(');
    ppExpr(p->u.head_.expr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_IsEmpty:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("List::isempty");
    renderC('(');
    ppExpr(p->u.isEmpty_.expr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Tail:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("List::tail");
    renderC('(');
    ppExpr(p->u.tail_.expr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Panic:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("panic!");
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Throw:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("throw");
    renderC('(');
    ppExpr(p->u.throw_.expr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_TryCatch:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("try");
    renderC('{');
    ppExpr(p->u.tryCatch_.expr_1, 0);
    renderC('}');
    renderS("catch");
    renderC('{');
    ppPattern(p->u.tryCatch_.pattern_, 0);
    renderS("=>");
    ppExpr(p->u.tryCatch_.expr_2, 0);
    renderC('}');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_TryWith:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("try");
    renderC('{');
    ppExpr(p->u.tryWith_.expr_1, 0);
    renderC('}');
    renderS("with");
    renderC('{');
    ppExpr(p->u.tryWith_.expr_2, 0);
    renderC('}');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_TryCastAs:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("try");
    renderC('{');
    ppExpr(p->u.tryCastAs_.expr_1, 0);
    renderC('}');
    renderS("cast");
    renderS("as");
    ppType(p->u.tryCastAs_.type_, 0);
    renderC('{');
    ppPattern(p->u.tryCastAs_.pattern_, 0);
    renderS("=>");
    ppExpr(p->u.tryCastAs_.expr_2, 0);
    renderC('}');
    renderS("with");
    renderC('{');
    ppExpr(p->u.tryCastAs_.expr_3, 0);
    renderC('}');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Inl:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("inl");
    renderC('(');
    ppExpr(p->u.inl_.expr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Inr:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("inr");
    renderC('(');
    ppExpr(p->u.inr_.expr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Succ:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("succ");
    renderC('(');
    ppExpr(p->u.succ_.expr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_LogicNot:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("not");
    renderC('(');
    ppExpr(p->u.logicNot_.expr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Pred:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("Nat::pred");
    renderC('(');
    ppExpr(p->u.pred_.expr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_IsZero:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("Nat::iszero");
    renderC('(');
    ppExpr(p->u.isZero_.expr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Fix:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("fix");
    renderC('(');
    ppExpr(p->u.fix_.expr_, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_NatRec:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("Nat::rec");
    renderC('(');
    ppExpr(p->u.natRec_.expr_1, 0);
    renderC(',');
    ppExpr(p->u.natRec_.expr_2, 0);
    renderC(',');
    ppExpr(p->u.natRec_.expr_3, 0);
    renderC(')');
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Fold:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("fold");
    renderC('[');
    ppType(p->u.fold_.type_, 0);
    renderC(']');
    ppExpr(p->u.fold_.expr_, 7);
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_Unfold:
    if (_i_ > 6) renderC(_L_PAREN);
    renderS("unfold");
    renderC('[');
    ppType(p->u.unfold_.type_, 0);
    renderC(']');
    ppExpr(p->u.unfold_.expr_, 7);
    if (_i_ > 6) renderC(_R_PAREN);
    break;

  case is_ConstTrue:
    if (_i_ > 7) renderC(_L_PAREN);
    renderS("true");
    if (_i_ > 7) renderC(_R_PAREN);
    break;

  case is_ConstFalse:
    if (_i_ > 7) renderC(_L_PAREN);
    renderS("false");
    if (_i_ > 7) renderC(_R_PAREN);
    break;

  case is_ConstUnit:
    if (_i_ > 7) renderC(_L_PAREN);
    renderS("unit");
    if (_i_ > 7) renderC(_R_PAREN);
    break;

  case is_ConstInt:
    if (_i_ > 7) renderC(_L_PAREN);
    ppInteger(p->u.constInt_.integer_, 0);
    if (_i_ > 7) renderC(_R_PAREN);
    break;

  case is_ConstMemory:
    if (_i_ > 7) renderC(_L_PAREN);
    ppIdent(p->u.constMemory_.memoryaddress_, 0);
    if (_i_ > 7) renderC(_R_PAREN);
    break;

  case is_Var:
    if (_i_ > 7) renderC(_L_PAREN);
    ppIdent(p->u.var_.stellaident_, 0);
    if (_i_ > 7) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Expr!\n");
    exit(1);
  }
}

void ppListExpr(ListExpr listexpr, int i)
{
  if (listexpr == 0)
  { /* nil */
  }
  else if (listexpr->listexpr_ == 0)
  { /* last */
    switch(i)
    {
      case 2: ppExpr(listexpr->expr_, 2); renderC(';'); break;
      case 0: ppExpr(listexpr->expr_, 0); break;
    }
  }
  else
  { /* cons */
    switch(i)
    {
      case 2: ppExpr(listexpr->expr_, 2);
              renderC(';');
              ppListExpr(listexpr->listexpr_, 2); break;
      case 0: ppExpr(listexpr->expr_, 0);
              renderC(',');
              ppListExpr(listexpr->listexpr_, 0); break;
    }
  }
}

void ppPatternBinding(PatternBinding p, int _i_)
{
  switch(p->kind)
  {
  case is_APatternBinding:
    if (_i_ > 0) renderC(_L_PAREN);
    ppPattern(p->u.aPatternBinding_.pattern_, 0);
    renderC('=');
    ppExpr(p->u.aPatternBinding_.expr_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing PatternBinding!\n");
    exit(1);
  }
}

void ppListPatternBinding(ListPatternBinding listpatternbinding, int i)
{
  if (listpatternbinding == 0)
  { /* nil */
  }
  else if (listpatternbinding->listpatternbinding_ == 0)
  { /* last */
    ppPatternBinding(listpatternbinding->patternbinding_, 0);
  }
  else
  { /* cons */
    ppPatternBinding(listpatternbinding->patternbinding_, 0);
    renderC(',');
    ppListPatternBinding(listpatternbinding->listpatternbinding_, 0);
  }
}

void ppMod(Mod p, int _i_)
{
  switch(p->kind)
  {
  case is_ModLock:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("lock");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Mod!\n");
    exit(1);
  }
}

void ppVariantFieldType(VariantFieldType p, int _i_)
{
  switch(p->kind)
  {
  case is_AVariantFieldType:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.aVariantFieldType_.stellaident_, 0);
    ppOptionalTyping(p->u.aVariantFieldType_.optionaltyping_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing VariantFieldType!\n");
    exit(1);
  }
}

void ppListVariantFieldType(ListVariantFieldType listvariantfieldtype, int i)
{
  if (listvariantfieldtype == 0)
  { /* nil */
  }
  else if (listvariantfieldtype->listvariantfieldtype_ == 0)
  { /* last */
    ppVariantFieldType(listvariantfieldtype->variantfieldtype_, 0);
  }
  else
  { /* cons */
    ppVariantFieldType(listvariantfieldtype->variantfieldtype_, 0);
    renderC(',');
    ppListVariantFieldType(listvariantfieldtype->listvariantfieldtype_, 0);
  }
}

void ppRecordFieldType(RecordFieldType p, int _i_)
{
  switch(p->kind)
  {
  case is_ARecordFieldType:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.aRecordFieldType_.stellaident_, 0);
    renderC(':');
    ppType(p->u.aRecordFieldType_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RecordFieldType!\n");
    exit(1);
  }
}

void ppListRecordFieldType(ListRecordFieldType listrecordfieldtype, int i)
{
  if (listrecordfieldtype == 0)
  { /* nil */
  }
  else if (listrecordfieldtype->listrecordfieldtype_ == 0)
  { /* last */
    ppRecordFieldType(listrecordfieldtype->recordfieldtype_, 0);
  }
  else
  { /* cons */
    ppRecordFieldType(listrecordfieldtype->recordfieldtype_, 0);
    renderC(',');
    ppListRecordFieldType(listrecordfieldtype->listrecordfieldtype_, 0);
  }
}

void ppTyping(Typing p, int _i_)
{
  switch(p->kind)
  {
  case is_ATyping:
    if (_i_ > 0) renderC(_L_PAREN);
    ppExpr(p->u.aTyping_.expr_, 0);
    renderC(':');
    ppType(p->u.aTyping_.type_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Typing!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void ppStellaIdent(String s, int i)
{
  renderS(s);
}


void ppExtensionName(String s, int i)
{
  renderS(s);
}


void ppMemoryAddress(String s, int i)
{
  renderS(s);
}


void shProgram(Program p)
{
  switch(p->kind)
  {
  case is_AProgram:
    bufAppendC('(');

    bufAppendS("AProgram");

    bufAppendC(' ');

    shLanguageDecl(p->u.aProgram_.languagedecl_);
  bufAppendC(' ');
    shListExtension(p->u.aProgram_.listextension_);
  bufAppendC(' ');
    shListDecl(p->u.aProgram_.listdecl_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Program!\n");
    exit(1);
  }
}

void shListStellaIdent(ListStellaIdent liststellaident)
{
  bufAppendC('[');
  while(liststellaident != 0)
  {
    if (liststellaident->liststellaident_)
    {
      shStellaIdent(liststellaident->stellaident_);
      bufAppendS(", ");
      liststellaident = liststellaident->liststellaident_;
    }
    else
    {
      shStellaIdent(liststellaident->stellaident_);
      liststellaident = 0;
    }
  }
  bufAppendC(']');
}

void shLanguageDecl(LanguageDecl p)
{
  switch(p->kind)
  {
  case is_LanguageCore:

    bufAppendS("LanguageCore");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing LanguageDecl!\n");
    exit(1);
  }
}

void shExtension(Extension p)
{
  switch(p->kind)
  {
  case is_AnExtension:
    bufAppendC('(');

    bufAppendS("AnExtension");

    bufAppendC(' ');

    shListExtensionName(p->u.anExtension_.listextensionname_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Extension!\n");
    exit(1);
  }
}

void shListExtensionName(ListExtensionName listextensionname)
{
  bufAppendC('[');
  while(listextensionname != 0)
  {
    if (listextensionname->listextensionname_)
    {
      shExtensionName(listextensionname->extensionname_);
      bufAppendS(", ");
      listextensionname = listextensionname->listextensionname_;
    }
    else
    {
      shExtensionName(listextensionname->extensionname_);
      listextensionname = 0;
    }
  }
  bufAppendC(']');
}

void shListExtension(ListExtension listextension)
{
  bufAppendC('[');
  while(listextension != 0)
  {
    if (listextension->listextension_)
    {
      shExtension(listextension->extension_);
      bufAppendS(", ");
      listextension = listextension->listextension_;
    }
    else
    {
      shExtension(listextension->extension_);
      listextension = 0;
    }
  }
  bufAppendC(']');
}

void shDecl(Decl p)
{
  switch(p->kind)
  {
  case is_DeclFun:
    bufAppendC('(');

    bufAppendS("DeclFun");

    bufAppendC(' ');

    shListAnnotation(p->u.declFun_.listannotation_);
  bufAppendC(' ');
    shIdent(p->u.declFun_.stellaident_);
  bufAppendC(' ');
    shListParamDecl(p->u.declFun_.listparamdecl_);
  bufAppendC(' ');
    shReturnType(p->u.declFun_.returntype_);
  bufAppendC(' ');
    shThrowType(p->u.declFun_.throwtype_);
  bufAppendC(' ');
    shListDecl(p->u.declFun_.listdecl_);
  bufAppendC(' ');
    shExpr(p->u.declFun_.expr_);

    bufAppendC(')');

    break;
  case is_DeclFunGeneric:
    bufAppendC('(');

    bufAppendS("DeclFunGeneric");

    bufAppendC(' ');

    shListAnnotation(p->u.declFunGeneric_.listannotation_);
  bufAppendC(' ');
    shIdent(p->u.declFunGeneric_.stellaident_);
  bufAppendC(' ');
    shListStellaIdent(p->u.declFunGeneric_.liststellaident_);
  bufAppendC(' ');
    shListParamDecl(p->u.declFunGeneric_.listparamdecl_);
  bufAppendC(' ');
    shReturnType(p->u.declFunGeneric_.returntype_);
  bufAppendC(' ');
    shThrowType(p->u.declFunGeneric_.throwtype_);
  bufAppendC(' ');
    shListDecl(p->u.declFunGeneric_.listdecl_);
  bufAppendC(' ');
    shExpr(p->u.declFunGeneric_.expr_);

    bufAppendC(')');

    break;
  case is_DeclFunMod:
    bufAppendC('(');

    bufAppendS("DeclFunMod");

    bufAppendC(' ');

    shListAnnotation(p->u.declFunMod_.listannotation_);
  bufAppendC(' ');
    shMod(p->u.declFunMod_.mod_);
  bufAppendC(' ');
    shIdent(p->u.declFunMod_.stellaident_);
  bufAppendC(' ');
    shListParamDecl(p->u.declFunMod_.listparamdecl_);
  bufAppendC(' ');
    shReturnType(p->u.declFunMod_.returntype_);
  bufAppendC(' ');
    shThrowType(p->u.declFunMod_.throwtype_);
  bufAppendC(' ');
    shListDecl(p->u.declFunMod_.listdecl_);
  bufAppendC(' ');
    shExpr(p->u.declFunMod_.expr_);

    bufAppendC(')');

    break;
  case is_DeclTypeAlias:
    bufAppendC('(');

    bufAppendS("DeclTypeAlias");

    bufAppendC(' ');

    shIdent(p->u.declTypeAlias_.stellaident_);
  bufAppendC(' ');
    shType(p->u.declTypeAlias_.type_);

    bufAppendC(')');

    break;
  case is_DeclExceptionType:
    bufAppendC('(');

    bufAppendS("DeclExceptionType");

    bufAppendC(' ');

    shType(p->u.declExceptionType_.type_);

    bufAppendC(')');

    break;
  case is_DeclExceptionVariant:
    bufAppendC('(');

    bufAppendS("DeclExceptionVariant");

    bufAppendC(' ');

    shIdent(p->u.declExceptionVariant_.stellaident_);
  bufAppendC(' ');
    shType(p->u.declExceptionVariant_.type_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Decl!\n");
    exit(1);
  }
}

void shListDecl(ListDecl listdecl)
{
  bufAppendC('[');
  while(listdecl != 0)
  {
    if (listdecl->listdecl_)
    {
      shDecl(listdecl->decl_);
      bufAppendS(", ");
      listdecl = listdecl->listdecl_;
    }
    else
    {
      shDecl(listdecl->decl_);
      listdecl = 0;
    }
  }
  bufAppendC(']');
}

void shLocalDecl(LocalDecl p)
{
  switch(p->kind)
  {
  case is_ALocalDecl:
    bufAppendC('(');

    bufAppendS("ALocalDecl");

    bufAppendC(' ');

    shDecl(p->u.aLocalDecl_.decl_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing LocalDecl!\n");
    exit(1);
  }
}

void shListLocalDecl(ListLocalDecl listlocaldecl)
{
  bufAppendC('[');
  while(listlocaldecl != 0)
  {
    if (listlocaldecl->listlocaldecl_)
    {
      shLocalDecl(listlocaldecl->localdecl_);
      bufAppendS(", ");
      listlocaldecl = listlocaldecl->listlocaldecl_;
    }
    else
    {
      shLocalDecl(listlocaldecl->localdecl_);
      listlocaldecl = 0;
    }
  }
  bufAppendC(']');
}

void shAnnotation(Annotation p)
{
  switch(p->kind)
  {
  case is_InlineAnnotation:

    bufAppendS("InlineAnnotation");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Annotation!\n");
    exit(1);
  }
}

void shListAnnotation(ListAnnotation listannotation)
{
  bufAppendC('[');
  while(listannotation != 0)
  {
    if (listannotation->listannotation_)
    {
      shAnnotation(listannotation->annotation_);
      bufAppendS(", ");
      listannotation = listannotation->listannotation_;
    }
    else
    {
      shAnnotation(listannotation->annotation_);
      listannotation = 0;
    }
  }
  bufAppendC(']');
}

void shParamDecl(ParamDecl p)
{
  switch(p->kind)
  {
  case is_AParamDecl:
    bufAppendC('(');

    bufAppendS("AParamDecl");

    bufAppendC(' ');

    shIdent(p->u.aParamDecl_.stellaident_);
  bufAppendC(' ');
    shType(p->u.aParamDecl_.type_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ParamDecl!\n");
    exit(1);
  }
}

void shListParamDecl(ListParamDecl listparamdecl)
{
  bufAppendC('[');
  while(listparamdecl != 0)
  {
    if (listparamdecl->listparamdecl_)
    {
      shParamDecl(listparamdecl->paramdecl_);
      bufAppendS(", ");
      listparamdecl = listparamdecl->listparamdecl_;
    }
    else
    {
      shParamDecl(listparamdecl->paramdecl_);
      listparamdecl = 0;
    }
  }
  bufAppendC(']');
}

void shReturnType(ReturnType p)
{
  switch(p->kind)
  {
  case is_NoReturnType:

    bufAppendS("NoReturnType");




    break;
  case is_SomeReturnType:
    bufAppendC('(');

    bufAppendS("SomeReturnType");

    bufAppendC(' ');

    shType(p->u.someReturnType_.type_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ReturnType!\n");
    exit(1);
  }
}

void shThrowType(ThrowType p)
{
  switch(p->kind)
  {
  case is_NoThrowType:

    bufAppendS("NoThrowType");




    break;
  case is_SomeThrowType:
    bufAppendC('(');

    bufAppendS("SomeThrowType");

    bufAppendC(' ');

    shListType(p->u.someThrowType_.listtype_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ThrowType!\n");
    exit(1);
  }
}

void shType(Type p)
{
  switch(p->kind)
  {
  case is_TypeAuto:

    bufAppendS("TypeAuto");




    break;
  case is_TypeFun:
    bufAppendC('(');

    bufAppendS("TypeFun");

    bufAppendC(' ');

    shListType(p->u.typeFun_.listtype_);
  bufAppendC(' ');
    shType(p->u.typeFun_.type_);

    bufAppendC(')');

    break;
  case is_TypeForAll:
    bufAppendC('(');

    bufAppendS("TypeForAll");

    bufAppendC(' ');

    shListStellaIdent(p->u.typeForAll_.liststellaident_);
  bufAppendC(' ');
    shType(p->u.typeForAll_.type_);

    bufAppendC(')');

    break;
  case is_TypeRec:
    bufAppendC('(');

    bufAppendS("TypeRec");

    bufAppendC(' ');

    shIdent(p->u.typeRec_.stellaident_);
  bufAppendC(' ');
    shType(p->u.typeRec_.type_);

    bufAppendC(')');

    break;
  case is_TypeSum:
    bufAppendC('(');

    bufAppendS("TypeSum");

    bufAppendC(' ');

    shType(p->u.typeSum_.type_1);
  bufAppendC(' ');
    shType(p->u.typeSum_.type_2);

    bufAppendC(')');

    break;
  case is_TypeTuple:
    bufAppendC('(');

    bufAppendS("TypeTuple");

    bufAppendC(' ');

    shListType(p->u.typeTuple_.listtype_);

    bufAppendC(')');

    break;
  case is_TypeRecord:
    bufAppendC('(');

    bufAppendS("TypeRecord");

    bufAppendC(' ');

    shListRecordFieldType(p->u.typeRecord_.listrecordfieldtype_);

    bufAppendC(')');

    break;
  case is_TypeVariant:
    bufAppendC('(');

    bufAppendS("TypeVariant");

    bufAppendC(' ');

    shListVariantFieldType(p->u.typeVariant_.listvariantfieldtype_);

    bufAppendC(')');

    break;
  case is_TypeList:
    bufAppendC('(');

    bufAppendS("TypeList");

    bufAppendC(' ');

    shType(p->u.typeList_.type_);

    bufAppendC(')');

    break;
  case is_TypeBool:

    bufAppendS("TypeBool");




    break;
  case is_TypeNat:

    bufAppendS("TypeNat");




    break;
  case is_TypeUnit:

    bufAppendS("TypeUnit");




    break;
  case is_TypeTop:

    bufAppendS("TypeTop");




    break;
  case is_TypeBottom:

    bufAppendS("TypeBottom");




    break;
  case is_TypeRef:
    bufAppendC('(');

    bufAppendS("TypeRef");

    bufAppendC(' ');

    shType(p->u.typeRef_.type_);

    bufAppendC(')');

    break;
  case is_TypeVar:
    bufAppendC('(');

    bufAppendS("TypeVar");

    bufAppendC(' ');

    shIdent(p->u.typeVar_.stellaident_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Type!\n");
    exit(1);
  }
}

void shListType(ListType listtype)
{
  bufAppendC('[');
  while(listtype != 0)
  {
    if (listtype->listtype_)
    {
      shType(listtype->type_);
      bufAppendS(", ");
      listtype = listtype->listtype_;
    }
    else
    {
      shType(listtype->type_);
      listtype = 0;
    }
  }
  bufAppendC(']');
}

void shMatchCase(MatchCase p)
{
  switch(p->kind)
  {
  case is_AMatchCase:
    bufAppendC('(');

    bufAppendS("AMatchCase");

    bufAppendC(' ');

    shPattern(p->u.aMatchCase_.pattern_);
  bufAppendC(' ');
    shExpr(p->u.aMatchCase_.expr_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing MatchCase!\n");
    exit(1);
  }
}

void shListMatchCase(ListMatchCase listmatchcase)
{
  bufAppendC('[');
  while(listmatchcase != 0)
  {
    if (listmatchcase->listmatchcase_)
    {
      shMatchCase(listmatchcase->matchcase_);
      bufAppendS(", ");
      listmatchcase = listmatchcase->listmatchcase_;
    }
    else
    {
      shMatchCase(listmatchcase->matchcase_);
      listmatchcase = 0;
    }
  }
  bufAppendC(']');
}

void shOptionalTyping(OptionalTyping p)
{
  switch(p->kind)
  {
  case is_NoTyping:

    bufAppendS("NoTyping");




    break;
  case is_SomeTyping:
    bufAppendC('(');

    bufAppendS("SomeTyping");

    bufAppendC(' ');

    shType(p->u.someTyping_.type_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing OptionalTyping!\n");
    exit(1);
  }
}

void shPatternData(PatternData p)
{
  switch(p->kind)
  {
  case is_NoPatternData:

    bufAppendS("NoPatternData");




    break;
  case is_SomePatternData:
    bufAppendC('(');

    bufAppendS("SomePatternData");

    bufAppendC(' ');

    shPattern(p->u.somePatternData_.pattern_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing PatternData!\n");
    exit(1);
  }
}

void shExprData(ExprData p)
{
  switch(p->kind)
  {
  case is_NoExprData:

    bufAppendS("NoExprData");




    break;
  case is_SomeExprData:
    bufAppendC('(');

    bufAppendS("SomeExprData");

    bufAppendC(' ');

    shExpr(p->u.someExprData_.expr_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ExprData!\n");
    exit(1);
  }
}

void shPattern(Pattern p)
{
  switch(p->kind)
  {
  case is_PatternCastAs:
    bufAppendC('(');

    bufAppendS("PatternCastAs");

    bufAppendC(' ');

    shPattern(p->u.patternCastAs_.pattern_);
  bufAppendC(' ');
    shType(p->u.patternCastAs_.type_);

    bufAppendC(')');

    break;
  case is_PatternAsc:
    bufAppendC('(');

    bufAppendS("PatternAsc");

    bufAppendC(' ');

    shPattern(p->u.patternAsc_.pattern_);
  bufAppendC(' ');
    shType(p->u.patternAsc_.type_);

    bufAppendC(')');

    break;
  case is_PatternVariant:
    bufAppendC('(');

    bufAppendS("PatternVariant");

    bufAppendC(' ');

    shIdent(p->u.patternVariant_.stellaident_);
  bufAppendC(' ');
    shPatternData(p->u.patternVariant_.patterndata_);

    bufAppendC(')');

    break;
  case is_PatternInl:
    bufAppendC('(');

    bufAppendS("PatternInl");

    bufAppendC(' ');

    shPattern(p->u.patternInl_.pattern_);

    bufAppendC(')');

    break;
  case is_PatternInr:
    bufAppendC('(');

    bufAppendS("PatternInr");

    bufAppendC(' ');

    shPattern(p->u.patternInr_.pattern_);

    bufAppendC(')');

    break;
  case is_PatternTuple:
    bufAppendC('(');

    bufAppendS("PatternTuple");

    bufAppendC(' ');

    shListPattern(p->u.patternTuple_.listpattern_);

    bufAppendC(')');

    break;
  case is_PatternRecord:
    bufAppendC('(');

    bufAppendS("PatternRecord");

    bufAppendC(' ');

    shListLabelledPattern(p->u.patternRecord_.listlabelledpattern_);

    bufAppendC(')');

    break;
  case is_PatternList:
    bufAppendC('(');

    bufAppendS("PatternList");

    bufAppendC(' ');

    shListPattern(p->u.patternList_.listpattern_);

    bufAppendC(')');

    break;
  case is_PatternCons:
    bufAppendC('(');

    bufAppendS("PatternCons");

    bufAppendC(' ');

    shPattern(p->u.patternCons_.pattern_1);
  bufAppendC(' ');
    shPattern(p->u.patternCons_.pattern_2);

    bufAppendC(')');

    break;
  case is_PatternFalse:

    bufAppendS("PatternFalse");




    break;
  case is_PatternTrue:

    bufAppendS("PatternTrue");




    break;
  case is_PatternUnit:

    bufAppendS("PatternUnit");




    break;
  case is_PatternInt:
    bufAppendC('(');

    bufAppendS("PatternInt");

    bufAppendC(' ');

    shInteger(p->u.patternInt_.integer_);

    bufAppendC(')');

    break;
  case is_PatternSucc:
    bufAppendC('(');

    bufAppendS("PatternSucc");

    bufAppendC(' ');

    shPattern(p->u.patternSucc_.pattern_);

    bufAppendC(')');

    break;
  case is_PatternVar:
    bufAppendC('(');

    bufAppendS("PatternVar");

    bufAppendC(' ');

    shIdent(p->u.patternVar_.stellaident_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Pattern!\n");
    exit(1);
  }
}

void shListPattern(ListPattern listpattern)
{
  bufAppendC('[');
  while(listpattern != 0)
  {
    if (listpattern->listpattern_)
    {
      shPattern(listpattern->pattern_);
      bufAppendS(", ");
      listpattern = listpattern->listpattern_;
    }
    else
    {
      shPattern(listpattern->pattern_);
      listpattern = 0;
    }
  }
  bufAppendC(']');
}

void shLabelledPattern(LabelledPattern p)
{
  switch(p->kind)
  {
  case is_ALabelledPattern:
    bufAppendC('(');

    bufAppendS("ALabelledPattern");

    bufAppendC(' ');

    shIdent(p->u.aLabelledPattern_.stellaident_);
  bufAppendC(' ');
    shPattern(p->u.aLabelledPattern_.pattern_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing LabelledPattern!\n");
    exit(1);
  }
}

void shListLabelledPattern(ListLabelledPattern listlabelledpattern)
{
  bufAppendC('[');
  while(listlabelledpattern != 0)
  {
    if (listlabelledpattern->listlabelledpattern_)
    {
      shLabelledPattern(listlabelledpattern->labelledpattern_);
      bufAppendS(", ");
      listlabelledpattern = listlabelledpattern->listlabelledpattern_;
    }
    else
    {
      shLabelledPattern(listlabelledpattern->labelledpattern_);
      listlabelledpattern = 0;
    }
  }
  bufAppendC(']');
}

void shBinding(Binding p)
{
  switch(p->kind)
  {
  case is_ABinding:
    bufAppendC('(');

    bufAppendS("ABinding");

    bufAppendC(' ');

    shIdent(p->u.aBinding_.stellaident_);
  bufAppendC(' ');
    shExpr(p->u.aBinding_.expr_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Binding!\n");
    exit(1);
  }
}

void shListBinding(ListBinding listbinding)
{
  bufAppendC('[');
  while(listbinding != 0)
  {
    if (listbinding->listbinding_)
    {
      shBinding(listbinding->binding_);
      bufAppendS(", ");
      listbinding = listbinding->listbinding_;
    }
    else
    {
      shBinding(listbinding->binding_);
      listbinding = 0;
    }
  }
  bufAppendC(']');
}

void shExpr(Expr p)
{
  switch(p->kind)
  {
  case is_Sequence:
    bufAppendC('(');

    bufAppendS("Sequence");

    bufAppendC(' ');

    shExpr(p->u.sequence_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.sequence_.expr_2);

    bufAppendC(')');

    break;
  case is_Let:
    bufAppendC('(');

    bufAppendS("Let");

    bufAppendC(' ');

    shListPatternBinding(p->u.let_.listpatternbinding_);
  bufAppendC(' ');
    shExpr(p->u.let_.expr_);

    bufAppendC(')');

    break;
  case is_LetRec:
    bufAppendC('(');

    bufAppendS("LetRec");

    bufAppendC(' ');

    shListPatternBinding(p->u.letRec_.listpatternbinding_);
  bufAppendC(' ');
    shExpr(p->u.letRec_.expr_);

    bufAppendC(')');

    break;
  case is_TypeAbstraction:
    bufAppendC('(');

    bufAppendS("TypeAbstraction");

    bufAppendC(' ');

    shListStellaIdent(p->u.typeAbstraction_.liststellaident_);
  bufAppendC(' ');
    shExpr(p->u.typeAbstraction_.expr_);

    bufAppendC(')');

    break;
  case is_Assign:
    bufAppendC('(');

    bufAppendS("Assign");

    bufAppendC(' ');

    shExpr(p->u.assign_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.assign_.expr_2);

    bufAppendC(')');

    break;
  case is_If:
    bufAppendC('(');

    bufAppendS("If");

    bufAppendC(' ');

    shExpr(p->u.if_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.if_.expr_2);
  bufAppendC(' ');
    shExpr(p->u.if_.expr_3);

    bufAppendC(')');

    break;
  case is_LessThan:
    bufAppendC('(');

    bufAppendS("LessThan");

    bufAppendC(' ');

    shExpr(p->u.lessThan_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.lessThan_.expr_2);

    bufAppendC(')');

    break;
  case is_LessThanOrEqual:
    bufAppendC('(');

    bufAppendS("LessThanOrEqual");

    bufAppendC(' ');

    shExpr(p->u.lessThanOrEqual_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.lessThanOrEqual_.expr_2);

    bufAppendC(')');

    break;
  case is_GreaterThan:
    bufAppendC('(');

    bufAppendS("GreaterThan");

    bufAppendC(' ');

    shExpr(p->u.greaterThan_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.greaterThan_.expr_2);

    bufAppendC(')');

    break;
  case is_GreaterThanOrEqual:
    bufAppendC('(');

    bufAppendS("GreaterThanOrEqual");

    bufAppendC(' ');

    shExpr(p->u.greaterThanOrEqual_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.greaterThanOrEqual_.expr_2);

    bufAppendC(')');

    break;
  case is_Equal:
    bufAppendC('(');

    bufAppendS("Equal");

    bufAppendC(' ');

    shExpr(p->u.equal_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.equal_.expr_2);

    bufAppendC(')');

    break;
  case is_NotEqual:
    bufAppendC('(');

    bufAppendS("NotEqual");

    bufAppendC(' ');

    shExpr(p->u.notEqual_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.notEqual_.expr_2);

    bufAppendC(')');

    break;
  case is_TypeAsc:
    bufAppendC('(');

    bufAppendS("TypeAsc");

    bufAppendC(' ');

    shExpr(p->u.typeAsc_.expr_);
  bufAppendC(' ');
    shType(p->u.typeAsc_.type_);

    bufAppendC(')');

    break;
  case is_TypeCast:
    bufAppendC('(');

    bufAppendS("TypeCast");

    bufAppendC(' ');

    shExpr(p->u.typeCast_.expr_);
  bufAppendC(' ');
    shType(p->u.typeCast_.type_);

    bufAppendC(')');

    break;
  case is_Abstraction:
    bufAppendC('(');

    bufAppendS("Abstraction");

    bufAppendC(' ');

    shListParamDecl(p->u.abstraction_.listparamdecl_);
  bufAppendC(' ');
    shExpr(p->u.abstraction_.expr_);

    bufAppendC(')');

    break;
  case is_Mod:
    bufAppendC('(');

    bufAppendS("Mod");

    bufAppendC(' ');

    shMod(p->u.mod_.mod_);
  bufAppendC(' ');
    shExpr(p->u.mod_.expr_);

    bufAppendC(')');

    break;
  case is_Variant:
    bufAppendC('(');

    bufAppendS("Variant");

    bufAppendC(' ');

    shIdent(p->u.variant_.stellaident_);
  bufAppendC(' ');
    shExprData(p->u.variant_.exprdata_);

    bufAppendC(')');

    break;
  case is_Match:
    bufAppendC('(');

    bufAppendS("Match");

    bufAppendC(' ');

    shExpr(p->u.match_.expr_);
  bufAppendC(' ');
    shListMatchCase(p->u.match_.listmatchcase_);

    bufAppendC(')');

    break;
  case is_List:
    bufAppendC('(');

    bufAppendS("List");

    bufAppendC(' ');

    shListExpr(p->u.list_.listexpr_);

    bufAppendC(')');

    break;
  case is_Add:
    bufAppendC('(');

    bufAppendS("Add");

    bufAppendC(' ');

    shExpr(p->u.add_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.add_.expr_2);

    bufAppendC(')');

    break;
  case is_Subtract:
    bufAppendC('(');

    bufAppendS("Subtract");

    bufAppendC(' ');

    shExpr(p->u.subtract_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.subtract_.expr_2);

    bufAppendC(')');

    break;
  case is_LogicOr:
    bufAppendC('(');

    bufAppendS("LogicOr");

    bufAppendC(' ');

    shExpr(p->u.logicOr_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.logicOr_.expr_2);

    bufAppendC(')');

    break;
  case is_Multiply:
    bufAppendC('(');

    bufAppendS("Multiply");

    bufAppendC(' ');

    shExpr(p->u.multiply_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.multiply_.expr_2);

    bufAppendC(')');

    break;
  case is_Divide:
    bufAppendC('(');

    bufAppendS("Divide");

    bufAppendC(' ');

    shExpr(p->u.divide_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.divide_.expr_2);

    bufAppendC(')');

    break;
  case is_LogicAnd:
    bufAppendC('(');

    bufAppendS("LogicAnd");

    bufAppendC(' ');

    shExpr(p->u.logicAnd_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.logicAnd_.expr_2);

    bufAppendC(')');

    break;
  case is_Ref:
    bufAppendC('(');

    bufAppendS("Ref");

    bufAppendC(' ');

    shExpr(p->u.ref_.expr_);

    bufAppendC(')');

    break;
  case is_Deref:
    bufAppendC('(');

    bufAppendS("Deref");

    bufAppendC(' ');

    shExpr(p->u.deref_.expr_);

    bufAppendC(')');

    break;
  case is_Application:
    bufAppendC('(');

    bufAppendS("Application");

    bufAppendC(' ');

    shExpr(p->u.application_.expr_);
  bufAppendC(' ');
    shListExpr(p->u.application_.listexpr_);

    bufAppendC(')');

    break;
  case is_TypeApplication:
    bufAppendC('(');

    bufAppendS("TypeApplication");

    bufAppendC(' ');

    shExpr(p->u.typeApplication_.expr_);
  bufAppendC(' ');
    shListType(p->u.typeApplication_.listtype_);

    bufAppendC(')');

    break;
  case is_DotRecord:
    bufAppendC('(');

    bufAppendS("DotRecord");

    bufAppendC(' ');

    shExpr(p->u.dotRecord_.expr_);
  bufAppendC(' ');
    shIdent(p->u.dotRecord_.stellaident_);

    bufAppendC(')');

    break;
  case is_DotTuple:
    bufAppendC('(');

    bufAppendS("DotTuple");

    bufAppendC(' ');

    shExpr(p->u.dotTuple_.expr_);
  bufAppendC(' ');
    shInteger(p->u.dotTuple_.integer_);

    bufAppendC(')');

    break;
  case is_Tuple:
    bufAppendC('(');

    bufAppendS("Tuple");

    bufAppendC(' ');

    shListExpr(p->u.tuple_.listexpr_);

    bufAppendC(')');

    break;
  case is_Record:
    bufAppendC('(');

    bufAppendS("Record");

    bufAppendC(' ');

    shListBinding(p->u.record_.listbinding_);

    bufAppendC(')');

    break;
  case is_ConsList:
    bufAppendC('(');

    bufAppendS("ConsList");

    bufAppendC(' ');

    shExpr(p->u.consList_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.consList_.expr_2);

    bufAppendC(')');

    break;
  case is_Head:
    bufAppendC('(');

    bufAppendS("Head");

    bufAppendC(' ');

    shExpr(p->u.head_.expr_);

    bufAppendC(')');

    break;
  case is_IsEmpty:
    bufAppendC('(');

    bufAppendS("IsEmpty");

    bufAppendC(' ');

    shExpr(p->u.isEmpty_.expr_);

    bufAppendC(')');

    break;
  case is_Tail:
    bufAppendC('(');

    bufAppendS("Tail");

    bufAppendC(' ');

    shExpr(p->u.tail_.expr_);

    bufAppendC(')');

    break;
  case is_Panic:

    bufAppendS("Panic");




    break;
  case is_Throw:
    bufAppendC('(');

    bufAppendS("Throw");

    bufAppendC(' ');

    shExpr(p->u.throw_.expr_);

    bufAppendC(')');

    break;
  case is_TryCatch:
    bufAppendC('(');

    bufAppendS("TryCatch");

    bufAppendC(' ');

    shExpr(p->u.tryCatch_.expr_1);
  bufAppendC(' ');
    shPattern(p->u.tryCatch_.pattern_);
  bufAppendC(' ');
    shExpr(p->u.tryCatch_.expr_2);

    bufAppendC(')');

    break;
  case is_TryWith:
    bufAppendC('(');

    bufAppendS("TryWith");

    bufAppendC(' ');

    shExpr(p->u.tryWith_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.tryWith_.expr_2);

    bufAppendC(')');

    break;
  case is_TryCastAs:
    bufAppendC('(');

    bufAppendS("TryCastAs");

    bufAppendC(' ');

    shExpr(p->u.tryCastAs_.expr_1);
  bufAppendC(' ');
    shType(p->u.tryCastAs_.type_);
  bufAppendC(' ');
    shPattern(p->u.tryCastAs_.pattern_);
  bufAppendC(' ');
    shExpr(p->u.tryCastAs_.expr_2);
  bufAppendC(' ');
    shExpr(p->u.tryCastAs_.expr_3);

    bufAppendC(')');

    break;
  case is_Inl:
    bufAppendC('(');

    bufAppendS("Inl");

    bufAppendC(' ');

    shExpr(p->u.inl_.expr_);

    bufAppendC(')');

    break;
  case is_Inr:
    bufAppendC('(');

    bufAppendS("Inr");

    bufAppendC(' ');

    shExpr(p->u.inr_.expr_);

    bufAppendC(')');

    break;
  case is_Succ:
    bufAppendC('(');

    bufAppendS("Succ");

    bufAppendC(' ');

    shExpr(p->u.succ_.expr_);

    bufAppendC(')');

    break;
  case is_LogicNot:
    bufAppendC('(');

    bufAppendS("LogicNot");

    bufAppendC(' ');

    shExpr(p->u.logicNot_.expr_);

    bufAppendC(')');

    break;
  case is_Pred:
    bufAppendC('(');

    bufAppendS("Pred");

    bufAppendC(' ');

    shExpr(p->u.pred_.expr_);

    bufAppendC(')');

    break;
  case is_IsZero:
    bufAppendC('(');

    bufAppendS("IsZero");

    bufAppendC(' ');

    shExpr(p->u.isZero_.expr_);

    bufAppendC(')');

    break;
  case is_Fix:
    bufAppendC('(');

    bufAppendS("Fix");

    bufAppendC(' ');

    shExpr(p->u.fix_.expr_);

    bufAppendC(')');

    break;
  case is_NatRec:
    bufAppendC('(');

    bufAppendS("NatRec");

    bufAppendC(' ');

    shExpr(p->u.natRec_.expr_1);
  bufAppendC(' ');
    shExpr(p->u.natRec_.expr_2);
  bufAppendC(' ');
    shExpr(p->u.natRec_.expr_3);

    bufAppendC(')');

    break;
  case is_Fold:
    bufAppendC('(');

    bufAppendS("Fold");

    bufAppendC(' ');

    shType(p->u.fold_.type_);
  bufAppendC(' ');
    shExpr(p->u.fold_.expr_);

    bufAppendC(')');

    break;
  case is_Unfold:
    bufAppendC('(');

    bufAppendS("Unfold");

    bufAppendC(' ');

    shType(p->u.unfold_.type_);
  bufAppendC(' ');
    shExpr(p->u.unfold_.expr_);

    bufAppendC(')');

    break;
  case is_ConstTrue:

    bufAppendS("ConstTrue");




    break;
  case is_ConstFalse:

    bufAppendS("ConstFalse");




    break;
  case is_ConstUnit:

    bufAppendS("ConstUnit");




    break;
  case is_ConstInt:
    bufAppendC('(');

    bufAppendS("ConstInt");

    bufAppendC(' ');

    shInteger(p->u.constInt_.integer_);

    bufAppendC(')');

    break;
  case is_ConstMemory:
    bufAppendC('(');

    bufAppendS("ConstMemory");

    bufAppendC(' ');

    shIdent(p->u.constMemory_.memoryaddress_);

    bufAppendC(')');

    break;
  case is_Var:
    bufAppendC('(');

    bufAppendS("Var");

    bufAppendC(' ');

    shIdent(p->u.var_.stellaident_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Expr!\n");
    exit(1);
  }
}

void shListExpr(ListExpr listexpr)
{
  bufAppendC('[');
  while(listexpr != 0)
  {
    if (listexpr->listexpr_)
    {
      shExpr(listexpr->expr_);
      bufAppendS(", ");
      listexpr = listexpr->listexpr_;
    }
    else
    {
      shExpr(listexpr->expr_);
      listexpr = 0;
    }
  }
  bufAppendC(']');
}

void shPatternBinding(PatternBinding p)
{
  switch(p->kind)
  {
  case is_APatternBinding:
    bufAppendC('(');

    bufAppendS("APatternBinding");

    bufAppendC(' ');

    shPattern(p->u.aPatternBinding_.pattern_);
  bufAppendC(' ');
    shExpr(p->u.aPatternBinding_.expr_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing PatternBinding!\n");
    exit(1);
  }
}

void shListPatternBinding(ListPatternBinding listpatternbinding)
{
  bufAppendC('[');
  while(listpatternbinding != 0)
  {
    if (listpatternbinding->listpatternbinding_)
    {
      shPatternBinding(listpatternbinding->patternbinding_);
      bufAppendS(", ");
      listpatternbinding = listpatternbinding->listpatternbinding_;
    }
    else
    {
      shPatternBinding(listpatternbinding->patternbinding_);
      listpatternbinding = 0;
    }
  }
  bufAppendC(']');
}

void shMod(Mod p)
{
  switch(p->kind)
  {
  case is_ModLock:

    bufAppendS("ModLock");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Mod!\n");
    exit(1);
  }
}

void shVariantFieldType(VariantFieldType p)
{
  switch(p->kind)
  {
  case is_AVariantFieldType:
    bufAppendC('(');

    bufAppendS("AVariantFieldType");

    bufAppendC(' ');

    shIdent(p->u.aVariantFieldType_.stellaident_);
  bufAppendC(' ');
    shOptionalTyping(p->u.aVariantFieldType_.optionaltyping_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing VariantFieldType!\n");
    exit(1);
  }
}

void shListVariantFieldType(ListVariantFieldType listvariantfieldtype)
{
  bufAppendC('[');
  while(listvariantfieldtype != 0)
  {
    if (listvariantfieldtype->listvariantfieldtype_)
    {
      shVariantFieldType(listvariantfieldtype->variantfieldtype_);
      bufAppendS(", ");
      listvariantfieldtype = listvariantfieldtype->listvariantfieldtype_;
    }
    else
    {
      shVariantFieldType(listvariantfieldtype->variantfieldtype_);
      listvariantfieldtype = 0;
    }
  }
  bufAppendC(']');
}

void shRecordFieldType(RecordFieldType p)
{
  switch(p->kind)
  {
  case is_ARecordFieldType:
    bufAppendC('(');

    bufAppendS("ARecordFieldType");

    bufAppendC(' ');

    shIdent(p->u.aRecordFieldType_.stellaident_);
  bufAppendC(' ');
    shType(p->u.aRecordFieldType_.type_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing RecordFieldType!\n");
    exit(1);
  }
}

void shListRecordFieldType(ListRecordFieldType listrecordfieldtype)
{
  bufAppendC('[');
  while(listrecordfieldtype != 0)
  {
    if (listrecordfieldtype->listrecordfieldtype_)
    {
      shRecordFieldType(listrecordfieldtype->recordfieldtype_);
      bufAppendS(", ");
      listrecordfieldtype = listrecordfieldtype->listrecordfieldtype_;
    }
    else
    {
      shRecordFieldType(listrecordfieldtype->recordfieldtype_);
      listrecordfieldtype = 0;
    }
  }
  bufAppendC(']');
}

void shTyping(Typing p)
{
  switch(p->kind)
  {
  case is_ATyping:
    bufAppendC('(');

    bufAppendS("ATyping");

    bufAppendC(' ');

    shExpr(p->u.aTyping_.expr_);
  bufAppendC(' ');
    shType(p->u.aTyping_.type_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Typing!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void shStellaIdent(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void shExtensionName(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void shMemoryAddress(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

