/* File generated by the BNF Converter (bnfc 2.9.7). */

#ifndef PRINTER_HEADER
#define PRINTER_HEADER

#include "Absyn.h"

/* Certain applications may improve performance by changing the buffer size */
#define BUFFER_INITIAL 2048
/* You may wish to change _L_PAREN or _R_PAREN */
#define _L_PAREN '('
#define _R_PAREN ')'

/* The following are simple heuristics for rendering terminals */
/* You may wish to change them */
void renderCC(Char c);
void renderCS(String s);
void indent(void);
void backup(void);
void onEmptyLine(void);
void removeTrailingSpaces(void);
void removeTrailingWhitespace(void);


char *printProgram(Program p);
char *printListStellaIdent(ListStellaIdent p);
char *printLanguageDecl(LanguageDecl p);
char *printExtension(Extension p);
char *printListExtensionName(ListExtensionName p);
char *printListExtension(ListExtension p);
char *printDecl(Decl p);
char *printListDecl(ListDecl p);
char *printLocalDecl(LocalDecl p);
char *printListLocalDecl(ListLocalDecl p);
char *printAnnotation(Annotation p);
char *printListAnnotation(ListAnnotation p);
char *printParamDecl(ParamDecl p);
char *printListParamDecl(ListParamDecl p);
char *printReturnType(ReturnType p);
char *printThrowType(ThrowType p);
char *printType(Type p);
char *printListType(ListType p);
char *printMatchCase(MatchCase p);
char *printListMatchCase(ListMatchCase p);
char *printOptionalTyping(OptionalTyping p);
char *printPatternData(PatternData p);
char *printExprData(ExprData p);
char *printPattern(Pattern p);
char *printListPattern(ListPattern p);
char *printLabelledPattern(LabelledPattern p);
char *printListLabelledPattern(ListLabelledPattern p);
char *printBinding(Binding p);
char *printListBinding(ListBinding p);
char *printExpr(Expr p);
char *printListExpr(ListExpr p);
char *printPatternBinding(PatternBinding p);
char *printListPatternBinding(ListPatternBinding p);
char *printLabelledEffect(LabelledEffect p);
char *printListLabelledEffect(ListLabelledEffect p);
char *printModality(Modality p);
char *printListModality(ListModality p);
char *printHandler(Handler p);
char *printListHandler(ListHandler p);
char *printVariantFieldType(VariantFieldType p);
char *printListVariantFieldType(ListVariantFieldType p);
char *printRecordFieldType(RecordFieldType p);
char *printListRecordFieldType(ListRecordFieldType p);
char *printTyping(Typing p);

void ppProgram(Program p, int i);
void ppListStellaIdent(ListStellaIdent p, int i);
void ppLanguageDecl(LanguageDecl p, int i);
void ppExtension(Extension p, int i);
void ppListExtensionName(ListExtensionName p, int i);
void ppListExtension(ListExtension p, int i);
void ppDecl(Decl p, int i);
void ppListDecl(ListDecl p, int i);
void ppLocalDecl(LocalDecl p, int i);
void ppListLocalDecl(ListLocalDecl p, int i);
void ppAnnotation(Annotation p, int i);
void ppListAnnotation(ListAnnotation p, int i);
void ppParamDecl(ParamDecl p, int i);
void ppListParamDecl(ListParamDecl p, int i);
void ppReturnType(ReturnType p, int i);
void ppThrowType(ThrowType p, int i);
void ppType(Type p, int i);
void ppListType(ListType p, int i);
void ppMatchCase(MatchCase p, int i);
void ppListMatchCase(ListMatchCase p, int i);
void ppOptionalTyping(OptionalTyping p, int i);
void ppPatternData(PatternData p, int i);
void ppExprData(ExprData p, int i);
void ppPattern(Pattern p, int i);
void ppListPattern(ListPattern p, int i);
void ppLabelledPattern(LabelledPattern p, int i);
void ppListLabelledPattern(ListLabelledPattern p, int i);
void ppBinding(Binding p, int i);
void ppListBinding(ListBinding p, int i);
void ppExpr(Expr p, int i);
void ppListExpr(ListExpr p, int i);
void ppPatternBinding(PatternBinding p, int i);
void ppListPatternBinding(ListPatternBinding p, int i);
void ppLabelledEffect(LabelledEffect p, int i);
void ppListLabelledEffect(ListLabelledEffect p, int i);
void ppModality(Modality p, int i);
void ppListModality(ListModality p, int i);
void ppHandler(Handler p, int i);
void ppListHandler(ListHandler p, int i);
void ppVariantFieldType(VariantFieldType p, int i);
void ppListVariantFieldType(ListVariantFieldType p, int i);
void ppRecordFieldType(RecordFieldType p, int i);
void ppListRecordFieldType(ListRecordFieldType p, int i);
void ppTyping(Typing p, int i);

char *showProgram(Program p);
char *showListStellaIdent(ListStellaIdent p);
char *showLanguageDecl(LanguageDecl p);
char *showExtension(Extension p);
char *showListExtensionName(ListExtensionName p);
char *showListExtension(ListExtension p);
char *showDecl(Decl p);
char *showListDecl(ListDecl p);
char *showLocalDecl(LocalDecl p);
char *showListLocalDecl(ListLocalDecl p);
char *showAnnotation(Annotation p);
char *showListAnnotation(ListAnnotation p);
char *showParamDecl(ParamDecl p);
char *showListParamDecl(ListParamDecl p);
char *showReturnType(ReturnType p);
char *showThrowType(ThrowType p);
char *showType(Type p);
char *showListType(ListType p);
char *showMatchCase(MatchCase p);
char *showListMatchCase(ListMatchCase p);
char *showOptionalTyping(OptionalTyping p);
char *showPatternData(PatternData p);
char *showExprData(ExprData p);
char *showPattern(Pattern p);
char *showListPattern(ListPattern p);
char *showLabelledPattern(LabelledPattern p);
char *showListLabelledPattern(ListLabelledPattern p);
char *showBinding(Binding p);
char *showListBinding(ListBinding p);
char *showExpr(Expr p);
char *showListExpr(ListExpr p);
char *showPatternBinding(PatternBinding p);
char *showListPatternBinding(ListPatternBinding p);
char *showLabelledEffect(LabelledEffect p);
char *showListLabelledEffect(ListLabelledEffect p);
char *showModality(Modality p);
char *showListModality(ListModality p);
char *showHandler(Handler p);
char *showListHandler(ListHandler p);
char *showVariantFieldType(VariantFieldType p);
char *showListVariantFieldType(ListVariantFieldType p);
char *showRecordFieldType(RecordFieldType p);
char *showListRecordFieldType(ListRecordFieldType p);
char *showTyping(Typing p);

void shProgram(Program p);
void shListStellaIdent(ListStellaIdent p);
void shLanguageDecl(LanguageDecl p);
void shExtension(Extension p);
void shListExtensionName(ListExtensionName p);
void shListExtension(ListExtension p);
void shDecl(Decl p);
void shListDecl(ListDecl p);
void shLocalDecl(LocalDecl p);
void shListLocalDecl(ListLocalDecl p);
void shAnnotation(Annotation p);
void shListAnnotation(ListAnnotation p);
void shParamDecl(ParamDecl p);
void shListParamDecl(ListParamDecl p);
void shReturnType(ReturnType p);
void shThrowType(ThrowType p);
void shType(Type p);
void shListType(ListType p);
void shMatchCase(MatchCase p);
void shListMatchCase(ListMatchCase p);
void shOptionalTyping(OptionalTyping p);
void shPatternData(PatternData p);
void shExprData(ExprData p);
void shPattern(Pattern p);
void shListPattern(ListPattern p);
void shLabelledPattern(LabelledPattern p);
void shListLabelledPattern(ListLabelledPattern p);
void shBinding(Binding p);
void shListBinding(ListBinding p);
void shExpr(Expr p);
void shListExpr(ListExpr p);
void shPatternBinding(PatternBinding p);
void shListPatternBinding(ListPatternBinding p);
void shLabelledEffect(LabelledEffect p);
void shListLabelledEffect(ListLabelledEffect p);
void shModality(Modality p);
void shListModality(ListModality p);
void shHandler(Handler p);
void shListHandler(ListHandler p);
void shVariantFieldType(VariantFieldType p);
void shListVariantFieldType(ListVariantFieldType p);
void shRecordFieldType(RecordFieldType p);
void shListRecordFieldType(ListRecordFieldType p);
void shTyping(Typing p);

void ppStellaIdent(String s, int i);
void ppExtensionName(String s, int i);
void ppMemoryAddress(String s, int i);
void shStellaIdent(String s);
void shExtensionName(String s);
void shMemoryAddress(String s);
void ppInteger(Integer n, int i);
void ppDouble(Double d, int i);
void ppChar(Char c, int i);
void ppString(String s, int i);
void ppIdent(String s, int i);
void shInteger(Integer n);
void shDouble(Double d);
void shChar(Char c);
void shString(String s);
void shIdent(String s);
void bufEscapeS(const char *s);
void bufEscapeC(const char c);
void bufAppendS(const char *s);
void bufAppendC(const char c);
void bufReset(void);
void resizeBuffer(void);

#endif

