/* File generated by the BNF Converter (bnfc 2.9.7). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitProgram(Program p)
{
  switch(p->kind)
  {
  case is_AProgram:
    /* Code for AProgram Goes Here */
    visitLanguageDecl(p->u.aProgram_.languagedecl_);
    visitListExtension(p->u.aProgram_.listextension_);
    visitListDecl(p->u.aProgram_.listdecl_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Program!\n");
    exit(1);
  }
}

void visitListStellaIdent(ListStellaIdent liststellaident)
{
  while(liststellaident  != 0)
  {
    /* Code For ListStellaIdent Goes Here */
    visitStellaIdent(liststellaident->stellaident_);
    liststellaident = liststellaident->liststellaident_;
  }
}

void visitLanguageDecl(LanguageDecl p)
{
  switch(p->kind)
  {
  case is_LanguageCore:
    /* Code for LanguageCore Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing LanguageDecl!\n");
    exit(1);
  }
}

void visitExtension(Extension p)
{
  switch(p->kind)
  {
  case is_AnExtension:
    /* Code for AnExtension Goes Here */
    visitListExtensionName(p->u.anExtension_.listextensionname_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Extension!\n");
    exit(1);
  }
}

void visitListExtensionName(ListExtensionName listextensionname)
{
  while(listextensionname  != 0)
  {
    /* Code For ListExtensionName Goes Here */
    visitExtensionName(listextensionname->extensionname_);
    listextensionname = listextensionname->listextensionname_;
  }
}

void visitListExtension(ListExtension listextension)
{
  while(listextension  != 0)
  {
    /* Code For ListExtension Goes Here */
    visitExtension(listextension->extension_);
    listextension = listextension->listextension_;
  }
}

void visitDecl(Decl p)
{
  switch(p->kind)
  {
  case is_DeclFun:
    /* Code for DeclFun Goes Here */
    visitListAnnotation(p->u.declFun_.listannotation_);
    visitStellaIdent(p->u.declFun_.stellaident_);
    visitListParamDecl(p->u.declFun_.listparamdecl_);
    visitReturnType(p->u.declFun_.returntype_);
    visitThrowType(p->u.declFun_.throwtype_);
    visitListDecl(p->u.declFun_.listdecl_);
    visitExpr(p->u.declFun_.expr_);
    break;
  case is_DeclFunGeneric:
    /* Code for DeclFunGeneric Goes Here */
    visitListAnnotation(p->u.declFunGeneric_.listannotation_);
    visitStellaIdent(p->u.declFunGeneric_.stellaident_);
    visitListStellaIdent(p->u.declFunGeneric_.liststellaident_);
    visitListParamDecl(p->u.declFunGeneric_.listparamdecl_);
    visitReturnType(p->u.declFunGeneric_.returntype_);
    visitThrowType(p->u.declFunGeneric_.throwtype_);
    visitListDecl(p->u.declFunGeneric_.listdecl_);
    visitExpr(p->u.declFunGeneric_.expr_);
    break;
  case is_DeclFunMod:
    /* Code for DeclFunMod Goes Here */
    visitListAnnotation(p->u.declFunMod_.listannotation_);
    visitListModality(p->u.declFunMod_.listmodality_);
    visitStellaIdent(p->u.declFunMod_.stellaident_);
    visitListParamDecl(p->u.declFunMod_.listparamdecl_);
    visitReturnType(p->u.declFunMod_.returntype_);
    visitThrowType(p->u.declFunMod_.throwtype_);
    visitListDecl(p->u.declFunMod_.listdecl_);
    visitExpr(p->u.declFunMod_.expr_);
    break;
  case is_DeclTypeAlias:
    /* Code for DeclTypeAlias Goes Here */
    visitStellaIdent(p->u.declTypeAlias_.stellaident_);
    visitType(p->u.declTypeAlias_.type_);
    break;
  case is_DeclExceptionType:
    /* Code for DeclExceptionType Goes Here */
    visitType(p->u.declExceptionType_.type_);
    break;
  case is_DeclExceptionVariant:
    /* Code for DeclExceptionVariant Goes Here */
    visitStellaIdent(p->u.declExceptionVariant_.stellaident_);
    visitType(p->u.declExceptionVariant_.type_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Decl!\n");
    exit(1);
  }
}

void visitListDecl(ListDecl listdecl)
{
  while(listdecl  != 0)
  {
    /* Code For ListDecl Goes Here */
    visitDecl(listdecl->decl_);
    listdecl = listdecl->listdecl_;
  }
}

void visitLocalDecl(LocalDecl p)
{
  switch(p->kind)
  {
  case is_ALocalDecl:
    /* Code for ALocalDecl Goes Here */
    visitDecl(p->u.aLocalDecl_.decl_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing LocalDecl!\n");
    exit(1);
  }
}

void visitListLocalDecl(ListLocalDecl listlocaldecl)
{
  while(listlocaldecl  != 0)
  {
    /* Code For ListLocalDecl Goes Here */
    visitLocalDecl(listlocaldecl->localdecl_);
    listlocaldecl = listlocaldecl->listlocaldecl_;
  }
}

void visitAnnotation(Annotation p)
{
  switch(p->kind)
  {
  case is_InlineAnnotation:
    /* Code for InlineAnnotation Goes Here */
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Annotation!\n");
    exit(1);
  }
}

void visitListAnnotation(ListAnnotation listannotation)
{
  while(listannotation  != 0)
  {
    /* Code For ListAnnotation Goes Here */
    visitAnnotation(listannotation->annotation_);
    listannotation = listannotation->listannotation_;
  }
}

void visitParamDecl(ParamDecl p)
{
  switch(p->kind)
  {
  case is_AParamDecl:
    /* Code for AParamDecl Goes Here */
    visitStellaIdent(p->u.aParamDecl_.stellaident_);
    visitType(p->u.aParamDecl_.type_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ParamDecl!\n");
    exit(1);
  }
}

void visitListParamDecl(ListParamDecl listparamdecl)
{
  while(listparamdecl  != 0)
  {
    /* Code For ListParamDecl Goes Here */
    visitParamDecl(listparamdecl->paramdecl_);
    listparamdecl = listparamdecl->listparamdecl_;
  }
}

void visitReturnType(ReturnType p)
{
  switch(p->kind)
  {
  case is_NoReturnType:
    /* Code for NoReturnType Goes Here */
    break;
  case is_SomeReturnType:
    /* Code for SomeReturnType Goes Here */
    visitType(p->u.someReturnType_.type_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ReturnType!\n");
    exit(1);
  }
}

void visitThrowType(ThrowType p)
{
  switch(p->kind)
  {
  case is_NoThrowType:
    /* Code for NoThrowType Goes Here */
    break;
  case is_SomeThrowType:
    /* Code for SomeThrowType Goes Here */
    visitListType(p->u.someThrowType_.listtype_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ThrowType!\n");
    exit(1);
  }
}

void visitType(Type p)
{
  switch(p->kind)
  {
  case is_TypeMod:
    /* Code for TypeMod Goes Here */
    visitModality(p->u.typeMod_.modality_);
    visitType(p->u.typeMod_.type_);
    break;
  case is_TypeAuto:
    /* Code for TypeAuto Goes Here */
    break;
  case is_TypeFun:
    /* Code for TypeFun Goes Here */
    visitListType(p->u.typeFun_.listtype_);
    visitType(p->u.typeFun_.type_);
    break;
  case is_TypeForAll:
    /* Code for TypeForAll Goes Here */
    visitListStellaIdent(p->u.typeForAll_.liststellaident_);
    visitType(p->u.typeForAll_.type_);
    break;
  case is_TypeRec:
    /* Code for TypeRec Goes Here */
    visitStellaIdent(p->u.typeRec_.stellaident_);
    visitType(p->u.typeRec_.type_);
    break;
  case is_TypeSum:
    /* Code for TypeSum Goes Here */
    visitType(p->u.typeSum_.type_1);
    visitType(p->u.typeSum_.type_2);
    break;
  case is_TypeTuple:
    /* Code for TypeTuple Goes Here */
    visitListType(p->u.typeTuple_.listtype_);
    break;
  case is_TypeRecord:
    /* Code for TypeRecord Goes Here */
    visitListRecordFieldType(p->u.typeRecord_.listrecordfieldtype_);
    break;
  case is_TypeVariant:
    /* Code for TypeVariant Goes Here */
    visitListVariantFieldType(p->u.typeVariant_.listvariantfieldtype_);
    break;
  case is_TypeList:
    /* Code for TypeList Goes Here */
    visitType(p->u.typeList_.type_);
    break;
  case is_TypeBool:
    /* Code for TypeBool Goes Here */
    break;
  case is_TypeNat:
    /* Code for TypeNat Goes Here */
    break;
  case is_TypeUnit:
    /* Code for TypeUnit Goes Here */
    break;
  case is_TypeTop:
    /* Code for TypeTop Goes Here */
    break;
  case is_TypeBottom:
    /* Code for TypeBottom Goes Here */
    break;
  case is_TypeRef:
    /* Code for TypeRef Goes Here */
    visitType(p->u.typeRef_.type_);
    break;
  case is_TypeVar:
    /* Code for TypeVar Goes Here */
    visitStellaIdent(p->u.typeVar_.stellaident_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Type!\n");
    exit(1);
  }
}

void visitListType(ListType listtype)
{
  while(listtype  != 0)
  {
    /* Code For ListType Goes Here */
    visitType(listtype->type_);
    listtype = listtype->listtype_;
  }
}

void visitMatchCase(MatchCase p)
{
  switch(p->kind)
  {
  case is_AMatchCase:
    /* Code for AMatchCase Goes Here */
    visitPattern(p->u.aMatchCase_.pattern_);
    visitExpr(p->u.aMatchCase_.expr_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing MatchCase!\n");
    exit(1);
  }
}

void visitListMatchCase(ListMatchCase listmatchcase)
{
  while(listmatchcase  != 0)
  {
    /* Code For ListMatchCase Goes Here */
    visitMatchCase(listmatchcase->matchcase_);
    listmatchcase = listmatchcase->listmatchcase_;
  }
}

void visitOptionalTyping(OptionalTyping p)
{
  switch(p->kind)
  {
  case is_NoTyping:
    /* Code for NoTyping Goes Here */
    break;
  case is_SomeTyping:
    /* Code for SomeTyping Goes Here */
    visitType(p->u.someTyping_.type_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptionalTyping!\n");
    exit(1);
  }
}

void visitPatternData(PatternData p)
{
  switch(p->kind)
  {
  case is_NoPatternData:
    /* Code for NoPatternData Goes Here */
    break;
  case is_SomePatternData:
    /* Code for SomePatternData Goes Here */
    visitPattern(p->u.somePatternData_.pattern_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing PatternData!\n");
    exit(1);
  }
}

void visitExprData(ExprData p)
{
  switch(p->kind)
  {
  case is_NoExprData:
    /* Code for NoExprData Goes Here */
    break;
  case is_SomeExprData:
    /* Code for SomeExprData Goes Here */
    visitExpr(p->u.someExprData_.expr_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ExprData!\n");
    exit(1);
  }
}

void visitPattern(Pattern p)
{
  switch(p->kind)
  {
  case is_PatternCastAs:
    /* Code for PatternCastAs Goes Here */
    visitPattern(p->u.patternCastAs_.pattern_);
    visitType(p->u.patternCastAs_.type_);
    break;
  case is_PatternAsc:
    /* Code for PatternAsc Goes Here */
    visitPattern(p->u.patternAsc_.pattern_);
    visitType(p->u.patternAsc_.type_);
    break;
  case is_PatternVariant:
    /* Code for PatternVariant Goes Here */
    visitStellaIdent(p->u.patternVariant_.stellaident_);
    visitPatternData(p->u.patternVariant_.patterndata_);
    break;
  case is_PatternInl:
    /* Code for PatternInl Goes Here */
    visitPattern(p->u.patternInl_.pattern_);
    break;
  case is_PatternInr:
    /* Code for PatternInr Goes Here */
    visitPattern(p->u.patternInr_.pattern_);
    break;
  case is_PatternTuple:
    /* Code for PatternTuple Goes Here */
    visitListPattern(p->u.patternTuple_.listpattern_);
    break;
  case is_PatternRecord:
    /* Code for PatternRecord Goes Here */
    visitListLabelledPattern(p->u.patternRecord_.listlabelledpattern_);
    break;
  case is_PatternList:
    /* Code for PatternList Goes Here */
    visitListPattern(p->u.patternList_.listpattern_);
    break;
  case is_PatternCons:
    /* Code for PatternCons Goes Here */
    visitPattern(p->u.patternCons_.pattern_1);
    visitPattern(p->u.patternCons_.pattern_2);
    break;
  case is_PatternFalse:
    /* Code for PatternFalse Goes Here */
    break;
  case is_PatternTrue:
    /* Code for PatternTrue Goes Here */
    break;
  case is_PatternUnit:
    /* Code for PatternUnit Goes Here */
    break;
  case is_PatternInt:
    /* Code for PatternInt Goes Here */
    visitInteger(p->u.patternInt_.integer_);
    break;
  case is_PatternSucc:
    /* Code for PatternSucc Goes Here */
    visitPattern(p->u.patternSucc_.pattern_);
    break;
  case is_PatternVar:
    /* Code for PatternVar Goes Here */
    visitStellaIdent(p->u.patternVar_.stellaident_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Pattern!\n");
    exit(1);
  }
}

void visitListPattern(ListPattern listpattern)
{
  while(listpattern  != 0)
  {
    /* Code For ListPattern Goes Here */
    visitPattern(listpattern->pattern_);
    listpattern = listpattern->listpattern_;
  }
}

void visitLabelledPattern(LabelledPattern p)
{
  switch(p->kind)
  {
  case is_ALabelledPattern:
    /* Code for ALabelledPattern Goes Here */
    visitStellaIdent(p->u.aLabelledPattern_.stellaident_);
    visitPattern(p->u.aLabelledPattern_.pattern_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing LabelledPattern!\n");
    exit(1);
  }
}

void visitListLabelledPattern(ListLabelledPattern listlabelledpattern)
{
  while(listlabelledpattern  != 0)
  {
    /* Code For ListLabelledPattern Goes Here */
    visitLabelledPattern(listlabelledpattern->labelledpattern_);
    listlabelledpattern = listlabelledpattern->listlabelledpattern_;
  }
}

void visitBinding(Binding p)
{
  switch(p->kind)
  {
  case is_ABinding:
    /* Code for ABinding Goes Here */
    visitStellaIdent(p->u.aBinding_.stellaident_);
    visitExpr(p->u.aBinding_.expr_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Binding!\n");
    exit(1);
  }
}

void visitListBinding(ListBinding listbinding)
{
  while(listbinding  != 0)
  {
    /* Code For ListBinding Goes Here */
    visitBinding(listbinding->binding_);
    listbinding = listbinding->listbinding_;
  }
}

void visitExpr(Expr p)
{
  switch(p->kind)
  {
  case is_Sequence:
    /* Code for Sequence Goes Here */
    visitExpr(p->u.sequence_.expr_1);
    visitExpr(p->u.sequence_.expr_2);
    break;
  case is_Let:
    /* Code for Let Goes Here */
    visitListPatternBinding(p->u.let_.listpatternbinding_);
    visitExpr(p->u.let_.expr_);
    break;
  case is_LetRec:
    /* Code for LetRec Goes Here */
    visitListPatternBinding(p->u.letRec_.listpatternbinding_);
    visitExpr(p->u.letRec_.expr_);
    break;
  case is_ModLet:
    /* Code for ModLet Goes Here */
    visitModality(p->u.modLet_.modality_1);
    visitModality(p->u.modLet_.modality_2);
    visitListPatternBinding(p->u.modLet_.listpatternbinding_);
    visitExpr(p->u.modLet_.expr_);
    break;
  case is_TypeAbstraction:
    /* Code for TypeAbstraction Goes Here */
    visitListStellaIdent(p->u.typeAbstraction_.liststellaident_);
    visitExpr(p->u.typeAbstraction_.expr_);
    break;
  case is_Assign:
    /* Code for Assign Goes Here */
    visitExpr(p->u.assign_.expr_1);
    visitExpr(p->u.assign_.expr_2);
    break;
  case is_If:
    /* Code for If Goes Here */
    visitExpr(p->u.if_.expr_1);
    visitExpr(p->u.if_.expr_2);
    visitExpr(p->u.if_.expr_3);
    break;
  case is_LessThan:
    /* Code for LessThan Goes Here */
    visitExpr(p->u.lessThan_.expr_1);
    visitExpr(p->u.lessThan_.expr_2);
    break;
  case is_LessThanOrEqual:
    /* Code for LessThanOrEqual Goes Here */
    visitExpr(p->u.lessThanOrEqual_.expr_1);
    visitExpr(p->u.lessThanOrEqual_.expr_2);
    break;
  case is_GreaterThan:
    /* Code for GreaterThan Goes Here */
    visitExpr(p->u.greaterThan_.expr_1);
    visitExpr(p->u.greaterThan_.expr_2);
    break;
  case is_GreaterThanOrEqual:
    /* Code for GreaterThanOrEqual Goes Here */
    visitExpr(p->u.greaterThanOrEqual_.expr_1);
    visitExpr(p->u.greaterThanOrEqual_.expr_2);
    break;
  case is_Equal:
    /* Code for Equal Goes Here */
    visitExpr(p->u.equal_.expr_1);
    visitExpr(p->u.equal_.expr_2);
    break;
  case is_NotEqual:
    /* Code for NotEqual Goes Here */
    visitExpr(p->u.notEqual_.expr_1);
    visitExpr(p->u.notEqual_.expr_2);
    break;
  case is_TypeAsc:
    /* Code for TypeAsc Goes Here */
    visitExpr(p->u.typeAsc_.expr_);
    visitType(p->u.typeAsc_.type_);
    break;
  case is_TypeCast:
    /* Code for TypeCast Goes Here */
    visitExpr(p->u.typeCast_.expr_);
    visitType(p->u.typeCast_.type_);
    break;
  case is_Abstraction:
    /* Code for Abstraction Goes Here */
    visitListParamDecl(p->u.abstraction_.listparamdecl_);
    visitExpr(p->u.abstraction_.expr_);
    break;
  case is_ModBox:
    /* Code for ModBox Goes Here */
    visitModality(p->u.modBox_.modality_);
    visitExpr(p->u.modBox_.expr_);
    break;
  case is_Variant:
    /* Code for Variant Goes Here */
    visitStellaIdent(p->u.variant_.stellaident_);
    visitExprData(p->u.variant_.exprdata_);
    break;
  case is_Match:
    /* Code for Match Goes Here */
    visitExpr(p->u.match_.expr_);
    visitListMatchCase(p->u.match_.listmatchcase_);
    break;
  case is_List:
    /* Code for List Goes Here */
    visitListExpr(p->u.list_.listexpr_);
    break;
  case is_Add:
    /* Code for Add Goes Here */
    visitExpr(p->u.add_.expr_1);
    visitExpr(p->u.add_.expr_2);
    break;
  case is_Subtract:
    /* Code for Subtract Goes Here */
    visitExpr(p->u.subtract_.expr_1);
    visitExpr(p->u.subtract_.expr_2);
    break;
  case is_LogicOr:
    /* Code for LogicOr Goes Here */
    visitExpr(p->u.logicOr_.expr_1);
    visitExpr(p->u.logicOr_.expr_2);
    break;
  case is_Multiply:
    /* Code for Multiply Goes Here */
    visitExpr(p->u.multiply_.expr_1);
    visitExpr(p->u.multiply_.expr_2);
    break;
  case is_Divide:
    /* Code for Divide Goes Here */
    visitExpr(p->u.divide_.expr_1);
    visitExpr(p->u.divide_.expr_2);
    break;
  case is_LogicAnd:
    /* Code for LogicAnd Goes Here */
    visitExpr(p->u.logicAnd_.expr_1);
    visitExpr(p->u.logicAnd_.expr_2);
    break;
  case is_Ref:
    /* Code for Ref Goes Here */
    visitExpr(p->u.ref_.expr_);
    break;
  case is_Deref:
    /* Code for Deref Goes Here */
    visitExpr(p->u.deref_.expr_);
    break;
  case is_Application:
    /* Code for Application Goes Here */
    visitExpr(p->u.application_.expr_);
    visitListExpr(p->u.application_.listexpr_);
    break;
  case is_TypeApplication:
    /* Code for TypeApplication Goes Here */
    visitExpr(p->u.typeApplication_.expr_);
    visitListType(p->u.typeApplication_.listtype_);
    break;
  case is_DotRecord:
    /* Code for DotRecord Goes Here */
    visitExpr(p->u.dotRecord_.expr_);
    visitStellaIdent(p->u.dotRecord_.stellaident_);
    break;
  case is_DotTuple:
    /* Code for DotTuple Goes Here */
    visitExpr(p->u.dotTuple_.expr_);
    visitInteger(p->u.dotTuple_.integer_);
    break;
  case is_Tuple:
    /* Code for Tuple Goes Here */
    visitListExpr(p->u.tuple_.listexpr_);
    break;
  case is_Record:
    /* Code for Record Goes Here */
    visitListBinding(p->u.record_.listbinding_);
    break;
  case is_ConsList:
    /* Code for ConsList Goes Here */
    visitExpr(p->u.consList_.expr_1);
    visitExpr(p->u.consList_.expr_2);
    break;
  case is_Head:
    /* Code for Head Goes Here */
    visitExpr(p->u.head_.expr_);
    break;
  case is_IsEmpty:
    /* Code for IsEmpty Goes Here */
    visitExpr(p->u.isEmpty_.expr_);
    break;
  case is_Tail:
    /* Code for Tail Goes Here */
    visitExpr(p->u.tail_.expr_);
    break;
  case is_Panic:
    /* Code for Panic Goes Here */
    break;
  case is_Throw:
    /* Code for Throw Goes Here */
    visitExpr(p->u.throw_.expr_);
    break;
  case is_TryCatch:
    /* Code for TryCatch Goes Here */
    visitExpr(p->u.tryCatch_.expr_1);
    visitPattern(p->u.tryCatch_.pattern_);
    visitExpr(p->u.tryCatch_.expr_2);
    break;
  case is_TryWith:
    /* Code for TryWith Goes Here */
    visitExpr(p->u.tryWith_.expr_1);
    visitExpr(p->u.tryWith_.expr_2);
    break;
  case is_TryCastAs:
    /* Code for TryCastAs Goes Here */
    visitExpr(p->u.tryCastAs_.expr_1);
    visitType(p->u.tryCastAs_.type_);
    visitPattern(p->u.tryCastAs_.pattern_);
    visitExpr(p->u.tryCastAs_.expr_2);
    visitExpr(p->u.tryCastAs_.expr_3);
    break;
  case is_Inl:
    /* Code for Inl Goes Here */
    visitExpr(p->u.inl_.expr_);
    break;
  case is_Inr:
    /* Code for Inr Goes Here */
    visitExpr(p->u.inr_.expr_);
    break;
  case is_Succ:
    /* Code for Succ Goes Here */
    visitExpr(p->u.succ_.expr_);
    break;
  case is_LogicNot:
    /* Code for LogicNot Goes Here */
    visitExpr(p->u.logicNot_.expr_);
    break;
  case is_Pred:
    /* Code for Pred Goes Here */
    visitExpr(p->u.pred_.expr_);
    break;
  case is_IsZero:
    /* Code for IsZero Goes Here */
    visitExpr(p->u.isZero_.expr_);
    break;
  case is_ModDo:
    /* Code for ModDo Goes Here */
    visitStellaIdent(p->u.modDo_.stellaident_);
    visitExpr(p->u.modDo_.expr_);
    break;
  case is_ModHandle:
    /* Code for ModHandle Goes Here */
    visitExpr(p->u.modHandle_.expr_);
    visitListHandler(p->u.modHandle_.listhandler_);
    break;
  case is_Fix:
    /* Code for Fix Goes Here */
    visitExpr(p->u.fix_.expr_);
    break;
  case is_NatRec:
    /* Code for NatRec Goes Here */
    visitExpr(p->u.natRec_.expr_1);
    visitExpr(p->u.natRec_.expr_2);
    visitExpr(p->u.natRec_.expr_3);
    break;
  case is_Fold:
    /* Code for Fold Goes Here */
    visitType(p->u.fold_.type_);
    visitExpr(p->u.fold_.expr_);
    break;
  case is_Unfold:
    /* Code for Unfold Goes Here */
    visitType(p->u.unfold_.type_);
    visitExpr(p->u.unfold_.expr_);
    break;
  case is_ConstTrue:
    /* Code for ConstTrue Goes Here */
    break;
  case is_ConstFalse:
    /* Code for ConstFalse Goes Here */
    break;
  case is_ConstUnit:
    /* Code for ConstUnit Goes Here */
    break;
  case is_ConstInt:
    /* Code for ConstInt Goes Here */
    visitInteger(p->u.constInt_.integer_);
    break;
  case is_ConstMemory:
    /* Code for ConstMemory Goes Here */
    visitMemoryAddress(p->u.constMemory_.memoryaddress_);
    break;
  case is_Var:
    /* Code for Var Goes Here */
    visitStellaIdent(p->u.var_.stellaident_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Expr!\n");
    exit(1);
  }
}

void visitListExpr(ListExpr listexpr)
{
  while(listexpr  != 0)
  {
    /* Code For ListExpr Goes Here */
    visitExpr(listexpr->expr_);
    listexpr = listexpr->listexpr_;
  }
}

void visitPatternBinding(PatternBinding p)
{
  switch(p->kind)
  {
  case is_APatternBinding:
    /* Code for APatternBinding Goes Here */
    visitPattern(p->u.aPatternBinding_.pattern_);
    visitExpr(p->u.aPatternBinding_.expr_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing PatternBinding!\n");
    exit(1);
  }
}

void visitListPatternBinding(ListPatternBinding listpatternbinding)
{
  while(listpatternbinding  != 0)
  {
    /* Code For ListPatternBinding Goes Here */
    visitPatternBinding(listpatternbinding->patternbinding_);
    listpatternbinding = listpatternbinding->listpatternbinding_;
  }
}

void visitLabelledEffect(LabelledEffect p)
{
  switch(p->kind)
  {
  case is_ALabelledEffect:
    /* Code for ALabelledEffect Goes Here */
    visitStellaIdent(p->u.aLabelledEffect_.stellaident_);
    visitType(p->u.aLabelledEffect_.type_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing LabelledEffect!\n");
    exit(1);
  }
}

void visitListLabelledEffect(ListLabelledEffect listlabelledeffect)
{
  while(listlabelledeffect  != 0)
  {
    /* Code For ListLabelledEffect Goes Here */
    visitLabelledEffect(listlabelledeffect->labelledeffect_);
    listlabelledeffect = listlabelledeffect->listlabelledeffect_;
  }
}

void visitModality(Modality p)
{
  switch(p->kind)
  {
  case is_ModalityLock:
    /* Code for ModalityLock Goes Here */
    break;
  case is_ModalityAbs:
    /* Code for ModalityAbs Goes Here */
    visitListLabelledEffect(p->u.modalityAbs_.listlabelledeffect_);
    break;
  case is_ModalityRel:
    /* Code for ModalityRel Goes Here */
    visitListStellaIdent(p->u.modalityRel_.liststellaident_);
    visitListLabelledEffect(p->u.modalityRel_.listlabelledeffect_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Modality!\n");
    exit(1);
  }
}

void visitListModality(ListModality listmodality)
{
  while(listmodality  != 0)
  {
    /* Code For ListModality Goes Here */
    visitModality(listmodality->modality_);
    listmodality = listmodality->listmodality_;
  }
}

void visitHandler(Handler p)
{
  switch(p->kind)
  {
  case is_HandlerReturn:
    /* Code for HandlerReturn Goes Here */
    visitPattern(p->u.handlerReturn_.pattern_);
    visitExpr(p->u.handlerReturn_.expr_);
    break;
  case is_HandlerLabel:
    /* Code for HandlerLabel Goes Here */
    visitLabelledEffect(p->u.handlerLabel_.labelledeffect_);
    visitPattern(p->u.handlerLabel_.pattern_);
    visitStellaIdent(p->u.handlerLabel_.stellaident_);
    visitExpr(p->u.handlerLabel_.expr_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Handler!\n");
    exit(1);
  }
}

void visitListHandler(ListHandler listhandler)
{
  while(listhandler  != 0)
  {
    /* Code For ListHandler Goes Here */
    visitHandler(listhandler->handler_);
    listhandler = listhandler->listhandler_;
  }
}

void visitVariantFieldType(VariantFieldType p)
{
  switch(p->kind)
  {
  case is_AVariantFieldType:
    /* Code for AVariantFieldType Goes Here */
    visitStellaIdent(p->u.aVariantFieldType_.stellaident_);
    visitOptionalTyping(p->u.aVariantFieldType_.optionaltyping_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing VariantFieldType!\n");
    exit(1);
  }
}

void visitListVariantFieldType(ListVariantFieldType listvariantfieldtype)
{
  while(listvariantfieldtype  != 0)
  {
    /* Code For ListVariantFieldType Goes Here */
    visitVariantFieldType(listvariantfieldtype->variantfieldtype_);
    listvariantfieldtype = listvariantfieldtype->listvariantfieldtype_;
  }
}

void visitRecordFieldType(RecordFieldType p)
{
  switch(p->kind)
  {
  case is_ARecordFieldType:
    /* Code for ARecordFieldType Goes Here */
    visitStellaIdent(p->u.aRecordFieldType_.stellaident_);
    visitType(p->u.aRecordFieldType_.type_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing RecordFieldType!\n");
    exit(1);
  }
}

void visitListRecordFieldType(ListRecordFieldType listrecordfieldtype)
{
  while(listrecordfieldtype  != 0)
  {
    /* Code For ListRecordFieldType Goes Here */
    visitRecordFieldType(listrecordfieldtype->recordfieldtype_);
    listrecordfieldtype = listrecordfieldtype->listrecordfieldtype_;
  }
}

void visitTyping(Typing p)
{
  switch(p->kind)
  {
  case is_ATyping:
    /* Code for ATyping Goes Here */
    visitExpr(p->u.aTyping_.expr_);
    visitType(p->u.aTyping_.type_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Typing!\n");
    exit(1);
  }
}

void visitStellaIdent(StellaIdent p)
{
  /* Code for StellaIdent Goes Here */
}
void visitExtensionName(ExtensionName p)
{
  /* Code for ExtensionName Goes Here */
}
void visitMemoryAddress(MemoryAddress p)
{
  /* Code for MemoryAddress Goes Here */
}
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

