/* File generated by the BNF Converter (bnfc 2.9.7). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitProgram(Program p);
void visitListStellaIdent(ListStellaIdent p);
void visitLanguageDecl(LanguageDecl p);
void visitExtension(Extension p);
void visitListExtensionName(ListExtensionName p);
void visitListExtension(ListExtension p);
void visitDecl(Decl p);
void visitListDecl(ListDecl p);
void visitLocalDecl(LocalDecl p);
void visitListLocalDecl(ListLocalDecl p);
void visitAnnotation(Annotation p);
void visitListAnnotation(ListAnnotation p);
void visitParamDecl(ParamDecl p);
void visitListParamDecl(ListParamDecl p);
void visitReturnType(ReturnType p);
void visitThrowType(ThrowType p);
void visitType(Type p);
void visitListType(ListType p);
void visitMatchCase(MatchCase p);
void visitListMatchCase(ListMatchCase p);
void visitOptionalTyping(OptionalTyping p);
void visitPatternData(PatternData p);
void visitExprData(ExprData p);
void visitPattern(Pattern p);
void visitListPattern(ListPattern p);
void visitLabelledPattern(LabelledPattern p);
void visitListLabelledPattern(ListLabelledPattern p);
void visitBinding(Binding p);
void visitListBinding(ListBinding p);
void visitExpr(Expr p);
void visitListExpr(ListExpr p);
void visitPatternBinding(PatternBinding p);
void visitListPatternBinding(ListPatternBinding p);
void visitLabelledEffect(LabelledEffect p);
void visitListLabelledEffect(ListLabelledEffect p);
void visitModality(Modality p);
void visitListModality(ListModality p);
void visitHandler(Handler p);
void visitListHandler(ListHandler p);
void visitVariantFieldType(VariantFieldType p);
void visitListVariantFieldType(ListVariantFieldType p);
void visitRecordFieldType(RecordFieldType p);
void visitListRecordFieldType(ListRecordFieldType p);
void visitTyping(Typing p);

void visitStellaIdent(StellaIdent p);void visitExtensionName(ExtensionName p);void visitMemoryAddress(MemoryAddress p);
void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

