/* -*- c -*- File generated by the BNF Converter (bnfc 2.9.7). */

/* Parser definition to be used with Bison. */

/* Generate header file for lexer. */
%defines "Bison.h"

/* Reentrant parser */
%pure_parser
  /* From Bison 2.3b (2008): %define api.pure full */
%lex-param   { yyscan_t scanner }
%parse-param { yyscan_t scanner }

/* Turn on line/column tracking in the syntax_lloc structure: */
%locations

/* Argument to the parser to be filled with the parsed tree. */
%parse-param { YYSTYPE *result }

%{
/* Begin C preamble code */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "Absyn.h"

#define YYMAXDEPTH 10000000

/* The type yyscan_t is defined by flex, but we need it in the parser already. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;
extern YY_BUFFER_STATE syntax__scan_string(const char *str, yyscan_t scanner);
extern void syntax__delete_buffer(YY_BUFFER_STATE buf, yyscan_t scanner);

extern void syntax_lex_destroy(yyscan_t scanner);
extern char* syntax_get_text(yyscan_t scanner);

extern yyscan_t syntax__initialize_lexer(FILE * inp);

/* List reversal functions. */
ListStellaIdent reverseListStellaIdent(ListStellaIdent l)
{
  ListStellaIdent prev = 0;
  ListStellaIdent tmp = 0;
  while (l)
  {
    tmp = l->liststellaident_;
    l->liststellaident_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListExtensionName reverseListExtensionName(ListExtensionName l)
{
  ListExtensionName prev = 0;
  ListExtensionName tmp = 0;
  while (l)
  {
    tmp = l->listextensionname_;
    l->listextensionname_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListExtension reverseListExtension(ListExtension l)
{
  ListExtension prev = 0;
  ListExtension tmp = 0;
  while (l)
  {
    tmp = l->listextension_;
    l->listextension_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListDecl reverseListDecl(ListDecl l)
{
  ListDecl prev = 0;
  ListDecl tmp = 0;
  while (l)
  {
    tmp = l->listdecl_;
    l->listdecl_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListLocalDecl reverseListLocalDecl(ListLocalDecl l)
{
  ListLocalDecl prev = 0;
  ListLocalDecl tmp = 0;
  while (l)
  {
    tmp = l->listlocaldecl_;
    l->listlocaldecl_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListAnnotation reverseListAnnotation(ListAnnotation l)
{
  ListAnnotation prev = 0;
  ListAnnotation tmp = 0;
  while (l)
  {
    tmp = l->listannotation_;
    l->listannotation_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListParamDecl reverseListParamDecl(ListParamDecl l)
{
  ListParamDecl prev = 0;
  ListParamDecl tmp = 0;
  while (l)
  {
    tmp = l->listparamdecl_;
    l->listparamdecl_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListType reverseListType(ListType l)
{
  ListType prev = 0;
  ListType tmp = 0;
  while (l)
  {
    tmp = l->listtype_;
    l->listtype_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListMatchCase reverseListMatchCase(ListMatchCase l)
{
  ListMatchCase prev = 0;
  ListMatchCase tmp = 0;
  while (l)
  {
    tmp = l->listmatchcase_;
    l->listmatchcase_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListPattern reverseListPattern(ListPattern l)
{
  ListPattern prev = 0;
  ListPattern tmp = 0;
  while (l)
  {
    tmp = l->listpattern_;
    l->listpattern_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListLabelledPattern reverseListLabelledPattern(ListLabelledPattern l)
{
  ListLabelledPattern prev = 0;
  ListLabelledPattern tmp = 0;
  while (l)
  {
    tmp = l->listlabelledpattern_;
    l->listlabelledpattern_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListBinding reverseListBinding(ListBinding l)
{
  ListBinding prev = 0;
  ListBinding tmp = 0;
  while (l)
  {
    tmp = l->listbinding_;
    l->listbinding_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListExpr reverseListExpr(ListExpr l)
{
  ListExpr prev = 0;
  ListExpr tmp = 0;
  while (l)
  {
    tmp = l->listexpr_;
    l->listexpr_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListPatternBinding reverseListPatternBinding(ListPatternBinding l)
{
  ListPatternBinding prev = 0;
  ListPatternBinding tmp = 0;
  while (l)
  {
    tmp = l->listpatternbinding_;
    l->listpatternbinding_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListLabelledEffect reverseListLabelledEffect(ListLabelledEffect l)
{
  ListLabelledEffect prev = 0;
  ListLabelledEffect tmp = 0;
  while (l)
  {
    tmp = l->listlabelledeffect_;
    l->listlabelledeffect_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListHandler reverseListHandler(ListHandler l)
{
  ListHandler prev = 0;
  ListHandler tmp = 0;
  while (l)
  {
    tmp = l->listhandler_;
    l->listhandler_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListVariantFieldType reverseListVariantFieldType(ListVariantFieldType l)
{
  ListVariantFieldType prev = 0;
  ListVariantFieldType tmp = 0;
  while (l)
  {
    tmp = l->listvariantfieldtype_;
    l->listvariantfieldtype_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}
ListRecordFieldType reverseListRecordFieldType(ListRecordFieldType l)
{
  ListRecordFieldType prev = 0;
  ListRecordFieldType tmp = 0;
  while (l)
  {
    tmp = l->listrecordfieldtype_;
    l->listrecordfieldtype_ = prev;
    prev = l;
    l = tmp;
  }
  return prev;
}

/* End C preamble code */
%}

%union
{
  int    _int;
  char   _char;
  double _double;
  char*  _string;
  Program program_;
  ListStellaIdent liststellaident_;
  LanguageDecl languagedecl_;
  Extension extension_;
  ListExtensionName listextensionname_;
  ListExtension listextension_;
  Decl decl_;
  ListDecl listdecl_;
  LocalDecl localdecl_;
  ListLocalDecl listlocaldecl_;
  Annotation annotation_;
  ListAnnotation listannotation_;
  ParamDecl paramdecl_;
  ListParamDecl listparamdecl_;
  ReturnType returntype_;
  ThrowType throwtype_;
  Type type_;
  ListType listtype_;
  MatchCase matchcase_;
  ListMatchCase listmatchcase_;
  OptionalTyping optionaltyping_;
  PatternData patterndata_;
  ExprData exprdata_;
  Pattern pattern_;
  ListPattern listpattern_;
  LabelledPattern labelledpattern_;
  ListLabelledPattern listlabelledpattern_;
  Binding binding_;
  ListBinding listbinding_;
  Expr expr_;
  ListExpr listexpr_;
  PatternBinding patternbinding_;
  ListPatternBinding listpatternbinding_;
  LabelledEffect labelledeffect_;
  ListLabelledEffect listlabelledeffect_;
  Modality modality_;
  Handler handler_;
  ListHandler listhandler_;
  VariantFieldType variantfieldtype_;
  ListVariantFieldType listvariantfieldtype_;
  RecordFieldType recordfieldtype_;
  ListRecordFieldType listrecordfieldtype_;
  Typing typing_;
}

%{
void yyerror(YYLTYPE *loc, yyscan_t scanner, YYSTYPE *result, const char *msg)
{
  fprintf(stderr, "error: %d,%d: %s at %s\n",
    loc->first_line, loc->first_column, msg, syntax_get_text(scanner));
}

int yyparse(yyscan_t scanner, YYSTYPE *result);

extern int yylex(YYSTYPE *lvalp, YYLTYPE *llocp, yyscan_t scanner);
%}

%token          _ERROR_
%token          _BANGEQ          /* != */
%token          _AMP             /* & */
%token          _LPAREN          /* ( */
%token          _RPAREN          /* ) */
%token          _STAR            /* * */
%token          _PLUS            /* + */
%token          _COMMA           /* , */
%token          _MINUS           /* - */
%token          _RARROW          /* -> */
%token          _DOT             /* . */
%token          _SLASH           /* / */
%token          _COLON           /* : */
%token          _COLONEQ         /* := */
%token          _SEMI            /* ; */
%token          _LT              /* < */
%token          _LDARROW         /* <= */
%token          _SYMB_13         /* <| */
%token          _EQ              /* = */
%token          _DEQ             /* == */
%token          _RDARROW         /* => */
%token          _GT              /* > */
%token          _GTEQ            /* >= */
%token          _KW_Bool         /* Bool */
%token          _KW_Bot          /* Bot */
%token          _SYMB_27         /* List::head */
%token          _SYMB_28         /* List::isempty */
%token          _SYMB_29         /* List::tail */
%token          _KW_Nat          /* Nat */
%token          _SYMB_32         /* Nat::iszero */
%token          _SYMB_31         /* Nat::pred */
%token          _SYMB_33         /* Nat::rec */
%token          _KW_Top          /* Top */
%token          _KW_Unit         /* Unit */
%token          _LBRACK          /* [ */
%token          _RBRACK          /* ] */
%token          _KW_abs          /* abs */
%token          _KW_and          /* and */
%token          _KW_as           /* as */
%token          _KW_auto         /* auto */
%token          _KW_cast         /* cast */
%token          _KW_catch        /* catch */
%token          _KW_cons         /* cons */
%token          _KW_core         /* core */
%token          _KW_else         /* else */
%token          _KW_exception    /* exception */
%token          _KW_extend       /* extend */
%token          _KW_false        /* false */
%token          _KW_fix          /* fix */
%token          _KW_fn           /* fn */
%token          _KW_fold         /* fold */
%token          _KW_forall       /* forall */
%token          _KW_generic      /* generic */
%token          _KW_handle       /* handle */
%token          _KW_if           /* if */
%token          _KW_in           /* in */
%token          _KW_inl          /* inl */
%token          _KW_inline       /* inline */
%token          _KW_inr          /* inr */
%token          _KW_language     /* language */
%token          _KW_let          /* let */
%token          _KW_letrec       /* letrec */
%token          _KW_lock         /* lock */
%token          _KW_match        /* match */
%token          _KW_mod          /* mod */
%token          _KW_new          /* new */
%token          _KW_not          /* not */
%token          _KW_or           /* or */
%token          _SYMB_30         /* panic! */
%token          _KW_rel          /* rel */
%token          _KW_return       /* return */
%token          _KW_succ         /* succ */
%token          _KW_then         /* then */
%token          _KW_throw        /* throw */
%token          _KW_throws       /* throws */
%token          _KW_true         /* true */
%token          _KW_try          /* try */
%token          _KW_type         /* type */
%token          _KW_unfold       /* unfold */
%token          _KW_unit         /* unit */
%token          _KW_variant      /* variant */
%token          _KW_with         /* with */
%token          _LBRACE          /* { */
%token          _BAR             /* | */
%token          _SYMB_14         /* |> */
%token          _RBRACE          /* } */
%token          _KW_85           /* µ */
%token<_string> T_ExtensionName  /* ExtensionName */
%token<_string> T_MemoryAddress  /* MemoryAddress */
%token<_string> T_StellaIdent    /* StellaIdent */
%token<_int>    _INTEGER_

%type <program_> Program
%type <liststellaident_> ListStellaIdent
%type <languagedecl_> LanguageDecl
%type <extension_> Extension
%type <listextensionname_> ListExtensionName
%type <listextension_> ListExtension
%type <decl_> Decl
%type <listdecl_> ListDecl
%type <localdecl_> LocalDecl
%type <listlocaldecl_> ListLocalDecl
%type <annotation_> Annotation
%type <listannotation_> ListAnnotation
%type <paramdecl_> ParamDecl
%type <listparamdecl_> ListParamDecl
%type <returntype_> ReturnType
%type <throwtype_> ThrowType
%type <type_> Type9
%type <listtype_> ListType9
%type <matchcase_> MatchCase
%type <listmatchcase_> ListMatchCase
%type <optionaltyping_> OptionalTyping
%type <patterndata_> PatternData
%type <exprdata_> ExprData
%type <pattern_> Pattern
%type <listpattern_> ListPattern
%type <labelledpattern_> LabelledPattern
%type <listlabelledpattern_> ListLabelledPattern
%type <binding_> Binding
%type <listbinding_> ListBinding
%type <expr_> Expr
%type <listexpr_> ListExpr
%type <expr_> Expr1
%type <patternbinding_> PatternBinding
%type <listpatternbinding_> ListPatternBinding
%type <expr_> Expr2
%type <listexpr_> ListExpr2
%type <labelledeffect_> LabelledEffect
%type <listlabelledeffect_> ListLabelledEffect
%type <modality_> Modality
%type <expr_> Expr3
%type <expr_> Expr4
%type <expr_> Expr5
%type <expr_> Expr6
%type <expr_> Expr7
%type <handler_> Handler
%type <listhandler_> ListHandler
%type <type_> Type
%type <type_> Type1
%type <type_> Type2
%type <type_> Type3
%type <listtype_> ListType
%type <variantfieldtype_> VariantFieldType
%type <listvariantfieldtype_> ListVariantFieldType
%type <recordfieldtype_> RecordFieldType
%type <listrecordfieldtype_> ListRecordFieldType
%type <typing_> Typing

%start Program

%%

Program : LanguageDecl ListExtension ListDecl { $$ = make_AProgram($1, reverseListExtension($2), reverseListDecl($3)); result->program_ = $$; }
;
ListStellaIdent : /* empty */ { $$ = 0; result->liststellaident_ = $$; }
  | T_StellaIdent { $$ = make_ListStellaIdent($1, 0); result->liststellaident_ = $$; }
  | T_StellaIdent _COMMA ListStellaIdent { $$ = make_ListStellaIdent($1, $3); result->liststellaident_ = $$; }
;
LanguageDecl : _KW_language _KW_core _SEMI { $$ = make_LanguageCore(); result->languagedecl_ = $$; }
;
Extension : _KW_extend _KW_with ListExtensionName { $$ = make_AnExtension($3); result->extension_ = $$; }
;
ListExtensionName : /* empty */ { $$ = 0; result->listextensionname_ = $$; }
  | T_ExtensionName { $$ = make_ListExtensionName($1, 0); result->listextensionname_ = $$; }
  | T_ExtensionName _COMMA ListExtensionName { $$ = make_ListExtensionName($1, $3); result->listextensionname_ = $$; }
;
ListExtension : /* empty */ { $$ = 0; result->listextension_ = $$; }
  | ListExtension Extension _SEMI { $$ = make_ListExtension($2, $1); result->listextension_ = $$; }
;
Decl : ListAnnotation _KW_fn T_StellaIdent _LPAREN ListParamDecl _RPAREN ReturnType ThrowType _LBRACE ListDecl _KW_return Expr _RBRACE { $$ = make_DeclFun(reverseListAnnotation($1), $3, $5, $7, $8, reverseListDecl($10), $12); result->decl_ = $$; }
  | ListAnnotation _KW_generic _KW_fn T_StellaIdent _LBRACK ListStellaIdent _RBRACK _LPAREN ListParamDecl _RPAREN ReturnType ThrowType _LBRACE ListDecl _KW_return Expr _RBRACE { $$ = make_DeclFunGeneric(reverseListAnnotation($1), $4, $6, $9, $11, $12, reverseListDecl($14), $16); result->decl_ = $$; }
  | ListAnnotation _KW_mod _LBRACK Modality _RBRACK _KW_fn T_StellaIdent _LPAREN ListParamDecl _RPAREN ReturnType ThrowType _LBRACE ListDecl _KW_return Expr _RBRACE { $$ = make_DeclFunMod(reverseListAnnotation($1), $4, $7, $9, $11, $12, reverseListDecl($14), $16); result->decl_ = $$; }
  | _KW_type T_StellaIdent _EQ Type { $$ = make_DeclTypeAlias($2, $4); result->decl_ = $$; }
  | _KW_exception _KW_type _EQ Type { $$ = make_DeclExceptionType($4); result->decl_ = $$; }
  | _KW_exception _KW_variant T_StellaIdent _COLON Type { $$ = make_DeclExceptionVariant($3, $5); result->decl_ = $$; }
;
ListDecl : /* empty */ { $$ = 0; result->listdecl_ = $$; }
  | ListDecl Decl { $$ = make_ListDecl($2, $1); result->listdecl_ = $$; }
;
LocalDecl : Decl { $$ = make_ALocalDecl($1); result->localdecl_ = $$; }
;
ListLocalDecl : /* empty */ { $$ = 0; result->listlocaldecl_ = $$; }
  | ListLocalDecl LocalDecl _SEMI { $$ = make_ListLocalDecl($2, $1); result->listlocaldecl_ = $$; }
;
Annotation : _KW_inline { $$ = make_InlineAnnotation(); result->annotation_ = $$; }
;
ListAnnotation : /* empty */ { $$ = 0; result->listannotation_ = $$; }
  | ListAnnotation Annotation { $$ = make_ListAnnotation($2, $1); result->listannotation_ = $$; }
;
ParamDecl : T_StellaIdent _COLON Type { $$ = make_AParamDecl($1, $3); result->paramdecl_ = $$; }
;
ListParamDecl : /* empty */ { $$ = 0; result->listparamdecl_ = $$; }
  | ParamDecl { $$ = make_ListParamDecl($1, 0); result->listparamdecl_ = $$; }
  | ParamDecl _COMMA ListParamDecl { $$ = make_ListParamDecl($1, $3); result->listparamdecl_ = $$; }
;
ReturnType : /* empty */ { $$ = make_NoReturnType(); result->returntype_ = $$; }
  | _RARROW Type { $$ = make_SomeReturnType($2); result->returntype_ = $$; }
;
ThrowType : /* empty */ { $$ = make_NoThrowType(); result->throwtype_ = $$; }
  | _KW_throws ListType9 { $$ = make_SomeThrowType($2); result->throwtype_ = $$; }
;
Type9 : Type { $$ = $1; result->type_ = $$; }
;
ListType9 : Type9 { $$ = make_ListType($1, 0); result->listtype_ = $$; }
  | Type9 _COMMA ListType9 { $$ = make_ListType($1, $3); result->listtype_ = $$; }
;
MatchCase : Pattern _RDARROW Expr { $$ = make_AMatchCase($1, $3); result->matchcase_ = $$; }
;
ListMatchCase : /* empty */ { $$ = 0; result->listmatchcase_ = $$; }
  | MatchCase { $$ = make_ListMatchCase($1, 0); result->listmatchcase_ = $$; }
  | MatchCase _BAR ListMatchCase { $$ = make_ListMatchCase($1, $3); result->listmatchcase_ = $$; }
;
OptionalTyping : /* empty */ { $$ = make_NoTyping(); result->optionaltyping_ = $$; }
  | _COLON Type { $$ = make_SomeTyping($2); result->optionaltyping_ = $$; }
;
PatternData : /* empty */ { $$ = make_NoPatternData(); result->patterndata_ = $$; }
  | _EQ Pattern { $$ = make_SomePatternData($2); result->patterndata_ = $$; }
;
ExprData : /* empty */ { $$ = make_NoExprData(); result->exprdata_ = $$; }
  | _EQ Expr { $$ = make_SomeExprData($2); result->exprdata_ = $$; }
;
Pattern : Pattern _KW_cast _KW_as Type { $$ = make_PatternCastAs($1, $4); result->pattern_ = $$; }
  | Pattern _KW_as Type { $$ = make_PatternAsc($1, $3); result->pattern_ = $$; }
  | _SYMB_13 T_StellaIdent PatternData _SYMB_14 { $$ = make_PatternVariant($2, $3); result->pattern_ = $$; }
  | _KW_inl _LPAREN Pattern _RPAREN { $$ = make_PatternInl($3); result->pattern_ = $$; }
  | _KW_inr _LPAREN Pattern _RPAREN { $$ = make_PatternInr($3); result->pattern_ = $$; }
  | _LBRACE ListPattern _RBRACE { $$ = make_PatternTuple($2); result->pattern_ = $$; }
  | _LBRACE ListLabelledPattern _RBRACE { $$ = make_PatternRecord($2); result->pattern_ = $$; }
  | _LBRACK ListPattern _RBRACK { $$ = make_PatternList($2); result->pattern_ = $$; }
  | _KW_cons _LPAREN Pattern _COMMA Pattern _RPAREN { $$ = make_PatternCons($3, $5); result->pattern_ = $$; }
  | _LPAREN Pattern _COMMA Pattern _RPAREN { $$ = make_patternCons($2, $4); result->pattern_ = $$; }
  | _KW_false { $$ = make_PatternFalse(); result->pattern_ = $$; }
  | _KW_true { $$ = make_PatternTrue(); result->pattern_ = $$; }
  | _KW_unit { $$ = make_PatternUnit(); result->pattern_ = $$; }
  | _INTEGER_ { $$ = make_PatternInt($1); result->pattern_ = $$; }
  | _KW_succ _LPAREN Pattern _RPAREN { $$ = make_PatternSucc($3); result->pattern_ = $$; }
  | T_StellaIdent { $$ = make_PatternVar($1); result->pattern_ = $$; }
  | _LPAREN Pattern _RPAREN { $$ = $2; result->pattern_ = $$; }
;
ListPattern : /* empty */ { $$ = 0; result->listpattern_ = $$; }
  | Pattern { $$ = make_ListPattern($1, 0); result->listpattern_ = $$; }
  | Pattern _COMMA ListPattern { $$ = make_ListPattern($1, $3); result->listpattern_ = $$; }
;
LabelledPattern : T_StellaIdent _EQ Pattern { $$ = make_ALabelledPattern($1, $3); result->labelledpattern_ = $$; }
;
ListLabelledPattern : LabelledPattern { $$ = make_ListLabelledPattern($1, 0); result->listlabelledpattern_ = $$; }
  | LabelledPattern _COMMA ListLabelledPattern { $$ = make_ListLabelledPattern($1, $3); result->listlabelledpattern_ = $$; }
;
Binding : T_StellaIdent _EQ Expr { $$ = make_ABinding($1, $3); result->binding_ = $$; }
;
ListBinding : Binding { $$ = make_ListBinding($1, 0); result->listbinding_ = $$; }
  | Binding _COMMA ListBinding { $$ = make_ListBinding($1, $3); result->listbinding_ = $$; }
;
Expr : Expr1 _SEMI Expr { $$ = make_Sequence($1, $3); result->expr_ = $$; }
  | Expr1 _SEMI { $$ = $1; result->expr_ = $$; }
  | _KW_let ListPatternBinding _KW_in Expr { $$ = make_Let($2, $4); result->expr_ = $$; }
  | _KW_letrec ListPatternBinding _KW_in Expr { $$ = make_LetRec($2, $4); result->expr_ = $$; }
  | _KW_generic _LBRACK ListStellaIdent _RBRACK Expr { $$ = make_TypeAbstraction($3, $5); result->expr_ = $$; }
  | Expr1 { $$ = $1; result->expr_ = $$; }
;
ListExpr : /* empty */ { $$ = 0; result->listexpr_ = $$; }
  | Expr { $$ = make_ListExpr($1, 0); result->listexpr_ = $$; }
  | Expr _COMMA ListExpr { $$ = make_ListExpr($1, $3); result->listexpr_ = $$; }
;
Expr1 : Expr2 _COLONEQ Expr1 { $$ = make_Assign($1, $3); result->expr_ = $$; }
  | _KW_if Expr1 _KW_then Expr1 _KW_else Expr1 { $$ = make_If($2, $4, $6); result->expr_ = $$; }
  | Expr2 { $$ = $1; result->expr_ = $$; }
;
PatternBinding : Pattern _EQ Expr { $$ = make_APatternBinding($1, $3); result->patternbinding_ = $$; }
;
ListPatternBinding : PatternBinding { $$ = make_ListPatternBinding($1, 0); result->listpatternbinding_ = $$; }
  | PatternBinding _COMMA ListPatternBinding { $$ = make_ListPatternBinding($1, $3); result->listpatternbinding_ = $$; }
;
Expr2 : Expr3 _LT Expr3 { $$ = make_LessThan($1, $3); result->expr_ = $$; }
  | Expr3 _LDARROW Expr3 { $$ = make_LessThanOrEqual($1, $3); result->expr_ = $$; }
  | Expr3 _GT Expr3 { $$ = make_GreaterThan($1, $3); result->expr_ = $$; }
  | Expr3 _GTEQ Expr3 { $$ = make_GreaterThanOrEqual($1, $3); result->expr_ = $$; }
  | Expr3 _DEQ Expr3 { $$ = make_Equal($1, $3); result->expr_ = $$; }
  | Expr3 _BANGEQ Expr3 { $$ = make_NotEqual($1, $3); result->expr_ = $$; }
  | Expr3 { $$ = $1; result->expr_ = $$; }
;
ListExpr2 : Expr2 _SEMI { $$ = make_ListExpr($1, 0); result->listexpr_ = $$; }
  | Expr2 _SEMI ListExpr2 { $$ = make_ListExpr($1, $3); result->listexpr_ = $$; }
;
LabelledEffect : T_StellaIdent _COLON Type { $$ = make_ALabelledEffect($1, $3); result->labelledeffect_ = $$; }
;
ListLabelledEffect : /* empty */ { $$ = 0; result->listlabelledeffect_ = $$; }
  | LabelledEffect { $$ = make_ListLabelledEffect($1, 0); result->listlabelledeffect_ = $$; }
  | LabelledEffect _COMMA ListLabelledEffect { $$ = make_ListLabelledEffect($1, $3); result->listlabelledeffect_ = $$; }
;
Modality : _KW_lock { $$ = make_ModalityLock(); result->modality_ = $$; }
  | _KW_abs _LT ListLabelledEffect _GT { $$ = make_ModalityAbs($3); result->modality_ = $$; }
  | _KW_rel _LT ListStellaIdent _BAR ListLabelledEffect _GT { $$ = make_ModalityRel($3, $5); result->modality_ = $$; }
;
Expr3 : Expr3 _KW_as Type2 { $$ = make_TypeAsc($1, $3); result->expr_ = $$; }
  | Expr3 _KW_cast _KW_as Type2 { $$ = make_TypeCast($1, $4); result->expr_ = $$; }
  | _KW_fn _LPAREN ListParamDecl _RPAREN _LBRACE _KW_return Expr _RBRACE { $$ = make_Abstraction($3, $7); result->expr_ = $$; }
  | _KW_mod _LBRACK Modality _RBRACK _LBRACE Expr _RBRACE { $$ = make_ModBox($3, $6); result->expr_ = $$; }
  | _SYMB_13 T_StellaIdent ExprData _SYMB_14 { $$ = make_Variant($2, $3); result->expr_ = $$; }
  | _KW_match Expr2 _LBRACE ListMatchCase _RBRACE { $$ = make_Match($2, $4); result->expr_ = $$; }
  | _LBRACK ListExpr _RBRACK { $$ = make_List($2); result->expr_ = $$; }
  | Expr3 _PLUS Expr4 { $$ = make_Add($1, $3); result->expr_ = $$; }
  | Expr3 _MINUS Expr4 { $$ = make_Subtract($1, $3); result->expr_ = $$; }
  | Expr3 _KW_or Expr4 { $$ = make_LogicOr($1, $3); result->expr_ = $$; }
  | Expr4 { $$ = $1; result->expr_ = $$; }
;
Expr4 : Expr4 _STAR Expr5 { $$ = make_Multiply($1, $3); result->expr_ = $$; }
  | Expr4 _SLASH Expr5 { $$ = make_Divide($1, $3); result->expr_ = $$; }
  | Expr4 _KW_and Expr5 { $$ = make_LogicAnd($1, $3); result->expr_ = $$; }
  | Expr5 { $$ = $1; result->expr_ = $$; }
;
Expr5 : _KW_new _LPAREN Expr _RPAREN { $$ = make_Ref($3); result->expr_ = $$; }
  | _STAR Expr5 { $$ = make_Deref($2); result->expr_ = $$; }
  | Expr6 { $$ = $1; result->expr_ = $$; }
;
Expr6 : Expr6 _LPAREN ListExpr _RPAREN { $$ = make_Application($1, $3); result->expr_ = $$; }
  | Expr6 _LBRACK ListType _RBRACK { $$ = make_TypeApplication($1, $3); result->expr_ = $$; }
  | Expr6 _DOT T_StellaIdent { $$ = make_DotRecord($1, $3); result->expr_ = $$; }
  | Expr6 _DOT _INTEGER_ { $$ = make_DotTuple($1, $3); result->expr_ = $$; }
  | _LBRACE ListExpr _RBRACE { $$ = make_Tuple($2); result->expr_ = $$; }
  | _LBRACE ListBinding _RBRACE { $$ = make_Record($2); result->expr_ = $$; }
  | _KW_cons _LPAREN Expr _COMMA Expr _RPAREN { $$ = make_ConsList($3, $5); result->expr_ = $$; }
  | _SYMB_27 _LPAREN Expr _RPAREN { $$ = make_Head($3); result->expr_ = $$; }
  | _SYMB_28 _LPAREN Expr _RPAREN { $$ = make_IsEmpty($3); result->expr_ = $$; }
  | _SYMB_29 _LPAREN Expr _RPAREN { $$ = make_Tail($3); result->expr_ = $$; }
  | _SYMB_30 { $$ = make_Panic(); result->expr_ = $$; }
  | _KW_throw _LPAREN Expr _RPAREN { $$ = make_Throw($3); result->expr_ = $$; }
  | _KW_try _LBRACE Expr _RBRACE _KW_catch _LBRACE Pattern _RDARROW Expr _RBRACE { $$ = make_TryCatch($3, $7, $9); result->expr_ = $$; }
  | _KW_try _LBRACE Expr _RBRACE _KW_with _LBRACE Expr _RBRACE { $$ = make_TryWith($3, $7); result->expr_ = $$; }
  | _KW_try _LBRACE Expr _RBRACE _KW_cast _KW_as Type _LBRACE Pattern _RDARROW Expr _RBRACE _KW_with _LBRACE Expr _RBRACE { $$ = make_TryCastAs($3, $7, $9, $11, $15); result->expr_ = $$; }
  | _KW_inl _LPAREN Expr _RPAREN { $$ = make_Inl($3); result->expr_ = $$; }
  | _KW_inr _LPAREN Expr _RPAREN { $$ = make_Inr($3); result->expr_ = $$; }
  | _KW_succ _LPAREN Expr _RPAREN { $$ = make_Succ($3); result->expr_ = $$; }
  | _KW_not _LPAREN Expr _RPAREN { $$ = make_LogicNot($3); result->expr_ = $$; }
  | _SYMB_31 _LPAREN Expr _RPAREN { $$ = make_Pred($3); result->expr_ = $$; }
  | _SYMB_32 _LPAREN Expr _RPAREN { $$ = make_IsZero($3); result->expr_ = $$; }
  | _KW_handle _LBRACE Expr _RBRACE _KW_with _LBRACE ListHandler _RBRACE { $$ = make_Handle($3, $7); result->expr_ = $$; }
  | _KW_fix _LPAREN Expr _RPAREN { $$ = make_Fix($3); result->expr_ = $$; }
  | _SYMB_33 _LPAREN Expr _COMMA Expr _COMMA Expr _RPAREN { $$ = make_NatRec($3, $5, $7); result->expr_ = $$; }
  | _KW_fold _LBRACK Type _RBRACK Expr7 { $$ = make_Fold($3, $5); result->expr_ = $$; }
  | _KW_unfold _LBRACK Type _RBRACK Expr7 { $$ = make_Unfold($3, $5); result->expr_ = $$; }
  | Expr7 { $$ = $1; result->expr_ = $$; }
;
Expr7 : _KW_true { $$ = make_ConstTrue(); result->expr_ = $$; }
  | _KW_false { $$ = make_ConstFalse(); result->expr_ = $$; }
  | _KW_unit { $$ = make_ConstUnit(); result->expr_ = $$; }
  | _INTEGER_ { $$ = make_ConstInt($1); result->expr_ = $$; }
  | T_MemoryAddress { $$ = make_ConstMemory($1); result->expr_ = $$; }
  | T_StellaIdent { $$ = make_Var($1); result->expr_ = $$; }
  | _LPAREN Expr _RPAREN { $$ = $2; result->expr_ = $$; }
;
Handler : _KW_return Pattern _RARROW Expr { $$ = make_HandlerReturn($2, $4); result->handler_ = $$; }
  | _LPAREN LabelledEffect _COMMA Expr _COMMA T_StellaIdent _RPAREN _RARROW Expr { $$ = make_HandlerLabel($2, $4, $6, $9); result->handler_ = $$; }
;
ListHandler : Handler _SEMI { $$ = make_ListHandler($1, 0); result->listhandler_ = $$; }
  | Handler _SEMI ListHandler { $$ = make_ListHandler($1, $3); result->listhandler_ = $$; }
;
Type : _LBRACK Modality _RBRACK Type { $$ = make_TypeMod($2, $4); result->type_ = $$; }
  | _KW_auto { $$ = make_TypeAuto(); result->type_ = $$; }
  | _KW_fn _LPAREN ListType _RPAREN _RARROW Type { $$ = make_TypeFun($3, $6); result->type_ = $$; }
  | _KW_forall ListStellaIdent _DOT Type { $$ = make_TypeForAll($2, $4); result->type_ = $$; }
  | _KW_85 T_StellaIdent _DOT Type { $$ = make_TypeRec($2, $4); result->type_ = $$; }
  | Type1 { $$ = $1; result->type_ = $$; }
;
Type1 : Type2 _PLUS Type2 { $$ = make_TypeSum($1, $3); result->type_ = $$; }
  | Type2 { $$ = $1; result->type_ = $$; }
;
Type2 : _LBRACE ListType _RBRACE { $$ = make_TypeTuple($2); result->type_ = $$; }
  | _LBRACE ListRecordFieldType _RBRACE { $$ = make_TypeRecord($2); result->type_ = $$; }
  | _SYMB_13 ListVariantFieldType _SYMB_14 { $$ = make_TypeVariant($2); result->type_ = $$; }
  | _LBRACK Type _RBRACK { $$ = make_TypeList($2); result->type_ = $$; }
  | Type3 { $$ = $1; result->type_ = $$; }
;
Type3 : _KW_Bool { $$ = make_TypeBool(); result->type_ = $$; }
  | _KW_Nat { $$ = make_TypeNat(); result->type_ = $$; }
  | _KW_Unit { $$ = make_TypeUnit(); result->type_ = $$; }
  | _KW_Top { $$ = make_TypeTop(); result->type_ = $$; }
  | _KW_Bot { $$ = make_TypeBottom(); result->type_ = $$; }
  | _AMP Type2 { $$ = make_TypeRef($2); result->type_ = $$; }
  | T_StellaIdent { $$ = make_TypeVar($1); result->type_ = $$; }
  | _LPAREN Type _RPAREN { $$ = $2; result->type_ = $$; }
;
ListType : /* empty */ { $$ = 0; result->listtype_ = $$; }
  | Type { $$ = make_ListType($1, 0); result->listtype_ = $$; }
  | Type _COMMA ListType { $$ = make_ListType($1, $3); result->listtype_ = $$; }
;
VariantFieldType : T_StellaIdent OptionalTyping { $$ = make_AVariantFieldType($1, $2); result->variantfieldtype_ = $$; }
;
ListVariantFieldType : /* empty */ { $$ = 0; result->listvariantfieldtype_ = $$; }
  | VariantFieldType { $$ = make_ListVariantFieldType($1, 0); result->listvariantfieldtype_ = $$; }
  | VariantFieldType _COMMA ListVariantFieldType { $$ = make_ListVariantFieldType($1, $3); result->listvariantfieldtype_ = $$; }
;
RecordFieldType : T_StellaIdent _COLON Type { $$ = make_ARecordFieldType($1, $3); result->recordfieldtype_ = $$; }
;
ListRecordFieldType : RecordFieldType { $$ = make_ListRecordFieldType($1, 0); result->listrecordfieldtype_ = $$; }
  | RecordFieldType _COMMA ListRecordFieldType { $$ = make_ListRecordFieldType($1, $3); result->listrecordfieldtype_ = $$; }
;
Typing : Expr _COLON Type { $$ = make_ATyping($1, $3); result->typing_ = $$; }
;

%%


/* Entrypoint: parse Program from file. */
Program pProgram(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.program_;
  }
}

/* Entrypoint: parse Program from string. */
Program psProgram(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.program_;
  }
}

/* Entrypoint: parse ListStellaIdent from file. */
ListStellaIdent pListStellaIdent(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.liststellaident_;
  }
}

/* Entrypoint: parse ListStellaIdent from string. */
ListStellaIdent psListStellaIdent(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.liststellaident_;
  }
}

/* Entrypoint: parse LanguageDecl from file. */
LanguageDecl pLanguageDecl(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.languagedecl_;
  }
}

/* Entrypoint: parse LanguageDecl from string. */
LanguageDecl psLanguageDecl(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.languagedecl_;
  }
}

/* Entrypoint: parse Extension from file. */
Extension pExtension(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.extension_;
  }
}

/* Entrypoint: parse Extension from string. */
Extension psExtension(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.extension_;
  }
}

/* Entrypoint: parse ListExtensionName from file. */
ListExtensionName pListExtensionName(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listextensionname_;
  }
}

/* Entrypoint: parse ListExtensionName from string. */
ListExtensionName psListExtensionName(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listextensionname_;
  }
}

/* Entrypoint: parse ListExtension from file. */
ListExtension pListExtension(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return reverseListExtension(result.listextension_);
  }
}

/* Entrypoint: parse ListExtension from string. */
ListExtension psListExtension(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return reverseListExtension(result.listextension_);
  }
}

/* Entrypoint: parse Decl from file. */
Decl pDecl(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.decl_;
  }
}

/* Entrypoint: parse Decl from string. */
Decl psDecl(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.decl_;
  }
}

/* Entrypoint: parse ListDecl from file. */
ListDecl pListDecl(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return reverseListDecl(result.listdecl_);
  }
}

/* Entrypoint: parse ListDecl from string. */
ListDecl psListDecl(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return reverseListDecl(result.listdecl_);
  }
}

/* Entrypoint: parse LocalDecl from file. */
LocalDecl pLocalDecl(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.localdecl_;
  }
}

/* Entrypoint: parse LocalDecl from string. */
LocalDecl psLocalDecl(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.localdecl_;
  }
}

/* Entrypoint: parse ListLocalDecl from file. */
ListLocalDecl pListLocalDecl(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return reverseListLocalDecl(result.listlocaldecl_);
  }
}

/* Entrypoint: parse ListLocalDecl from string. */
ListLocalDecl psListLocalDecl(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return reverseListLocalDecl(result.listlocaldecl_);
  }
}

/* Entrypoint: parse Annotation from file. */
Annotation pAnnotation(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.annotation_;
  }
}

/* Entrypoint: parse Annotation from string. */
Annotation psAnnotation(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.annotation_;
  }
}

/* Entrypoint: parse ListAnnotation from file. */
ListAnnotation pListAnnotation(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return reverseListAnnotation(result.listannotation_);
  }
}

/* Entrypoint: parse ListAnnotation from string. */
ListAnnotation psListAnnotation(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return reverseListAnnotation(result.listannotation_);
  }
}

/* Entrypoint: parse ParamDecl from file. */
ParamDecl pParamDecl(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.paramdecl_;
  }
}

/* Entrypoint: parse ParamDecl from string. */
ParamDecl psParamDecl(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.paramdecl_;
  }
}

/* Entrypoint: parse ListParamDecl from file. */
ListParamDecl pListParamDecl(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listparamdecl_;
  }
}

/* Entrypoint: parse ListParamDecl from string. */
ListParamDecl psListParamDecl(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listparamdecl_;
  }
}

/* Entrypoint: parse ReturnType from file. */
ReturnType pReturnType(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.returntype_;
  }
}

/* Entrypoint: parse ReturnType from string. */
ReturnType psReturnType(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.returntype_;
  }
}

/* Entrypoint: parse ThrowType from file. */
ThrowType pThrowType(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.throwtype_;
  }
}

/* Entrypoint: parse ThrowType from string. */
ThrowType psThrowType(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.throwtype_;
  }
}

/* Entrypoint: parse Type from file. */
Type pType9(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.type_;
  }
}

/* Entrypoint: parse Type from string. */
Type psType9(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.type_;
  }
}

/* Entrypoint: parse ListType from file. */
ListType pListType9(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listtype_;
  }
}

/* Entrypoint: parse ListType from string. */
ListType psListType9(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listtype_;
  }
}

/* Entrypoint: parse MatchCase from file. */
MatchCase pMatchCase(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.matchcase_;
  }
}

/* Entrypoint: parse MatchCase from string. */
MatchCase psMatchCase(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.matchcase_;
  }
}

/* Entrypoint: parse ListMatchCase from file. */
ListMatchCase pListMatchCase(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listmatchcase_;
  }
}

/* Entrypoint: parse ListMatchCase from string. */
ListMatchCase psListMatchCase(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listmatchcase_;
  }
}

/* Entrypoint: parse OptionalTyping from file. */
OptionalTyping pOptionalTyping(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.optionaltyping_;
  }
}

/* Entrypoint: parse OptionalTyping from string. */
OptionalTyping psOptionalTyping(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.optionaltyping_;
  }
}

/* Entrypoint: parse PatternData from file. */
PatternData pPatternData(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.patterndata_;
  }
}

/* Entrypoint: parse PatternData from string. */
PatternData psPatternData(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.patterndata_;
  }
}

/* Entrypoint: parse ExprData from file. */
ExprData pExprData(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.exprdata_;
  }
}

/* Entrypoint: parse ExprData from string. */
ExprData psExprData(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.exprdata_;
  }
}

/* Entrypoint: parse Pattern from file. */
Pattern pPattern(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.pattern_;
  }
}

/* Entrypoint: parse Pattern from string. */
Pattern psPattern(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.pattern_;
  }
}

/* Entrypoint: parse ListPattern from file. */
ListPattern pListPattern(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listpattern_;
  }
}

/* Entrypoint: parse ListPattern from string. */
ListPattern psListPattern(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listpattern_;
  }
}

/* Entrypoint: parse LabelledPattern from file. */
LabelledPattern pLabelledPattern(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.labelledpattern_;
  }
}

/* Entrypoint: parse LabelledPattern from string. */
LabelledPattern psLabelledPattern(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.labelledpattern_;
  }
}

/* Entrypoint: parse ListLabelledPattern from file. */
ListLabelledPattern pListLabelledPattern(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listlabelledpattern_;
  }
}

/* Entrypoint: parse ListLabelledPattern from string. */
ListLabelledPattern psListLabelledPattern(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listlabelledpattern_;
  }
}

/* Entrypoint: parse Binding from file. */
Binding pBinding(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.binding_;
  }
}

/* Entrypoint: parse Binding from string. */
Binding psBinding(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.binding_;
  }
}

/* Entrypoint: parse ListBinding from file. */
ListBinding pListBinding(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listbinding_;
  }
}

/* Entrypoint: parse ListBinding from string. */
ListBinding psListBinding(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listbinding_;
  }
}

/* Entrypoint: parse Expr from file. */
Expr pExpr(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from string. */
Expr psExpr(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse ListExpr from file. */
ListExpr pListExpr(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listexpr_;
  }
}

/* Entrypoint: parse ListExpr from string. */
ListExpr psListExpr(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listexpr_;
  }
}

/* Entrypoint: parse Expr from file. */
Expr pExpr1(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from string. */
Expr psExpr1(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse PatternBinding from file. */
PatternBinding pPatternBinding(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.patternbinding_;
  }
}

/* Entrypoint: parse PatternBinding from string. */
PatternBinding psPatternBinding(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.patternbinding_;
  }
}

/* Entrypoint: parse ListPatternBinding from file. */
ListPatternBinding pListPatternBinding(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listpatternbinding_;
  }
}

/* Entrypoint: parse ListPatternBinding from string. */
ListPatternBinding psListPatternBinding(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listpatternbinding_;
  }
}

/* Entrypoint: parse Expr from file. */
Expr pExpr2(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from string. */
Expr psExpr2(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse ListExpr from file. */
ListExpr pListExpr2(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listexpr_;
  }
}

/* Entrypoint: parse ListExpr from string. */
ListExpr psListExpr2(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listexpr_;
  }
}

/* Entrypoint: parse LabelledEffect from file. */
LabelledEffect pLabelledEffect(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.labelledeffect_;
  }
}

/* Entrypoint: parse LabelledEffect from string. */
LabelledEffect psLabelledEffect(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.labelledeffect_;
  }
}

/* Entrypoint: parse ListLabelledEffect from file. */
ListLabelledEffect pListLabelledEffect(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listlabelledeffect_;
  }
}

/* Entrypoint: parse ListLabelledEffect from string. */
ListLabelledEffect psListLabelledEffect(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listlabelledeffect_;
  }
}

/* Entrypoint: parse Modality from file. */
Modality pModality(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.modality_;
  }
}

/* Entrypoint: parse Modality from string. */
Modality psModality(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.modality_;
  }
}

/* Entrypoint: parse Expr from file. */
Expr pExpr3(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from string. */
Expr psExpr3(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from file. */
Expr pExpr4(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from string. */
Expr psExpr4(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from file. */
Expr pExpr5(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from string. */
Expr psExpr5(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from file. */
Expr pExpr6(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from string. */
Expr psExpr6(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from file. */
Expr pExpr7(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Expr from string. */
Expr psExpr7(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.expr_;
  }
}

/* Entrypoint: parse Handler from file. */
Handler pHandler(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.handler_;
  }
}

/* Entrypoint: parse Handler from string. */
Handler psHandler(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.handler_;
  }
}

/* Entrypoint: parse ListHandler from file. */
ListHandler pListHandler(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listhandler_;
  }
}

/* Entrypoint: parse ListHandler from string. */
ListHandler psListHandler(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listhandler_;
  }
}

/* Entrypoint: parse Type from file. */
Type pType(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.type_;
  }
}

/* Entrypoint: parse Type from string. */
Type psType(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.type_;
  }
}

/* Entrypoint: parse Type from file. */
Type pType1(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.type_;
  }
}

/* Entrypoint: parse Type from string. */
Type psType1(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.type_;
  }
}

/* Entrypoint: parse Type from file. */
Type pType2(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.type_;
  }
}

/* Entrypoint: parse Type from string. */
Type psType2(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.type_;
  }
}

/* Entrypoint: parse Type from file. */
Type pType3(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.type_;
  }
}

/* Entrypoint: parse Type from string. */
Type psType3(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.type_;
  }
}

/* Entrypoint: parse ListType from file. */
ListType pListType(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listtype_;
  }
}

/* Entrypoint: parse ListType from string. */
ListType psListType(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listtype_;
  }
}

/* Entrypoint: parse VariantFieldType from file. */
VariantFieldType pVariantFieldType(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.variantfieldtype_;
  }
}

/* Entrypoint: parse VariantFieldType from string. */
VariantFieldType psVariantFieldType(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.variantfieldtype_;
  }
}

/* Entrypoint: parse ListVariantFieldType from file. */
ListVariantFieldType pListVariantFieldType(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listvariantfieldtype_;
  }
}

/* Entrypoint: parse ListVariantFieldType from string. */
ListVariantFieldType psListVariantFieldType(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listvariantfieldtype_;
  }
}

/* Entrypoint: parse RecordFieldType from file. */
RecordFieldType pRecordFieldType(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.recordfieldtype_;
  }
}

/* Entrypoint: parse RecordFieldType from string. */
RecordFieldType psRecordFieldType(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.recordfieldtype_;
  }
}

/* Entrypoint: parse ListRecordFieldType from file. */
ListRecordFieldType pListRecordFieldType(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listrecordfieldtype_;
  }
}

/* Entrypoint: parse ListRecordFieldType from string. */
ListRecordFieldType psListRecordFieldType(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.listrecordfieldtype_;
  }
}

/* Entrypoint: parse Typing from file. */
Typing pTyping(FILE *inp)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(inp);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  int error = yyparse(scanner, &result);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.typing_;
  }
}

/* Entrypoint: parse Typing from string. */
Typing psTyping(const char *str)
{
  YYSTYPE result;
  yyscan_t scanner = syntax__initialize_lexer(0);
  if (!scanner) {
    fprintf(stderr, "Failed to initialize lexer.\n");
    return 0;
  }
  YY_BUFFER_STATE buf = syntax__scan_string(str, scanner);
  int error = yyparse(scanner, &result);
  syntax__delete_buffer(buf, scanner);
  syntax_lex_destroy(scanner);
  if (error)
  { /* Failure */
    return 0;
  }
  else
  { /* Success */
    return result.typing_;
  }
}



